import type { CharacterMotion } from "./types.js"

/** Animals & Pets — 28 entries. Category id `animals-pets`. */
export const ANIMALS_PETS_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "pet-a-dog", label: "Pet a Dog", category: "animals-pets", description: "Flat hand strokes over the dog's skull and neck",
    promptHint: "the subject lowers an open hand onto a dog's head, draws the flat palm back over the skull to the base of the neck, lifts the hand away and repeats the stroke",
    term: "pets a dog on the head" },
  { id: "scratch-behind-ears", label: "Scratch Behind Ears", category: "animals-pets", description: "Fingertips work in small circles behind an ear",
    promptHint: "the subject reaches to the side of an animal's head and works curled fingertips in small circles behind one ear, the wrist rocking, the other hand resting under the muzzle",
    term: "scratches behind the ears" },
  { id: "ruffle-dog-fur", label: "Ruffle Dog Fur", category: "animals-pets", description: "Fingers scrub through the thick fur at the neck",
    promptHint: "the subject sinks the fingers deep into the thick fur at a dog's neck and scrubs them briskly back and forth through the coat, elbows pumping, then opens the fingers and lifts the hands away",
    term: "ruffles a dog's fur with both hands" },
  { id: "scoop-up-pet", label: "Scoop Up Pet", category: "animals-pets", description: "Bends, slides both hands under, lifts to the chest",
    promptHint: "the subject bends at the knees, slides one hand under a small pet's chest and the other under its hindquarters, and straightens upright, drawing the animal in against the subject's chest",
    term: "scoops up a small pet" },
  { id: "offer-hand-to-sniff", label: "Offer Hand to Sniff", category: "animals-pets", description: "Arm extends, knuckles down, hand held still",
    promptHint: "the subject extends one arm forward at waist height with the fingers curled and the knuckles down, stops the hand short of the animal and holds it motionless, shoulders loose",
    term: "holds out a hand to be sniffed" },
  { id: "offer-a-treat", label: "Offer a Treat", category: "animals-pets", description: "Flat open palm held out at arm length",
    promptHint: "the subject brings a treat out of a pocket, flattens the palm with the fingers pressed straight, extends the arm forward at waist height and holds the hand steady while a dog lips the treat off the open palm",
    term: "offers a treat on an open palm" },
  { id: "get-pulled-by-leash", label: "Get Pulled by Leash", category: "animals-pets", description: "Leash snaps taut and drags the arm forward",
    promptHint: "the subject is yanked forward as the leash snaps taut and stumbles a step with one shoulder dragged ahead of the torso, then leans the weight back and digs the heels in",
    term: "gets pulled along by the leash" },
  { id: "reel-in-leash", label: "Reel In Leash", category: "animals-pets", description: "Hand over hand shortens the leash",
    promptHint: "the subject gathers the leash hand over hand, each fist closing on the line and drawing it back to the hip until the slack is gone, the elbow tucked tight against the ribs",
    term: "reels in the leash hand over hand" },
  { id: "throw-ball-for-dog", label: "Throw Ball for Dog", category: "animals-pets", description: "Overhand wind-up, release, follow-through",
    promptHint: "the subject cocks the throwing arm back past the shoulder, steps onto the front foot, whips the arm forward and releases a ball, the hand following through down across the opposite hip",
    term: "throws a ball for a dog" },
  { id: "kneel-to-greet", label: "Kneel to Greet", category: "animals-pets", description: "Drops to one knee and opens both arms",
    promptHint: "the subject drops onto one knee, spreads both arms wide and leans the chest forward, closing both hands around a dog's shoulders and rocking back slightly under the weight",
    term: "kneels down to greet a dog" },
  { id: "signal-dog-to-sit", label: "Signal Dog to Sit", category: "animals-pets", description: "Flat palm raised, then pressed down and held",
    promptHint: "the subject raises one flat palm to chest height, holds it still for a beat, and presses the hand down toward the ground in a firm level push, freezing it there",
    term: "signals a dog to sit" },
  { id: "call-dog-over", label: "Call Dog Over", category: "animals-pets", description: "Slaps thighs, whistles, crouches with arms open",
    promptHint: "the subject slaps both palms against the thighs twice, cups one hand beside the mouth to whistle, and drops into a crouch with the arms spread open and waiting",
    term: "calls a dog over" },
  { id: "cuddle-pet-on-lap", label: "Cuddle Pet on Lap", category: "animals-pets", description: "Curls over a pet on the lap and strokes its back",
    promptHint: "the subject curls the shoulders forward over a pet settled across the lap, runs one hand in long strokes down its back and lets the chin drop toward it",
    term: "cuddles a pet on the lap" },
  { id: "hold-cat-to-chest", label: "Hold Cat to Chest", category: "animals-pets", description: "Gathers a cat up against the sternum",
    promptHint: "the subject gathers a cat up against the chest, one forearm braced under its hindquarters and the other hand flat along its back, and lowers the chin toward its head",
    term: "holds a cat against the chest" },
  { id: "lift-cat-up", label: "Lift Cat Up", category: "animals-pets", description: "Chest and hindquarters supported, lifted to eye level",
    promptHint: "the subject slides one hand under a cat's chest just behind the front legs and the other under its hindquarters, lifts it up to eye level as the arms extend, holds it there a beat before drawing it back in against the chest",
    term: "lifts a cat up to eye level" },
  { id: "lift-puppy-to-face", label: "Lift Puppy to Face", category: "animals-pets", description: "Raises a puppy up nose to nose",
    promptHint: "the subject raises a puppy in both hands from lap height up to eye level, lifts the chin and leans in until the two are nose to nose, then lowers the puppy back down against the subject's chest",
    term: "holds a puppy up to the face" },
  { id: "let-bird-perch", label: "Let Bird Perch", category: "animals-pets", description: "Index finger held out level and steady",
    promptHint: "the subject holds one index finger out level in front of the chest and locks the elbow against the ribs to keep the hand from shaking, lifting the whole arm upward as a bird steps onto the finger",
    term: "holds out a finger for a bird" },
  { id: "feed-the-ducks", label: "Feed the Ducks", category: "animals-pets", description: "Breaks off pieces and tosses them underhand",
    promptHint: "the subject reaches into a bag, pinches off small pieces and flicks them out underhand one after another with a loose wrist, stepping back a pace between tosses",
    term: "feeds the ducks" },
  { id: "stroke-horse-neck", label: "Stroke Horse Neck", category: "animals-pets", description: "Long flat-palm sweeps down the neck",
    promptHint: "the subject lays a flat palm high on a horse's neck and sweeps it down the length of the crest in long full strokes, the other hand resting at the horse's shoulder",
    term: "strokes a horse's neck" },
  { id: "brush-the-horse", label: "Brush the Horse", category: "animals-pets", description: "Long brush strokes along the lie of the coat",
    promptHint: "the subject presses a brush to a horse's flank and pulls it in long strokes along the lie of the coat, the free hand steadying the horse ahead of each pass, the shoulder swinging with the motion",
    term: "brushes a horse's coat" },
  { id: "pat-horse-flank", label: "Pat Horse Flank", category: "animals-pets", description: "Two firm open-palm pats, then rests the hand",
    promptHint: "the subject brings a flat hand in to pat a horse's flank twice with a firm open palm, then leaves the hand resting there and leans a little weight onto it",
    term: "pats a horse on the flank" },
  { id: "mount-the-horse", label: "Mount the Horse", category: "animals-pets", description: "Foot in the stirrup, swings the leg over",
    promptHint: "the subject sets one foot into the stirrup, grips the saddle with both hands, springs off the ground and swings the trailing leg over, then settles down and finds the other stirrup",
    term: "mounts a horse" },
  { id: "back-away-slowly", label: "Back Away Slowly", category: "animals-pets", description: "Small heel-first steps back, palms raised",
    promptHint: "the subject shifts the weight onto the back foot and takes small heel-first steps backward, palms raised open at chest height, the torso staying square and the gaze fixed forward",
    term: "backs away slowly from an animal" },
  { id: "let-it-approach", label: "Let It Approach", category: "animals-pets", description: "Goes completely still and waits it out",
    promptHint: "the subject stops mid-step and goes completely still, arms hanging loose at the sides, the breathing shallow so the chest barely moves, only the eyes tracking the animal",
    term: "freezes as an animal comes near" },
  { id: "crouch-to-photograph", label: "Crouch to Photograph", category: "animals-pets", description: "Drops low and frames the animal with a phone",
    promptHint: "the subject drops into a low crouch, braces the elbows on the knees and lifts a phone in both hands up in front of the face, holding dead still before tapping the screen with a thumb",
    term: "crouches to photograph an animal" },
  { id: "tug-the-toy", label: "Tug the Toy", category: "animals-pets", description: "Both fists on a rope toy, leaning back and pulling",
    promptHint: "the subject grips a rope toy in both fists, leans the torso back against the pull and swings the toy side to side in short jerks before stepping in to let the tension go slack",
    term: "tugs back and forth on a rope toy" },
  { id: "wipe-muddy-paws", label: "Wipe Muddy Paws", category: "animals-pets", description: "Kneels and towels one paw at a time",
    promptHint: "the subject kneels on one knee, lifts a dog's paw into a cupped hand, wraps a towel around it and rubs it clean, sets it back down and reaches for the next one",
    term: "wipes a dog's muddy paws" },
  { id: "brace-for-jump", label: "Brace for Jump", category: "animals-pets", description: "Plants the back foot to absorb a dog jumping up",
    promptHint: "the subject plants the back foot and drops the pelvis to take a dog's weight against the chest, both hands rising to catch its shoulders, the torso rocking back then steadying",
    term: "braces as a dog jumps up" },
]
