import type { CharacterMotion } from "./types.js"

/** Athletic & Stunts — 71 entries. Category id `athletic-stunts`. */
export const ATHLETIC_STUNTS_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "vertical-jump", label: "Vertical Jump", category: "athletic-stunts", description: "Crouch, drive straight up, land soft on bent knees",
    promptHint: "the subject sinks into a quarter squat with arms swung back, drives straight up off both feet with arms reaching overhead, then lands softly on bent knees",
    term: "jump straight up and land" },
  { id: "leap-across-gap", label: "Leap Across Gap", category: "athletic-stunts", description: "Running takeoff, legs split in flight, far-side landing",
    promptHint: "the subject takes running strides toward an edge, plants one foot at the lip and drives off it, sails forward with legs split and arms reaching, then lands on the far side and absorbs on bent knees",
    term: "leap across a gap" },
  { id: "box-jump", label: "Box Jump", category: "athletic-stunts", description: "Two-foot jump up onto a box, stand tall on top",
    promptHint: "the subject faces a box, dips into a half squat with arms back, jumps from both feet swinging the arms forward, lands flat-footed on top with soft knees, then stands tall",
    term: "jump up onto a box" },
  { id: "precision-jump", label: "Precision Jump", category: "athletic-stunts", description: "Standing jump landing balanced on a narrow rail",
    promptHint: "the subject stands with toes at an edge, swings both arms back and jumps from both feet, draws the knees up in flight, then lands on the balls of the feet on a narrow rail and holds balance",
    term: "precision-jump onto a narrow rail" },
  { id: "backflip", label: "Backflip", category: "athletic-stunts", description: "Standing backward flip, tucked, landed on both feet",
    promptHint: "the subject swings the arms up and jumps straight off both feet, tucks the knees to the chest while rotating backward through a full flip, then opens up and lands on both feet",
    term: "backflip from standing" },
  { id: "front-flip", label: "Front Flip", category: "athletic-stunts", description: "Two-step punch into a forward flip, landed",
    promptHint: "the subject takes two steps, punches off both feet, tucks the chin and knees while rotating forward through a full flip, then extends and lands on both feet with knees bent",
    term: "front-flip from a two-step run" },
  { id: "cartwheel", label: "Cartwheel", category: "athletic-stunts", description: "Hand-hand-foot-foot sideways wheel",
    promptHint: "the subject lunges sideways, plants one hand then the other on the ground with arms locked, swings the legs over the top in a straight line like a wheel, and lands one foot then the other",
    term: "cartwheel sideways" },
  { id: "round-off", label: "Round-off", category: "athletic-stunts", description: "Cartwheel that snaps both feet down, facing back",
    promptHint: "the subject takes a hurdle step into a cartwheel, plants both hands, snaps the legs together at the top of the rotation, and punches both feet down together to land facing back the way they came",
    term: "hurdle into a round-off and snap down" },
  { id: "vault-over-obstacle", label: "Vault Over Obstacle", category: "athletic-stunts", description: "Parkour speed vault, one hand on top, legs swung over",
    promptHint: "the subject runs at a waist-high obstacle, plants one hand on top and swings both legs over to the side of the planted arm, clears the top, then lands on the far side and keeps running",
    term: "vault over an obstacle" },
  { id: "wall-run", label: "Wall Run", category: "athletic-stunts", description: "Two or three driving steps up a wall, then push off",
    promptHint: "the subject sprints at a wall at an angle, plants one foot high on the surface and drives up it for two or three steps leaning into the wall, then pushes off and drops back down",
    term: "run up a wall and push off" },
  { id: "baseball-slide", label: "Baseball Slide", category: "athletic-stunts", description: "Sprint, drop onto a hip, feet-first slide to the base",
    promptHint: "the subject sprints toward a base, drops onto one hip with the lead leg extended and the other knee bent under it, slides feet first with the arms raised, and stops with the lead foot against the base",
    term: "slide feet-first into a base" },
  { id: "dive-roll", label: "Dive Roll", category: "athletic-stunts", description: "Dive over a low obstacle into a roll, come up running",
    promptHint: "the subject runs at a low obstacle, dives headlong over it with arms stretched forward, tucks the chin and takes the landing on the hands and upper back, rolls forward along the spine, and comes up onto the feet running",
    term: "dive over an obstacle into a roll" },
  { id: "superhero-landing", label: "Superhero Landing", category: "athletic-stunts", description: "Drop into a knee-and-fist three-point crouch, then rise",
    promptHint: "the subject drops from height and lands in a deep crouch with one knee and one fist striking the ground, the other arm flung out to the side and head down, then lifts the head and rises to standing",
    term: "land in a three-point superhero crouch" },
  { id: "sprint-start", label: "Sprint Start", category: "athletic-stunts", description: "Set in the blocks, drive out low, open into full stride",
    promptHint: "the subject crouches in starting blocks with fingertips on the line, raises the pelvis into the set position, then drives forward off the front foot in a low lean and accelerates into full stride",
    term: "drive out of the starting blocks" },
  { id: "skid-to-stop", label: "Skid to a Stop", category: "athletic-stunts", description: "Full run braked into a heel-skid dead stop",
    promptHint: "the subject arrives at a full run, plants the feet wide and drops the pelvis while leaning back, skids forward with heels braking and arms out for balance, then settles to a dead stop upright",
    term: "skid to a stop" },
  { id: "hurdle-jump", label: "Hurdle Jump", category: "athletic-stunts", description: "Clear a hurdle mid-sprint, lead leg over, trail leg flat",
    promptHint: "the subject sprints toward a hurdle, drives the lead knee up and extends that leg over the bar while the trail leg folds flat out to the side, snaps the lead foot down, and continues sprinting",
    term: "hurdle a barrier mid-sprint" },
  { id: "lean-across-finish-line", label: "Lean Across Finish Line", category: "athletic-stunts", description: "Final strides, chest thrown forward through the tape",
    promptHint: "the subject sprints the final strides toward a finish line, throws the chest forward and drops the head with the arms swept back behind the body to break the tape, then straightens up and slows to a jog",
    term: "lean across the finish line" },
  { id: "run-celebrating-arms-out", label: "Run Celebrating Arms Out", category: "athletic-stunts", description: "Goal celebration run, arms spread wide, head back",
    promptHint: "the subject breaks into a run with both arms spread wide like wings, head tilted back and mouth open in a shout, then slides to a stop on the knees with the arms still outstretched",
    term: "run celebrating with arms spread wide" },
  { id: "soccer-dribble", label: "Soccer Dribble", category: "athletic-stunts", description: "Close-control dribble, feints, and a cut inside",
    promptHint: "the subject jogs forward tapping a soccer ball ahead with the inside of alternating feet, drops the shoulder in a feint one way, then cuts the ball the other way with the outside of the foot and accelerates after it",
    term: "dribble a soccer ball with a feint" },
  { id: "kick-ball", label: "Kick a Ball", category: "athletic-stunts", description: "Plant, swing through, strike with the instep, follow through",
    promptHint: "the subject takes two approach steps to a ball on the ground, plants the support foot beside it, swings the kicking leg through with the pelvis rotating, strikes with the instep, and follows through with the leg rising",
    term: "kick a ball with the instep" },
  { id: "header", label: "Header", category: "athletic-stunts", description: "Jump, arch back, snap the forehead through the ball",
    promptHint: "the subject tracks a ball in the air, jumps off one foot with the arms driving up, arches the back and pulls the head behind the shoulders, then snaps the torso forward to strike the ball with the forehead",
    term: "head the ball with the forehead" },
  { id: "bicycle-kick", label: "Bicycle Kick", category: "athletic-stunts", description: "Airborne overhead scissor kick, landing on the back",
    promptHint: "the subject faces away from the goal, leaps backward off one leg and swings the other leg up, then scissors the takeoff leg up and over it to strike the ball overhead, and lands on the back and shoulders",
    term: "bicycle-kick the ball overhead" },
  { id: "goalkeeper-dive-save", label: "Goalkeeper Dive Save", category: "athletic-stunts", description: "Set stance, explode sideways, full-length dive, ball held",
    promptHint: "the subject sets in a ready crouch with hands out, pushes off the near foot into a full-length sideways dive, stretches both arms to catch the ball in both hands, and lands on the side clutching it to the chest",
    term: "dive full-length for a save" },
  { id: "throw-ball", label: "Throw a Ball", category: "athletic-stunts", description: "Overhand throw with stride, hip turn, and follow-through",
    promptHint: "the subject steps back with the ball cocked behind the head, strides onto the front foot, rotates the pelvis and shoulders, whips the arm through and releases the ball, and follows through across the body",
    term: "throw a ball overhand" },
  { id: "catch-ball", label: "Catch a Ball", category: "athletic-stunts", description: "Track, reach with both hands, absorb into the chest",
    promptHint: "the subject tracks an incoming ball with the eyes, steps toward it with both hands raised and fingers spread, absorbs the ball by pulling the hands to the chest, then holds it secure",
    term: "catch a ball two-handed" },
  { id: "baseball-pitch", label: "Baseball Pitch", category: "athletic-stunts", description: "Wind-up, high leg kick, stride, whip the arm through",
    promptHint: "the subject stands side-on with the ball in the glove, lifts the front knee high in a wind-up, strides toward the plate, whips the throwing arm over the top to release, and follows through with the back leg swinging around",
    term: "wind up and pitch a baseball" },
  { id: "swing-bat", label: "Swing a Bat", category: "athletic-stunts", description: "Side-on stride, hip rotation, bat through the zone",
    promptHint: "the subject stands side-on with the bat cocked over the back shoulder, strides onto the front foot, rotates the pelvis then the shoulders, whips the bat through the strike zone, and follows through over the shoulder",
    term: "swing a baseball bat" },
  { id: "golf-swing", label: "Golf Swing", category: "athletic-stunts", description: "Backswing over the shoulder, unwind, high finish",
    promptHint: "the subject addresses the ball in a bent-over stance, draws the club back in a wide arc over the shoulder, unwinds the pelvis and swings down through the ball, and finishes with the chest facing the target, club high",
    term: "swing a golf club through the ball" },
  { id: "tennis-serve", label: "Tennis Serve", category: "athletic-stunts", description: "Toss, knee bend, spring up, snap the racket over",
    promptHint: "the subject tosses the ball up with the front arm while drawing the racket back, bends the knees, springs upward, snaps the racket over the top of the ball, and lands forward on the front foot",
    term: "serve a tennis ball" },
  { id: "tennis-forehand", label: "Tennis Forehand", category: "athletic-stunts", description: "Split step, racket back, swing low to high, follow through",
    promptHint: "the subject split-steps and turns the shoulders sideways with the racket drawn back, steps into the ball with the front foot, swings the racket low to high through contact, and follows through with the racket finishing over the opposite shoulder",
    term: "hit a tennis forehand" },
  { id: "volleyball-spike", label: "Volleyball Spike", category: "athletic-stunts", description: "Three-step approach, two-foot jump, arm swing over the net",
    promptHint: "the subject takes a three-step approach to the net with arms swinging back, jumps off both feet with both arms driving up, draws the hitting elbow back high, and snaps the open hand down over the ball at the peak",
    term: "spike a volleyball over the net" },
  { id: "basketball-dribble", label: "Basketball Dribble", category: "athletic-stunts", description: "Low dribble with a crossover while stepping sideways",
    promptHint: "the subject crouches low with knees bent, bounces a basketball with one hand at hip height, crosses it over to the other hand in front of the body, and keeps dribbling while stepping sideways",
    term: "dribble a basketball with a crossover" },
  { id: "layup", label: "Layup", category: "athletic-stunts", description: "Two-step drive and one-hand lay off the backboard",
    promptHint: "the subject dribbles toward the basket, gathers the ball in both hands, takes two long steps, drives up off the inside foot with the opposite knee lifting, and lays the ball off the backboard with one hand",
    term: "drive in for a layup" },
  { id: "slam-dunk", label: "Slam Dunk", category: "athletic-stunts", description: "Two-foot rise and slam through the hoop, hang, drop",
    promptHint: "the subject drives toward the rim with the ball, jumps off both feet, rises with the ball raised above the head, slams it down through the hoop, and hangs on the rim before dropping to the floor",
    term: "slam dunk the ball" },
  { id: "free-throw", label: "Free Throw", category: "athletic-stunts", description: "Set at the line, dip, extend, wrist-flick release",
    promptHint: "the subject stands at the line holding the ball at the waist, bends the knees, raises the ball to the forehead with the elbow under it, extends the legs and arm together, and flicks the wrist to release",
    term: "shoot a free throw" },
  { id: "shadowbox", label: "Shadowbox", category: "athletic-stunts", description: "Bounce on the toes, throw combos at the air, slip and weave",
    promptHint: "the subject bounces on the balls of the feet in a boxing guard, throws a jab-cross-hook combination at the air with the pelvis turning into each punch, slips the head to one side, and resets with a short shuffle step",
    term: "shadowbox with combos and slips" },
  { id: "punch-heavy-bag", label: "Punch Heavy Bag", category: "athletic-stunts", description: "Guard up, jab-cross into the bag, hook, step around",
    promptHint: "the subject squares up to a heavy bag in a boxing guard, fires a jab and a cross into it with the rear hip turning through, digs a hook into its side as it swings back, and resets",
    term: "punch a heavy bag" },
  { id: "push-up", label: "Push-up", category: "athletic-stunts", description: "Plank, chest to the floor, press back to lockout",
    promptHint: "the subject starts in a straight-arm plank with hands under the shoulders, lowers the chest toward the floor by bending the elbows while keeping the body rigid, then presses back up to full extension",
    term: "lower into a push-up and press back up" },
  { id: "plank", label: "Plank", category: "athletic-stunts", description: "Drop to the forearms, body rigid, hold, then rest",
    promptHint: "the subject drops from kneeling onto the forearms with elbows under the shoulders, extends both legs back onto the toes so the body forms one rigid line, holds the position with the pelvis level, then lowers the knees to rest",
    term: "drop into a plank and hold" },
  { id: "sit-up-crunch", label: "Sit-up", category: "athletic-stunts", description: "Lie back, curl the torso up to the knees, lower down",
    promptHint: "the subject lies on the back with knees bent and feet flat, hands behind the head, curls the torso up until the chest nears the knees, then lowers back down one vertebra at a time and repeats",
    term: "do sit-ups" },
  { id: "bodyweight-squat", label: "Bodyweight Squat", category: "athletic-stunts", description: "Hips back and down to parallel, drive through the heels",
    promptHint: "the subject stands with feet shoulder-width apart and arms out front, sits the pelvis back and down until the thighs are parallel to the floor with the chest up, then drives through the heels to stand",
    term: "squat down and drive back up" },
  { id: "lunge", label: "Forward Lunge", category: "athletic-stunts", description: "Long step forward, both knees to ninety, push back up",
    promptHint: "the subject steps one foot far forward and lowers straight down until both knees bend to ninety degrees with the back knee just off the floor, then pushes off the front heel to step back to standing and switches legs",
    term: "step into a forward lunge" },
  { id: "deadlift", label: "Deadlift", category: "athletic-stunts", description: "Hinge, grip the bar, pull to lockout, lower it down",
    promptHint: "the subject stands over a loaded barbell, hinges at the waist to grip the bar with a flat back, drives through the legs to pull the bar up the shins to hip lockout, then lowers it to the floor",
    term: "deadlift a barbell" },
  { id: "bench-press", label: "Bench Press", category: "athletic-stunts", description: "Unrack, lower the bar to the chest, press to lockout",
    promptHint: "the subject lies on a flat bench, unracks a barbell with straight arms above the chest, lowers it under control until it touches the chest, then presses it back up to lockout and racks it",
    term: "bench-press a barbell" },
  { id: "dumbbell-curl", label: "Dumbbell Curl", category: "athletic-stunts", description: "Elbows pinned, curl to the shoulders, lower slow",
    promptHint: "the subject stands holding a dumbbell in each hand with arms hanging straight, curls both weights up to the shoulders by bending the elbows while keeping them pinned at the sides, then lowers them back down under control",
    term: "curl a pair of dumbbells" },
  { id: "burpee", label: "Burpee", category: "athletic-stunts", description: "Drop, kick back to plank, snap in, jump up",
    promptHint: "the subject drops from standing into a crouch with hands on the floor, kicks both feet back into a plank, snaps the feet back in under the body, and jumps straight up with arms overhead",
    term: "drop into a burpee and jump" },
  { id: "jumping-jacks", label: "Jumping Jacks", category: "athletic-stunts", description: "Feet apart and arms overhead, back together, repeat",
    promptHint: "the subject stands with feet together and arms at the sides, hops the feet apart while swinging the arms overhead until the hands nearly meet, hops back to the start, and repeats in a continuous rhythm",
    term: "do jumping jacks" },
  { id: "jump-rope", label: "Jump Rope", category: "athletic-stunts", description: "Wrist-driven rope swing, hops on the balls of the feet",
    promptHint: "the subject holds a jump rope handle in each hand, swings the rope overhead with the wrists, and hops over it on the balls of the feet in a continuous rhythm with elbows tucked at the sides",
    term: "jump rope on the spot" },
  { id: "sun-salutation", label: "Sun Salutation", category: "athletic-stunts", description: "Full yoga flow from standing through the floor and back",
    promptHint: "the subject stands with palms together, sweeps the arms overhead, folds forward over the legs, steps back into a plank and lowers down, arches into upward dog, pushes back into downward dog, then steps forward and rises to standing",
    term: "flow through a sun salutation" },
  { id: "tai-chi-flow", label: "Tai Chi Flow", category: "athletic-stunts", description: "Weight shifts and circling arms in one continuous flow",
    promptHint: "the subject shifts the weight onto one soft-kneed leg as both arms rise and circle before the chest, steps the other foot out and turns the waist to sweep the arms across, then sinks back as the arms lower",
    term: "flow through tai chi" },
  { id: "hamstring-stretch", label: "Hamstring Stretch", category: "athletic-stunts", description: "Heel propped up, flat-back reach to the toes, switch legs",
    promptHint: "the subject props one heel on a raised surface with the leg straight, hinges forward at the waist with a flat back and reaches both hands toward the toes, holds the stretch, then rises and switches legs",
    term: "stretch the hamstring on a raised heel" },
  { id: "freestyle-swim", label: "Freestyle Swim", category: "athletic-stunts", description: "Alternating overhead strokes, flutter kick, side breath",
    promptHint: "the subject swims freestyle with the body long and flat at the surface, arms pulling in alternating overhead strokes as the legs flutter-kick, the head rolling to one side to breathe between strokes",
    term: "swim freestyle" },
  { id: "dive-into-water", label: "Dive Into Water", category: "athletic-stunts", description: "Spring from the edge into a head-first arc",
    promptHint: "the subject stands at the edge with toes curled over it, bends the knees and swings the arms forward, springs outward in an arc with the arms extended together past the ears, and enters the water head first",
    term: "dive head-first into water" },
  { id: "cannonball-into-water", label: "Cannonball", category: "athletic-stunts", description: "Run, jump, hug the knees, splash down seat-first",
    promptHint: "the subject runs to the edge and jumps out over the water, pulls both knees to the chest and wraps the arms around the shins in a tight ball, then drops seat first into the water with a big splash",
    term: "cannonball into the water" },
  { id: "surface-and-flick-hair", label: "Surface & Flick Hair", category: "athletic-stunts", description: "Break the surface, whip the head back, hair throws an arc",
    promptHint: "the subject rises up through the water and breaks the surface face first, whips the head back so the wet hair throws an arc of spray behind it, then wipes the water from the eyes with both hands",
    term: "surface and flick the hair back" },
  { id: "pour-water-over-head", label: "Pour Water Over Head", category: "athletic-stunts", description: "Bottle raised, water cascades over the head, shake it off",
    promptHint: "the subject raises a water bottle above the head, tips it so the water cascades over the hair and face and runs down the neck, then drops the bottle and shakes the head to throw off the drops",
    term: "pour water over the head" },
  { id: "skateboard-push", label: "Skateboard Push", category: "athletic-stunts", description: "Two pushes off the ground, back foot to the tail, roll",
    promptHint: "the subject stands on a skateboard with the front foot over the front bolts, pushes off the ground with the back foot in two long strokes, then sets the back foot on the tail and rolls in a bent-knee stance",
    term: "push off on a skateboard" },
  { id: "surf-pop-up", label: "Surf Pop-up", category: "athletic-stunts", description: "Paddle prone, press up, feet under, riding stance",
    promptHint: "the subject lies prone on a surfboard paddling with alternating arms, plants both hands under the chest, pushes up and swings the feet under the body in one motion, and rises into a crouched side-on riding stance",
    term: "pop up on a surfboard" },
  { id: "ski-carve-turn", label: "Ski Carve Turn", category: "athletic-stunts", description: "Roll the edges into a carved turn, then the next",
    promptHint: "the subject skis downhill with knees bent and poles trailing, rolls both knees and edges into the slope to carve a turn with the upper body facing down the hill, then rolls the edges over into the next turn",
    term: "carve a ski turn" },
  { id: "rope-climb", label: "Rope Climb", category: "athletic-stunts", description: "Foot clamp, arm pull, re-clamp higher, repeat upward",
    promptHint: "the subject grips a hanging rope overhead, clamps it between the feet, pulls with the arms while pushing up through the legs, re-clamps the feet higher, and repeats the reach and pull to climb upward",
    term: "climb a hanging rope" },
  { id: "rope-swing-across", label: "Rope Swing Across", category: "athletic-stunts", description: "Run, swing across a gap on a rope, release and land",
    promptHint: "the subject grabs a hanging rope with both hands, runs and lifts the feet to swing in a long arc across a gap, releases at the far end of the swing, and lands on both feet",
    term: "swing across a gap on a rope" },
  { id: "pull-up", label: "Pull-up", category: "athletic-stunts", description: "Dead hang, chin over the bar, lower under control",
    promptHint: "the subject hangs from a bar with straight arms and an overhand grip, pulls the body up by driving the elbows down until the chin clears the bar, then lowers under control to a dead hang",
    term: "pull up until the chin clears the bar" },
  { id: "climb-wall", label: "Climb a Wall", category: "athletic-stunts", description: "Jump to the top edge, walk the feet up, mantle over",
    promptHint: "the subject runs at a high wall, jumps and catches the top edge with both hands, walks the feet up the face, pulls the chest over the edge and hooks one leg, then mantles up onto the top",
    term: "climb a wall and mantle over" },
  { id: "climb-ladder", label: "Climb a Ladder", category: "athletic-stunts", description: "Hand over hand up the rungs, step off at the top",
    promptHint: "the subject grips a ladder at chest height, steps onto the bottom rung and climbs hand over hand with the opposite foot following each hand, then reaches the top and steps off onto the ledge",
    term: "climb a ladder" },
  { id: "drop-and-roll", label: "Drop and Roll", category: "athletic-stunts", description: "Drop from a ledge, soft landing into a shoulder roll",
    promptHint: "the subject drops from a ledge, lands on the balls of the feet with knees bending deep, immediately tips forward into a shoulder roll to bleed off the impact, and comes up running",
    term: "drop from a ledge into a roll" },
  { id: "balance-on-beam", label: "Balance on a Beam", category: "athletic-stunts", description: "Heel-to-toe along a narrow beam, arms out, step down",
    promptHint: "the subject steps onto a narrow beam and walks heel to toe along it with arms extended out to the sides, wobbling and correcting with the arms, then reaches the end and steps down",
    term: "walk along a balance beam" },
  { id: "handstand", label: "Handstand", category: "athletic-stunts", description: "Lunge, kick up to vertical, hold, step down",
    promptHint: "the subject steps forward into a lunge, plants both hands on the ground shoulder-width apart, kicks the legs up overhead one after the other into a straight vertical line, holds the balance, then lowers one leg and steps down",
    term: "kick up into a handstand" },
  { id: "kip-up", label: "Kip-up", category: "athletic-stunts", description: "From flat on the back, snap the pelvis and spring up",
    promptHint: "the subject lies flat on the back, rocks the legs up and over the head, then snaps the pelvis forward and pushes off the hands to spring up onto both feet in one motion",
    term: "kip up from lying on the back" },
  { id: "jump-in-puddle", label: "Jump in a Puddle", category: "athletic-stunts", description: "Run up, two-foot stomp into a puddle, splash, hop out",
    promptHint: "the subject runs up to a puddle, jumps and stomps down into it with both feet together and arms flung up as the water splashes out around the legs, then hops out laughing",
    term: "jump into a puddle with both feet" },
  { id: "bounce-on-bed", label: "Bounce on a Bed", category: "athletic-stunts", description: "Climb onto a bed, bounce higher and higher, flop down",
    promptHint: "the subject climbs onto a bed, starts bouncing on both feet with the knees soft and arms pumping, springs higher with each bounce, then drops onto the back and lets the mattress catch the fall",
    term: "bounce on a bed and flop down" },
  { id: "swing-on-swing", label: "Swing on a Swing", category: "athletic-stunts", description: "Pump the legs on a swing, higher each pass, lean back",
    promptHint: "the subject sits on a swing gripping the chains, pumps the legs forward and tucks them back to build height with each pass, and leans back with the arms straight at the top of the forward swing",
    term: "swing on a playground swing" },
]
