import type { CharacterMotion } from "./types.js"

/** Camera Interaction — 44 entries. Category id `camera-interaction`. */
export const CAMERA_INTERACTION_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "look-into-lens", label: "Look Into Lens", category: "camera-interaction", description: "Eyes find the lens and lock on the viewer",
    promptHint: "the subject lifts their gaze from off-frame and locks eyes straight into the lens, head squaring toward the camera, holding the look steady on the viewer",
    term: "looks straight into the lens" },
  { id: "hold-then-look-away", label: "Hold Gaze Then Look Away", category: "camera-interaction", description: "Direct eye contact, then the gaze breaks aside",
    promptHint: "the subject holds direct eye contact with the lens, then lets the gaze drop and the head turn aside, breaking the connection with the viewer",
    term: "holds eye contact then looks away" },
  { id: "approach-camera", label: "Approach Camera", category: "camera-interaction", description: "Walks straight up to the lens",
    promptHint: "the subject walks straight toward the lens from mid-distance, each stride bringing the face larger in frame, stopping close with the eyes fixed on the viewer",
    term: "walks straight up to the lens" },
  { id: "lean-into-lens", label: "Lean Into Lens", category: "camera-interaction", description: "Leans in until the face fills the frame",
    promptHint: "the subject leans in toward the lens from the waist, the face closing the distance until it fills the frame, eyes fixed on the viewer, then settles there",
    term: "leans in close to the lens" },
  { id: "walk-past-camera", label: "Walk Past Camera", category: "camera-interaction", description: "Passes close by the lens and exits behind it",
    promptHint: "the subject walks toward the lens and passes close on one side, the body sweeping across the frame and exiting behind the camera position without looking back",
    term: "walks past the camera and out of frame" },
  { id: "point-at-camera", label: "Point at Camera", category: "camera-interaction", description: "Arm swings up and locks out pointing at the viewer",
    promptHint: "the subject swings one arm up from the side and locks it out straight at the lens with the index finger extended, eyes fixing on the viewer as the point lands, then lowers the hand",
    term: "raises an arm to point at the camera" },
  { id: "show-object-to-lens", label: "Show Object to Lens", category: "camera-interaction", description: "Holds an object up close for the viewer to see",
    promptHint: "the subject lifts an object in one hand and brings it up close to the lens, holding it steady beside the face for the viewer to inspect, then draws it back down",
    term: "holds an object up to the lens" },
  { id: "cover-the-lens", label: "Cover the Lens", category: "camera-interaction", description: "Palm presses over the lens, then pulls away",
    promptHint: "the subject reaches a hand toward the lens and presses the palm over it, fingers spreading until the hand fills the frame, then pulls the hand away to reveal the face again",
    term: "covers the lens with a palm" },
  { id: "step-back-from-camera", label: "Step Back", category: "camera-interaction", description: "Backs away from the lens to mid-distance",
    promptHint: "the subject steps backward away from the lens, weight shifting onto the rear foot with each step, the body shrinking in frame until standing at mid-distance",
    term: "steps back from the camera" },
  { id: "talk-to-camera", label: "Talk to Camera", category: "camera-interaction", description: "Vlog-style delivery straight to the viewer",
    promptHint: "the subject speaks directly into the lens like a vlogger, mouth moving with natural conversational hand gestures, eyebrows lifting on emphasis, eye contact held throughout",
    term: "talks to camera vlog-style" },
  { id: "react-off-screen", label: "React Off-Screen", category: "camera-interaction", description: "Reacts to something off-frame, then back to lens",
    promptHint: "the subject turns the head toward something off-screen and reacts with a visible change of expression, then swings the gaze back to the lens to share the reaction with the viewer",
    term: "reacts to something off-frame then back to lens" },
  { id: "wink-at-camera", label: "Wink at Camera", category: "camera-interaction", description: "A deliberate one-eyed wink to the viewer",
    promptHint: "the subject looks into the lens and closes one eye in a deliberate wink, the corner of the mouth lifting on the same side, then opens the eye and holds the look",
    term: "winks at the camera" },
  { id: "beckon-camera-closer", label: "Beckon Closer", category: "camera-interaction", description: "Come-here gesture aimed at the lens",
    promptHint: "the subject looks into the lens and curls the fingers of one raised hand toward the chest in a come-here gesture, repeating the beckon as the head tilts encouragingly",
    term: "beckons the camera closer" },
  { id: "push-camera-away", label: "Push Camera Away", category: "camera-interaction", description: "Open palm shoves the lens back in refusal",
    promptHint: "the subject extends an open palm toward the lens and pushes it away, the arm straightening as the hand grows large in frame, the face turning aside in refusal",
    term: "pushes the camera away with a palm" },
  { id: "wave-at-camera", label: "Wave at Camera", category: "camera-interaction", description: "Open-palm wave and a smile to the viewer",
    promptHint: "the subject raises one hand to shoulder height and waves at the lens, palm open and fingers swinging side to side, a smile breaking as the eyes meet the viewer",
    term: "waves at the camera" },
  { id: "blow-kiss-to-lens", label: "Blow Kiss to Lens", category: "camera-interaction", description: "Kisses the fingertips and sends it to the lens",
    promptHint: "the subject brings the fingertips to the lips, kisses them, and extends the hand toward the lens with a soft exhale, the palm opening to send the kiss to the viewer",
    term: "blows a kiss to the camera" },
  { id: "tap-the-lens", label: "Tap the Lens", category: "camera-interaction", description: "Fingertip taps the glass, then peers in",
    promptHint: "the subject reaches toward the lens and taps it with a fingertip, the finger growing huge in frame on contact, then withdraws the hand and peers in as if checking the camera works",
    term: "taps the lens with a fingertip" },
  { id: "whisper-to-camera", label: "Whisper to Camera", category: "camera-interaction", description: "Leans in, cupped hand, conspiratorial whisper",
    promptHint: "the subject leans in close to the lens, raises a cupped hand beside the mouth, and whispers toward the viewer with a conspiratorial glance to the side, then eases back",
    term: "whispers to camera behind a cupped hand" },
  { id: "grab-the-camera", label: "Grab the Camera", category: "camera-interaction", description: "Lunges to seize the lens and haul it in",
    promptHint: "the subject lunges one hand at the lens as if seizing the camera, fingers wrapping around the edges of the glass, the arm pulling as if to drag it in toward the face",
    term: "grabs at the camera with one hand" },
  { id: "extend-selfie-arm", label: "Extend Selfie Arm", category: "camera-interaction", description: "Arm out as if holding the camera, finds the angle",
    promptHint: "the subject extends one arm straight toward the lens as if holding the camera at arm's length, tilts the head and angles the face to find the flattering side, then settles into the pose",
    term: "extends a selfie arm toward the lens" },
  { id: "break-fourth-wall", label: "Break the Fourth Wall", category: "camera-interaction", description: "A knowing glance to the viewer mid-action",
    promptHint: "the subject continues an action within the scene and flicks the eyes to the lens for a knowing glance at the viewer without turning the head, then returns attention to the scene",
    term: "flicks a knowing glance to the lens mid-action" },
  { id: "nod-at-camera", label: "Nod at Camera", category: "camera-interaction", description: "Single deliberate nod of acknowledgment",
    promptHint: "the subject looks into the lens and gives a single deliberate nod, the chin dipping and lifting, eyes holding the viewer's throughout as an acknowledgment",
    term: "nods at the camera" },
  { id: "shake-head-at-camera", label: "Shake Head at Camera", category: "camera-interaction", description: "Head shakes side to side, eyes on the viewer",
    promptHint: "the subject looks into the lens and shakes the head side to side in a clear no, lips pressed together, the eyes staying on the viewer the whole time",
    term: "shakes head no at the camera" },
  { id: "shush-the-viewer", label: "Shush the Viewer", category: "camera-interaction", description: "Finger to lips, a hush aimed at the lens",
    promptHint: "the subject raises an index finger to the lips and holds it there while looking into the lens, brows lifting in a hush, then lowers the finger and keeps the gaze",
    term: "shushes the viewer with a finger to lips" },
  { id: "double-take-to-camera", label: "Double Take to Camera", category: "camera-interaction", description: "Glances past, looks away, then snaps back to lens",
    promptHint: "the subject glances past the lens, looks away, then snaps the head back to stare straight into the camera in a comic double take, the eyes widening",
    term: "does a comic double take to camera" },
  { id: "thumbs-up-to-camera", label: "Thumbs Up to Camera", category: "camera-interaction", description: "Pops a thumbs up at the lens with a grin",
    promptHint: "the subject raises one fist to chest height and pops the thumb up toward the lens, holding it with a grin at the viewer, then lowers the hand",
    term: "gives a thumbs up to the camera" },
  { id: "reach-toward-lens", label: "Reach for the Lens", category: "camera-interaction", description: "Open hand reaches out as if to touch the viewer",
    promptHint: "the subject extends an open hand toward the lens, fingers spreading as the hand grows to fill the frame, the arm reaching as if to touch the viewer, then draws back",
    term: "reaches out toward the lens" },
  { id: "look-back-over-shoulder", label: "Look Back at Lens", category: "camera-interaction", description: "Walks away, then glances back over the shoulder",
    promptHint: "the subject walks away from the lens, then pauses and turns the head back over one shoulder to look straight into the camera, holding the glance before continuing on",
    term: "looks back over the shoulder at the lens" },
  { id: "notice-the-camera", label: "Notice the Camera", category: "camera-interaction", description: "Caught-on-camera moment, realizes being filmed",
    promptHint: "the subject carries on with the scene's action, then catches sight of the lens with a small start, the eyes widening and the body straightening on realizing they are being filmed",
    term: "notices the camera mid-scene" },
  { id: "stare-down-the-lens", label: "Stare Down the Lens", category: "camera-interaction", description: "Chin lowers, hard unblinking stare at the viewer",
    promptHint: "the subject lowers the chin and stares hard into the lens, the eyes narrowing and unblinking, shoulders squaring as the intimidating look is held on the viewer",
    term: "stares hard down the lens" },
  { id: "bow-to-camera", label: "Bow to Camera", category: "camera-interaction", description: "Formal bow from the waist toward the lens",
    promptHint: "the subject faces the lens, folds forward from the waist in a formal bow with the hands at the sides, holds at the bottom, then straightens up with the eyes returning to the viewer",
    term: "bows to the camera" },
  { id: "shield-face-from-camera", label: "Shield Face", category: "camera-interaction", description: "Camera-shy, forearm blocks the face and turns away",
    promptHint: "the subject raises a forearm to block the face from the lens, turning the head away and hunching one shoulder, then lowers the arm a little and peeks out over it at the viewer",
    term: "shields the face from the camera" },
  { id: "smolder-at-camera", label: "Smolder at Camera", category: "camera-interaction", description: "Looks up through the lashes with a sensual half-smile",
    promptHint: "the subject tilts the chin down and looks up into the lens through lowered lashes, lips parting, a sensual half-smile forming as the gaze holds the viewer",
    term: "smolders into the lens", adultOnly: true },
  { id: "sing-to-camera", label: "Sing to Camera", category: "camera-interaction", description: "Lip-synced singing straight to the viewer",
    promptHint: "the subject sings straight into the lens, the lips shaping each lyric in sync, the head rocking to the beat and the brows lifting on the big notes, eyes on the viewer throughout",
    term: "lip-syncs a song to camera" },
  { id: "point-up-at-caption", label: "Point Up at Caption", category: "camera-interaction", description: "Points above the head at an on-screen caption",
    promptHint: "the subject looks into the lens, raises one arm and points the index finger straight up above the head at the space where a caption sits, holds the point, then lowers the arm",
    term: "points up above the head at a caption" },
  { id: "punch-at-camera", label: "Punch at Camera", category: "camera-interaction", description: "Fist drives straight at the lens and fills the frame",
    promptHint: "the subject sets the feet, draws one fist back to the shoulder and drives it straight at the lens, the knuckles growing to fill the frame, then pulls the fist back to guard",
    term: "throws a punch straight at the lens" },
  { id: "lunge-at-camera", label: "Lunge at Camera", category: "camera-interaction", description: "Whole body springs at the lens, face rushing in",
    promptHint: "the subject drops into a crouch, then springs forward at the lens with the whole body, arms flung wide and the face rushing to fill the frame, then checks the momentum just short of it",
    term: "lunges at the lens" },
  { id: "toss-object-to-camera", label: "Toss Object to Camera", category: "camera-interaction", description: "Flips an object underhand toward the lens",
    promptHint: "the subject holds an object at chest height, then flips it underhand toward the lens, the arm following through as the object arcs up and grows large in frame, the eyes tracking it to the viewer",
    term: "tosses an object at the lens" },
  { id: "kiss-the-lens", label: "Kiss the Lens", category: "camera-interaction", description: "Leans in and plants a playful kiss on the glass",
    promptHint: "the subject leans in until the face fills the frame, puckers the lips and presses a playful kiss onto the lens, the eyes closing on contact, then eases back with a grin",
    term: "kisses the lens" },
  { id: "mouth-silent-words", label: "Mouth Silent Words", category: "camera-interaction", description: "Mouths a phrase to the viewer without a sound",
    promptHint: "the subject looks into the lens and mouths a short phrase without sound, the lips shaping each word deliberately as the eyes hold the viewer, then closes the mouth and keeps the look",
    term: "mouths silent words to camera" },
  { id: "reach-to-tap-record", label: "Reach to Tap Record", category: "camera-interaction", description: "Reaches to hit record, then settles back into frame",
    promptHint: "the subject reaches one hand straight toward the lens as if to tap the record button just below it, the hand filling the frame, then withdraws it and settles back into place facing the viewer",
    term: "reaches to tap record then settles back" },
  { id: "prop-phone-on-surface", label: "Prop Phone on Surface", category: "camera-interaction", description: "Leans in to prop the phone up, then lets go",
    promptHint: "the subject cradles the phone in both hands and leans down close to prop it against a surface, the fingers adjusting it until it sits steady, then lets go and straightens up into frame",
    term: "props the phone on a surface" },
  { id: "turn-wrist-to-show-watch", label: "Show the Watch", category: "camera-interaction", description: "Wrist rotates to present the watch face to the lens",
    promptHint: "the subject raises one forearm toward the lens and rotates the wrist so the watch face turns square to the viewer, holding it steady close to the lens, then lowers the arm",
    term: "turns the wrist to show the watch" },
  { id: "splash-water-at-lens", label: "Splash Water at Lens", category: "camera-interaction", description: "Scoops and flings water at the viewer with a laugh",
    promptHint: "the subject scoops water with both hands and flings it at the lens, the arms sweeping up and forward as the spray flies toward the viewer, then shakes out the wet hands with a laugh",
    term: "splashes water at the lens" },
]
