import type { CharacterMotion } from "./types.js"

/** Combat & Weapons — 67 entries. Category id `combat-weapons`. */
export const COMBAT_WEAPONS_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "draw-pistol-from-holster", label: "Draw Pistol", category: "combat-weapons", description: "Hand drops to the holster and clears the pistol",
    promptHint: "the subject drops the dominant hand to the hip holster, grips the pistol and pulls it clear, the muzzle sweeping up level as the support hand joins the grip",
    term: "draws pistol from the holster" },
  { id: "raise-and-aim-pistol", label: "Raise & Aim Pistol", category: "combat-weapons", description: "Pistol comes up from low ready to eye level",
    promptHint: "the subject lifts the pistol from a low ready position, both arms extending forward until the sights sit at eye level, shoulders squared and feet planted",
    term: "raises pistol to aim" },
  { id: "fire-pistol", label: "Fire Pistol", category: "combat-weapons", description: "Trigger squeeze, recoil kick, muzzle settles back",
    promptHint: "the subject squeezes the trigger with both arms extended, the pistol kicking upward in recoil and the wrists absorbing the jolt, then settles the muzzle back on target",
    term: "fires the pistol" },
  { id: "fire-rifle-from-shoulder", label: "Fire Rifle", category: "combat-weapons", description: "Rifle shouldered, shoulder rocks with each recoil",
    promptHint: "the subject shoulders the rifle stock with the cheek pressed down onto it and fires, the shoulder rocking back with each recoil pulse while the feet stay planted",
    term: "fires rifle from the shoulder" },
  { id: "aim-down-sights", label: "Aim Down Sights", category: "combat-weapons", description: "Rifle rises to the shoulder, cheek on stock, holds",
    promptHint: "the subject raises the rifle from low ready to the shoulder, drops the cheek onto the stock and closes one eye, holding still on target with both elbows tucked in",
    term: "aims down the sights" },
  { id: "reload-magazine", label: "Reload Magazine", category: "combat-weapons", description: "Drops the empty mag, seats a fresh one, weapon back up",
    promptHint: "the subject drops the empty magazine with a thumb press, pulls a fresh magazine from the belt, seats it with a palm slap and brings the weapon back up to ready",
    term: "reloads a fresh magazine" },
  { id: "rack-the-slide", label: "Rack the Slide", category: "combat-weapons", description: "Support hand pulls the pistol slide back and lets go",
    promptHint: "the subject grips the top of the pistol with the support hand, pulls the slide back toward the chest and releases it so it snaps forward, then re-grips ready to fire",
    term: "racks the pistol slide" },
  { id: "pump-shotgun", label: "Pump Shotgun", category: "combat-weapons", description: "Fore-end pulled back and shoved forward in one pump",
    promptHint: "the subject pulls the shotgun fore-end back toward the body and shoves it forward again in one pump, then settles the stock back into the shoulder",
    term: "pumps the shotgun" },
  { id: "holster-pistol", label: "Holster Pistol", category: "combat-weapons", description: "Pistol lowers from aim and slides into the holster",
    promptHint: "the subject lowers the pistol from aim, turns the muzzle toward the ground and guides it into the hip holster with a downward push, then lets the hand come away",
    term: "holsters the pistol" },
  { id: "advance-with-rifle-up", label: "Tactical Advance", category: "combat-weapons", description: "Crouched forward walk with the rifle up",
    promptHint: "the subject moves forward in a crouched walk with the rifle raised at the shoulder, muzzle tracking ahead, knees bent and heel-to-toe steps keeping the upper body level",
    term: "advances with rifle up" },
  { id: "run-and-gun", label: "Run & Gun", category: "combat-weapons", description: "Fires the pistol on the move at a run",
    promptHint: "the subject runs forward with the pistol raised in both hands and fires on the move, the upper body staying level over the pumping legs while the muzzle holds on target",
    term: "fires while running forward" },
  { id: "take-cover", label: "Take Cover", category: "combat-weapons", description: "Drops low behind an object, weapon to the chest",
    promptHint: "the subject drops low and moves sideways behind a solid object, back pressing against it, weapon pulled tight to the chest and head ducked below the edge",
    term: "takes cover with the weapon tucked in" },
  { id: "pop-out-and-fire", label: "Pop Out & Fire", category: "combat-weapons", description: "Leans out of cover, fires, pulls back in",
    promptHint: "the subject leans out from behind cover, bringing the weapon up to aim and firing, then pulls back behind cover with the weapon tucked in",
    term: "pops out of cover and fires" },
  { id: "flip-table-for-cover", label: "Flip Table for Cover", category: "combat-weapons", description: "Heaves a table onto its side and crouches behind it",
    promptHint: "the subject grabs the edge of a table with both hands, heaves it up onto its side in one lift and drops into a crouch behind the tabletop with the head ducked below the edge",
    term: "flips a table and ducks behind it" },
  { id: "signal-move-up", label: "Tactical Hand Signal", category: "combat-weapons", description: "Two-finger move-up signal, then back on the rifle",
    promptHint: "the subject raises the support hand beside the head with two fingers extended, chops the fingers forward twice to signal the team to move up, then returns the hand to the rifle",
    term: "signals move up with two fingers" },
  { id: "turn-and-fire", label: "Turn & Fire", category: "combat-weapons", description: "Pivots around and fires as the muzzle comes on target",
    promptHint: "the subject pivots on the balls of the feet, swinging the weapon around with the turn and firing the instant the muzzle comes on target, stance settling square",
    term: "turns and fires" },
  { id: "kneel-and-fire", label: "Kneel & Fire", category: "combat-weapons", description: "Drops to one knee and fires from the low stance",
    promptHint: "the subject drops onto one knee with the other foot planted forward, brings the weapon up to the shoulder and fires from the lower stance, elbow braced on the raised knee",
    term: "drops to a knee and fires" },
  { id: "lower-weapon", label: "Lower Weapon", category: "combat-weapons", description: "Weapon eases down from aim, stance relaxes",
    promptHint: "the subject eases the weapon down from aim, arms bending and the muzzle dropping toward the ground as the shoulders relax and the stance opens up",
    term: "lowers the weapon" },
  { id: "twirl-and-holster", label: "Gun Twirl & Holster", category: "combat-weapons", description: "Spins the pistol on the trigger finger, slides it home",
    promptHint: "the subject spins the pistol around the trigger finger in a flourish, catches the grip on the last turn and slides it down into the holster",
    term: "twirls the pistol and holsters it" },
  { id: "throw-grenade", label: "Throw Grenade", category: "combat-weapons", description: "Pulls the pin, lobs overhand, ducks down",
    promptHint: "the subject pulls the pin, cocks the arm back and lobs the grenade forward in a high overhand arc, then drops into a crouch with the head tucked",
    term: "lobs a grenade overhand" },
  { id: "draw-sword", label: "Draw Sword", category: "combat-weapons", description: "Sword pulled from the scabbard up into guard",
    promptHint: "the subject reaches across the body to the hilt, draws the sword in one long pull until the blade clears the scabbard, and brings it up into a guard position",
    term: "draws sword from the scabbard" },
  { id: "slash-with-sword", label: "Sword Slash", category: "combat-weapons", description: "Horizontal cut driven by hip rotation",
    promptHint: "the subject steps into a horizontal sword slash, the blade sweeping across from one side to the other with the pelvis rotating through the cut and the arms finishing extended",
    term: "swings a horizontal sword slash" },
  { id: "drive-overhead-strike", label: "Overhead Strike", category: "combat-weapons", description: "Two-handed vertical cut, weight dropping into it",
    promptHint: "the subject raises the sword above the head with both hands, then drives it straight down in a vertical cut, the body weight dropping into the strike and the blade ending low",
    term: "drives an overhead sword strike" },
  { id: "parry-incoming-strike", label: "Parry", category: "combat-weapons", description: "Blade snaps up to deflect a strike, resets to guard",
    promptHint: "the subject snaps the blade up to meet an incoming strike, catching it and deflecting it aside with a turn of the wrists, then resets the sword to a guard position",
    term: "parries an incoming strike" },
  { id: "sheathe-sword", label: "Sheathe Sword", category: "combat-weapons", description: "Blade guided into the scabbard until the hilt seats",
    promptHint: "the subject lowers the sword, guides the blade tip into the scabbard mouth with the free hand and slides it home until the hilt seats, then drops both hands",
    term: "sheathes the sword" },
  { id: "draw-and-cut", label: "Draw & Cut", category: "combat-weapons", description: "Sword leaves the scabbard straight into a slash",
    promptHint: "the subject draws the sword and cuts in one continuous motion, the blade leaving the scabbard straight into a horizontal slash, then holds the finish with the blade extended low",
    term: "draws and cuts in one motion" },
  { id: "flourish-sword", label: "Sword Flourish", category: "combat-weapons", description: "Figure-eight spin of the blade, settles into guard",
    promptHint: "the subject spins the sword in a figure-eight around the body, the wrist rolling the blade over the back of the hand, then settles it into a guard position",
    term: "spins a figure-eight sword flourish" },
  { id: "raise-sword-to-rally", label: "Raise Sword to Rally", category: "combat-weapons", description: "Thrusts the sword overhead, then points it ahead",
    promptHint: "the subject thrusts the sword straight up overhead with the arm fully extended and the chest lifted, holds it high as a rallying signal, then sweeps the blade down to point ahead",
    term: "raises sword overhead to rally" },
  { id: "raise-shield-to-block", label: "Raise Shield", category: "combat-weapons", description: "Shield snaps up, body braces behind it, lowers",
    promptHint: "the subject snaps a shield up in front of the body, the forearm bracing behind it and the shoulder tucking in as the body leans into the block, then lowers the shield to chest height",
    term: "raises a shield to block" },
  { id: "charge-into-battle", label: "Battle Charge", category: "combat-weapons", description: "Charges forward at a run, weapon raised to strike",
    promptHint: "the subject raises the weapon overhead and charges forward at a run, the body leaning into the charge with the free arm pumping and the weapon arm cocked back ready to strike",
    term: "charges with weapon raised" },
  { id: "roar-a-battle-cry", label: "Battle Cry", category: "combat-weapons", description: "Head back, chest out, roars with a fist pumping up",
    promptHint: "the subject throws the head back with the chest expanding and roars a battle cry with the mouth wide open, the free fist pumping up, then drops the chin back level with the eyes fixed ahead",
    term: "roars a battle cry" },
  { id: "flip-knife", label: "Knife Flip", category: "combat-weapons", description: "Tosses a knife into a spin and catches the handle",
    promptHint: "the subject tosses a knife into a spin from one hand, lets it turn end over end in the air and catches it by the handle in a ready grip",
    term: "flips a knife and catches it" },
  { id: "slash-with-knife", label: "Knife Slash", category: "combat-weapons", description: "Horizontal knife slash at chest height, back to ready",
    promptHint: "the subject snaps a knife across in a horizontal slash at chest height, the wrist leading and the forearm following through, then pulls the blade back to a low ready grip",
    term: "slashes a knife horizontally" },
  { id: "throw-knife", label: "Throw Knife", category: "combat-weapons", description: "Arm whips through and releases a spinning knife",
    promptHint: "the subject draws the arm back with the knife held by the blade, steps forward and whips the arm through, releasing the knife to spin end over end toward the target",
    term: "throws a knife" },
  { id: "thrust-spear", label: "Spear Thrust", category: "combat-weapons", description: "Lunging straight thrust, then pulls it back",
    promptHint: "the subject lunges forward onto the front foot and drives a spear straight ahead, the rear hand pushing through and the front hand guiding, then retracts it back to guard",
    term: "lunges into a spear thrust" },
  { id: "draw-bow-and-release", label: "Draw Bow & Release", category: "combat-weapons", description: "Nock, draw to the cheek, hold, release",
    promptHint: "the subject nocks an arrow, raises the bow with the arm extended and draws the string back to the cheek, holds, then releases with the bow arm staying extended",
    term: "draws the bow and releases" },
  { id: "bat-strike", label: "Bat Strike", category: "combat-weapons", description: "Bat winds back and swings through a horizontal arc",
    promptHint: "the subject grips a bat with both hands, winds it back behind the shoulder and swings it through a horizontal arc, pelvis rotating, finishing past the opposite shoulder",
    term: "swings a bat in a melee strike" },
  { id: "spin-staff", label: "Spin Staff", category: "combat-weapons", description: "Continuous staff rotation hand to hand, snaps to a stop",
    promptHint: "the subject spins a staff in a continuous rotation, passing it hand to hand around the body, then snaps it to a stop held horizontally at guard",
    term: "spins a staff" },
  { id: "flourish-two-weapons", label: "Dual-Wield Flourish", category: "combat-weapons", description: "Mirrored spins of two blades, crosses at the chest",
    promptHint: "the subject spins a blade in each hand in mirrored flourishes around the wrists, crosses them in front of the chest and settles into a two-weapon stance",
    term: "flourishes two weapons" },
  { id: "settle-into-fighting-stance", label: "Settle Into Stance", category: "combat-weapons", description: "From relaxed standing into a fighting stance",
    promptHint: "the subject drops from a relaxed standing posture into a fighting stance, the feet spreading apart as the weight sinks into bent knees, the fists rising to guard and the chin tucking down",
    term: "settles into a fighting stance" },
  { id: "circle-the-opponent", label: "Circle the Opponent", category: "combat-weapons", description: "Sideways shuffle around the partner, guard up",
    promptHint: "the subject circles the partner in sideways shuffle steps with both fists up in guard, the lead foot always leading and the eyes locked on the partner, keeping the distance constant",
    term: "circles the partner with guard up", twoPerson: true },
  { id: "throw-a-punch", label: "Throw a Punch", category: "combat-weapons", description: "Straight rear-hand punch, pelvis behind it, back to guard",
    promptHint: "the subject drives a straight punch forward with the rear hand, pelvis and shoulder rotating behind it, the arm fully extending then snapping back to guard",
    term: "throws a straight punch" },
  { id: "throw-jab-cross", label: "Jab-Cross Combo", category: "combat-weapons", description: "Lead jab then rear cross, hands back to guard",
    promptHint: "the subject fires a lead-hand jab then a rear-hand cross in sequence, the second punch driven by a hip twist, both hands returning to guard by the chin",
    term: "throws a jab-cross combination" },
  { id: "throw-uppercut", label: "Uppercut", category: "combat-weapons", description: "Knees dip, fist rises from the hip to head height",
    promptHint: "the subject dips the knees and drives a fist upward from the hip in a rising arc, the legs and pelvis lifting the punch, ending with the fist at head height",
    term: "throws an uppercut" },
  { id: "swing-elbow-strike", label: "Elbow Strike", category: "combat-weapons", description: "Horizontal elbow at head height, shoulder driving",
    promptHint: "the subject steps in and swings the elbow horizontally at head height, the shoulder driving through the strike, then pulls the arm back to guard",
    term: "swings an elbow strike" },
  { id: "drive-knee-strike", label: "Knee Strike", category: "combat-weapons", description: "Rear knee drives straight up as the hands pull down",
    promptHint: "the subject pulls the pelvis forward and drives the rear knee straight up to torso height, both hands pulling down as the knee rises, then plants the foot back down into stance",
    term: "drives a knee strike" },
  { id: "throw-front-kick", label: "Front Kick", category: "combat-weapons", description: "Knee lifts, lower leg snaps straight out",
    promptHint: "the subject lifts the knee and snaps the lower leg straight out in a front kick with the ball of the foot leading, then retracts the leg and sets the foot down",
    term: "throws a front kick" },
  { id: "throw-roundhouse-kick", label: "Roundhouse Kick", category: "combat-weapons", description: "Wide horizontal arc of the shin at torso height",
    promptHint: "the subject pivots on the standing foot and swings the kicking leg around in a wide horizontal arc, the shin whipping through at torso height, then lands back in stance",
    term: "throws a roundhouse kick" },
  { id: "throw-spinning-hook-kick", label: "Spinning Hook Kick", category: "combat-weapons", description: "Full rotation, rear leg hooks around",
    promptHint: "the subject turns the back to the target, spins a full rotation on the standing foot and swings the rear leg around in a hooking arc, then lands facing forward",
    term: "throws a spinning hook kick" },
  { id: "leap-into-flying-kick", label: "Flying Kick", category: "combat-weapons", description: "Two running steps, launches, kick lands mid-air",
    promptHint: "the subject takes two running steps, launches off one foot and snaps the other leg straight out in a flying kick at head height with the body stretched in the air, then lands on both feet",
    term: "leaps into a flying kick" },
  { id: "sweep-the-legs", label: "Leg Sweep", category: "combat-weapons", description: "Low arcing leg takes the partner's feet out",
    promptHint: "the subject drops low and whips the rear leg in a wide arc along the ground into the partner's ankles, sweeping the partner's feet out so the partner drops onto the back",
    term: "sweeps the partner's legs", twoPerson: true },
  { id: "block-with-forearm", label: "Block", category: "combat-weapons", description: "Forearm intercepts a strike, drops back to guard",
    promptHint: "the subject raises a forearm to intercept an incoming strike, taking the impact on the outer forearm with the body braced, then drops the arm back to guard",
    term: "blocks with the forearm" },
  { id: "weave-under-punch", label: "Dodge a Punch", category: "combat-weapons", description: "Dips under a punch in a U-shape, rises to guard",
    promptHint: "the subject bends the knees and dips the head under an incoming punch, weaving the upper body in a U-shape out to the other side and rising back into guard",
    term: "slips and weaves under a punch" },
  { id: "roll-forward-to-knee", label: "Combat Roll", category: "combat-weapons", description: "Forward shoulder roll, comes up on one knee",
    promptHint: "the subject dives forward over one shoulder, tucks and rolls diagonally across the back, and comes up onto one knee facing forward with the hands ready",
    term: "rolls forward up onto one knee" },
  { id: "grapple-in-clinch", label: "Grapple", category: "combat-weapons", description: "Locks arms with the partner, wrestles for position",
    promptHint: "the subject closes in and locks arms with the partner, both gripping at the shoulders and collar, feet shuffling as they wrestle each other for position",
    term: "grapples the partner in a clinch", twoPerson: true },
  { id: "tackle-to-ground", label: "Tackle", category: "combat-weapons", description: "Shoulder into the midsection, takes the partner down",
    promptHint: "the subject drops low, charges forward and drives a shoulder into the partner's midsection, wrapping both arms around the waist and taking the partner down to the ground",
    term: "tackles the partner to the ground", twoPerson: true },
  { id: "throw-over-hip", label: "Hip Throw", category: "combat-weapons", description: "Turns in, loads the partner on the hip, throws over",
    promptHint: "the subject grips the partner's arm and collar, pivots in to turn the back to the partner, loads the partner up over the hip and throws the partner over onto the ground in one rolling motion",
    term: "throws the partner over the hip", twoPerson: true },
  { id: "shove-with-both-hands", label: "Two-Hand Shove", category: "combat-weapons", description: "Both palms to the chest, partner stumbles back",
    promptHint: "the subject plants both palms on the partner's chest and pushes through, arms extending fully, sending the partner stumbling backward a step",
    term: "shoves the partner with both hands", twoPerson: true },
  { id: "feint-headbutt", label: "Headbutt Feint", category: "combat-weapons", description: "Forehead jerks at the partner's face, stops short",
    promptHint: "the subject jerks the forehead toward the partner's face, stops short of contact as the partner flinches back, then straightens up with a level stare",
    term: "feints a headbutt at the partner", twoPerson: true },
  { id: "flow-through-kung-fu-combo", label: "Kung Fu Combo", category: "combat-weapons", description: "Palm strike, backfist and low sweep, linked",
    promptHint: "the subject flows through a chain of martial-arts strikes — a palm strike, a backfist and a low sweep kick — each move linking into the next with continuous footwork",
    term: "flows through a kung fu combination" },
  { id: "disarm-opponent", label: "Disarm", category: "combat-weapons", description: "Twists the partner's weapon wrist and strips it free",
    promptHint: "the subject grabs the partner's weapon wrist with both hands, twists it outward and strips the weapon free, then steps back with the weapon held ready",
    term: "disarms the partner", twoPerson: true },
  { id: "take-hit-and-stagger", label: "Take a Hit", category: "combat-weapons", description: "Head whips sideways, staggers back, catches balance",
    promptHint: "the subject takes a blow to the jaw, the head whipping to the side, and staggers two steps backward with the knees buckling before catching balance and squaring up",
    term: "takes a hit and staggers" },
  { id: "get-knocked-back", label: "Knocked Back", category: "combat-weapons", description: "Thrown off both feet, lands flat on the back",
    promptHint: "the subject flies backward off both feet from a heavy impact, arms flung forward, and lands flat on the back, sliding to a stop with the limbs loose",
    term: "gets knocked back off the feet" },
  { id: "collapse-in-knockout", label: "Knockout Fall", category: "combat-weapons", description: "Goes limp, knees fold, collapses and lies still",
    promptHint: "the subject goes limp, the knees folding under, and collapses straight down to the ground with the arms loose, landing on the side and lying still, dazed and out cold",
    term: "collapses in a knockout fall" },
  { id: "rise-after-knockdown", label: "Get Back Up", category: "combat-weapons", description: "Pushes up from the ground and raises the fists again",
    promptHint: "the subject pushes up from the ground onto one knee, plants a hand and rises to standing, shakes the head clear and raises both fists back into guard",
    term: "gets up off the ground" },
  { id: "wipe-mouth-with-thumb", label: "Wipe Mouth & Grin", category: "combat-weapons", description: "Thumb drags across the mouth, glances at it, grins",
    promptHint: "the subject drags the thumb across the corner of the mouth, glances down at the thumb, then lifts the chin and breaks into a cocky grin with the eyes coming back up",
    term: "wipes mouth with a thumb and grins" },
  { id: "strike-power-pose-after-hit", label: "Power Pose After Hit", category: "combat-weapons", description: "Lands a strike and freezes in a hero pose",
    promptHint: "the subject lands a strike, then plants the feet wide, straightens up and freezes in a superhero power pose with the chest out and the fists clenched",
    term: "lands a hit and strikes a power pose" },
]
