import type { CharacterMotion } from "./types.js"

/** dance — authored motion fragments. Stable ids survive copy revisions. */
export const DANCE_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { "id": "groove-hip-hop", "label": "Hip-hop groove", "category": "dance", "description": "Bounce and rock on the beat, arms loose",
    "promptHint": "the subject settles into a hip-hop groove, knees bouncing on the beat, chest rocking back and forth, shoulders dipping alternately, weight shifting foot to foot while the arms swing loose", "term": "grooves to a hip-hop beat" },
  { "id": "sway-to-music", "label": "Sway to the music", "category": "dance", "description": "Rock side to side in time, arms relaxed",
    "promptHint": "the subject sways side to side to the music, weight rocking from one foot to the other, hips following, arms relaxed at the sides, head nodding in time with the beat", "term": "sways side to side to the music" },
  { "id": "sway-arms-raised", "label": "Arms-up sway", "category": "dance", "description": "Both arms overhead, swaying with the rhythm",
    "promptHint": "the subject raises both arms overhead and sways side to side, wrists loose, hips rocking with each shift of weight, eyes closing as the body moves with the rhythm", "term": "sways with both arms raised overhead" },
  { "id": "clap-along", "label": "Clap along", "category": "dance", "description": "Claps on the count, body pulsing with it",
    "promptHint": "the subject claps along to the beat, hands meeting at chest height on each count, elbows out, knees bouncing lightly so the whole body pulses with the rhythm", "term": "claps along to the beat" },
  { "id": "two-step-side-to-side", "label": "Two-step", "category": "dance", "description": "Step out, touch, step back, touch, shoulders bobbing",
    "promptHint": "the subject two-steps side to side, stepping one foot out and bringing the other to meet it with a touch, then repeating the other way, shoulders bobbing and arms swinging loosely", "term": "two-steps side to side" },
  { "id": "grapevine-side-step", "label": "Grapevine", "category": "dance", "description": "Step side, cross behind, step side, touch",
    "promptHint": "the subject grapevines sideways, stepping one foot to the side, crossing the other behind it, stepping side again and touching the free foot beside it, then repeating back the other way", "term": "grapevines side to side" },
  { "id": "raise-the-roof", "label": "Raise the roof", "category": "dance", "description": "Palms push up overhead in pumps on the beat",
    "promptHint": "the subject raises the roof, both palms pushing upward overhead in short pumps on each beat, elbows bending and straightening, knees bouncing along and head nodding", "term": "raises the roof" },
  { "id": "slow-dance-close-hold", "label": "Slow dance", "category": "dance", "description": "Close hold, swaying together with a partner",
    "promptHint": "the subject and the partner slow dance in a close hold, arms around each other's neck and waist, swaying side to side in small steps, foreheads nearly touching", "term": "slow dances close with the partner",
    "twoPerson": true, "requires": ["partner"] },
  { "id": "do-house-footwork", "label": "House footwork", "category": "dance", "description": "Tight skipping steps, torso jacking",
    "promptHint": "the subject drops into house footwork, feet skipping and crossing in tight patterns under the body, heels lifting, the torso jacking forward and back while the arms stay loose", "term": "does house footwork with a jacking torso" },
  { "id": "do-toprock", "label": "Toprock", "category": "dance", "description": "Standing breakdance steps before the drop",
    "promptHint": "the subject dances a breakdance toprock, stepping one foot across the other in a cross-step, arms swinging wide, chest lifted, bouncing on the beat before dropping toward the floor", "term": "dances a breakdance toprock" },
  { "id": "spin-into-windmill", "label": "Windmill", "category": "dance", "description": "Floor spin on the shoulders, legs whipping",
    "promptHint": "the subject drops to the floor and rolls into a windmill, legs spread wide in a V and whipping around in circles as the body rotates on the upper back and shoulders", "term": "drops into a breakdance windmill" },
  { "id": "spin-on-the-head", "label": "Headspin", "category": "dance", "description": "Inverted spin on the crown, legs open in a V",
    "promptHint": "the subject kicks up into a headstand and spins on the crown of the head, legs opening wide in a V and hands pushing off the floor to drive the rotation", "term": "spins on the head with legs open" },
  { "id": "hit-a-freeze", "label": "Hold an improvised breakdance freeze", "category": "dance", "description": "Holds a model-chosen breakdance balance; exact choreography is unspecified.",
    "promptHint": "the subject holds an improvised breakdance freeze, showing clear stable contact between the supporting limbs and the floor; the exact balance is model-chosen", "term": "holds an improvised, floor-supported breakdance freeze",
    "requires": ["floor"], "startPose": "floor", "endPose": "floor", "aliases": ["breakdance freeze", "Breakdance Freeze"] },
  { "id": "do-the-worm", "label": "The worm", "category": "dance", "description": "Face-down ripple inching across the floor",
    "promptHint": "the subject dives face-down to the floor and does the worm, a ripple rolling from the chest through the hips to the feet so the body inches forward across the floor in waves", "term": "does the worm across the floor" },
  { "id": "hit-pops", "label": "Popping", "category": "dance", "description": "Sharp muscle hits that jolt the body",
    "promptHint": "the subject dances popping, the chest, arms and legs contracting and releasing in sharp muscle hits on each beat so the body jolts and snaps between held positions", "term": "pops with sharp muscle hits" },
  { "id": "roll-an-arm-wave", "label": "Arm wave", "category": "dance", "description": "Wave rolls from one hand across to the other",
    "promptHint": "the subject sends a wave through the arms, the ripple starting at the fingertips of one hand, rolling through the wrist, elbow and shoulder, across the chest and out through the other arm to the fingertips", "term": "rolls an arm wave across the shoulders" },
  { "id": "lock-and-point", "label": "Locking", "category": "dance", "description": "Wrist rolls, sharp locks and points",
    "promptHint": "the subject dances locking, rolling the wrists in tight circles then freezing the arms in a bent-elbow lock, pointing out to the side, dipping into a knee squat and bouncing back upright", "term": "locks with wrist rolls and sharp points" },
  { "id": "whip-arms-waacking", "label": "Waacking", "category": "dance", "description": "Arm whips around the head, dramatic poses",
    "promptHint": "the subject waacks, whipping the arms over and around the head in sharp circular strikes from the shoulder, wrists flicking, posing dramatically between each strike with chest lifted", "term": "waacks with arm whips around the head" },
  { "id": "strike-vogue-poses", "label": "Vogue", "category": "dance", "description": "Angular hand poses snapping to a dip",
    "promptHint": "the subject vogues, framing the face with angular hand movements that snap from one pose to the next, arms hitting crisp lines, hips squared, then dropping into a dramatic dip", "term": "vogues with angular hand poses into a dip" },
  { "id": "krump-and-stomp", "label": "Krump", "category": "dance", "description": "Stomps, arm strikes and chest pops",
    "promptHint": "the subject krumps, stomping the feet hard, arms swinging in big aggressive strikes, chest popping outward on each hit, the whole body jerking and buckling with raw intensity", "term": "krumps with chest pops and stomps" },
  { "id": "spin-a-pirouette", "label": "Pirouette", "category": "dance", "description": "Ballet turn on one foot, spotting the head",
    "promptHint": "the subject rises onto the ball of one foot and turns a ballet pirouette, the other foot tucked to the knee, arms rounded in front, head whipping to spot, then lands in fourth position", "term": "turns a ballet pirouette" },
  { "id": "extend-into-arabesque", "label": "Arabesque", "category": "dance", "description": "Lift one leg behind into a held line",
    "promptHint": "the subject shifts weight onto one straight leg and lifts the other behind, extending it high with a pointed foot while one arm reaches forward, holding the arabesque line", "term": "extends one leg into arabesque" },
  { "id": "leap-grand-jete", "label": "Grand jeté", "category": "dance", "description": "Running split leap through the air",
    "promptHint": "the subject takes a running preparation and springs into a grand jeté, legs opening into a full split in the air, front leg leading, arms lifted, landing on the front foot", "term": "springs into a grand jeté split leap" },
  { "id": "drop-into-splits", "label": "Drop into splits", "category": "dance", "description": "Slides down into a full split, then pushes back up",
    "promptHint": "the subject drops into the splits, one leg sliding forward and the other back until both are flat on the floor, arms flung out to the sides, then pushes back up to standing", "term": "drops into the splits" },
  { "id": "reach-and-fall", "label": "Reach & fall", "category": "dance", "description": "Contemporary reach, fall to floor, recover",
    "promptHint": "the subject reaches one arm forward and up until the weight tips past balance, then falls through the movement, spiraling down to the floor and rolling back up to standing", "term": "reaches off balance and falls to the floor" },
  { "id": "throw-jazz-kick", "label": "Jazz kick", "category": "dance", "description": "High straight-leg kick, arms flung out",
    "promptHint": "the subject steps forward and throws a high jazz kick, the leg swinging straight up in front to hip height or above, foot pointed, arms flung out to the sides for balance", "term": "throws a high jazz kick" },
  { "id": "tap-dance-steps", "label": "Tap dance", "category": "dance", "description": "Shuffles and stamps in crisp rhythm",
    "promptHint": "the subject tap dances, feet brushing, shuffling and stamping the floor in crisp rhythmic patterns, heels and toes striking alternately while the upper body stays upright and relaxed", "term": "tap dances with crisp shuffles and stamps" },
  { "id": "irish-step-dance", "label": "Irish step dance", "category": "dance", "description": "Arms pinned, feet hopping and kicking on the beat",
    "promptHint": "the subject irish step dances, arms pinned straight at the sides and torso rigid while the feet hop, kick and cross in pointed steps, toes striking the floor on each beat", "term": "irish step dances with arms pinned" },
  { "id": "spin-salsa-turn", "label": "Salsa turn", "category": "dance", "description": "Hip-led steps into a full spot turn",
    "promptHint": "the subject steps into a salsa turn, hips swinging with each step, spinning a full rotation on the ball of one foot, one arm raised, and stepping out on the beat facing forward again", "term": "spins a salsa spot turn" },
  { "id": "sway-bachata-hips", "label": "Bachata sway", "category": "dance", "description": "Side steps with a hip pop on the fourth count",
    "promptHint": "the subject steps side to side in a bachata basic, hips swaying with each step and popping upward on the fourth count, knees soft, arms held loosely at chest height", "term": "steps a bachata basic with a hip pop" },
  { "id": "walk-tango-embrace", "label": "Tango walk", "category": "dance", "description": "Long strides in close embrace with a partner",
    "promptHint": "the subject and the partner walk a tango in close embrace, chests connected, stepping in long deliberate strides with the knees brushing, heads turned sharply to the side, then pausing in a held stance", "term": "tangos with the partner in close embrace",
    "twoPerson": true, "requires": ["partner"] },
  { "id": "waltz-box-step", "label": "Waltz box step", "category": "dance", "description": "Closed-hold box step, rise and fall",
    "promptHint": "the subject and the partner waltz a box step in closed hold, stepping forward, side and together, then back, side and together, rising on the toes on the second count and sinking on the third", "term": "waltzes a box step with the partner",
    "twoPerson": true, "requires": ["partner"] },
  { "id": "swing-out-lindy", "label": "Lindy swing out", "category": "dance", "description": "Rock step, send the partner out and catch",
    "promptHint": "the subject leads the partner through a lindy hop swing out, pulling them in on a rock step, sending them spinning out to arm's length and catching the partner's hand as they swing back", "term": "swings the partner out in a lindy hop",
    "twoPerson": true, "requires": ["partner"] },
  { "id": "spin-partner", "label": "Underarm turn", "category": "dance", "description": "Leads the partner through a turn under the arm",
    "promptHint": "the subject raises the partner's hand overhead and leads the partner through a full turn under the raised arm, the partner pivoting on the balls of the feet before settling back facing the subject", "term": "spins the partner under the arm",
    "twoPerson": true, "requires": ["partner"] },
  { "id": "dip-the-partner", "label": "Ballroom dip", "category": "dance", "description": "Supported backward dip, then lift upright",
    "promptHint": "the subject steps forward and dips the partner backward, one arm supporting the partner's back as the partner arches the spine and extends one leg, holding the dip then lifting them upright", "term": "dips the partner backward",
    "twoPerson": true, "requires": ["partner"] },
  { "id": "shimmy-the-hips", "label": "Hip shimmy", "category": "dance", "description": "Belly-dance hip vibration, torso lifted",
    "promptHint": "the subject shimmies the hips in a belly dance, knees alternating in small rapid bends so the hips vibrate side to side while the torso stays lifted and the arms float at shoulder height", "term": "shimmies the hips belly-dance style" },
  { "id": "shimmy-the-shoulders", "label": "Shoulder shimmy", "category": "dance", "description": "Shoulders alternate forward and back in a flutter",
    "promptHint": "the subject shimmies the shoulders, pushing one shoulder forward as the other pulls back and alternating in a rapid flutter, chest lifted, arms hanging loose, head steady with a grin", "term": "shimmies the shoulders" },
  { "id": "flourish-flamenco-arms", "label": "Flamenco flourish", "category": "dance", "description": "Wrists circling overhead, heel stamps",
    "promptHint": "the subject raises the arms in a flamenco flourish, wrists circling inward as the hands rotate above the head, back arched, chin lifted, then stamps the heels in a sharp rhythmic burst", "term": "flourishes flamenco arms and stamps the heels" },
  { "id": "flourish-bollywood-hands", "label": "Bollywood flourish", "category": "dance", "description": "Rolling hand flicks, head slides, hip bounce",
    "promptHint": "the subject performs a bollywood flourish, hands rolling and flicking outward from the chest with the fingers spread, head sliding side to side, hips bouncing in time with each step", "term": "flicks bollywood hands with a hip bounce" },
  { "id": "do-bhangra", "label": "Bhangra", "category": "dance", "description": "Arms up, shoulders bouncing, knees lifting in hops",
    "promptHint": "the subject does bhangra, both arms raised overhead with index fingers pointing up, shoulders bouncing on the beat while the knees lift high in alternating hops and the head shakes side to side", "term": "does bhangra with arms up" },
  { "id": "dance-afrobeats-legwork", "label": "Afrobeats legwork", "category": "dance", "description": "Knees pumping, feet twisting, torso bent",
    "promptHint": "the subject dances afrobeats legwork, knees pumping in and out, feet skipping and twisting on the floor in loose patterns, shoulders rolling, torso bent forward and bouncing with the groove", "term": "dances afrobeats legwork" },
  { "id": "sway-capoeira-ginga", "label": "Capoeira ginga", "category": "dance", "description": "Rocking triangle step, guarding arm across the chest",
    "promptHint": "the subject sways in a capoeira ginga, one foot stepping back into a low lunge as the opposite arm guards across the chest, then shifting forward and switching sides in a rocking triangle step", "term": "sways in capoeira ginga" },
  { "id": "hit-kpop-point-move", "label": "Improvise K-pop point move", "category": "dance", "description": "Arms snap into a signature shape on the beat. Choreography is model-chosen.",
    "promptHint": "the subject hits a k-pop point move, both arms snapping into a crisp angular shape in front of the chest on the beat, head tilting with it, then stepping side to side into the next sharp pose; the choreography is improvised rather than a specific signature routine", "term": "improvises a K-pop point move on the beat",
    "kind": "compound", "aliases": ["K-Pop Point Move", "Kpop"] },
  { "id": "moonwalk-backward", "label": "Moonwalk", "category": "dance", "description": "Glide backward while the feet seem to walk forward",
    "promptHint": "the subject moonwalks, sliding backward across the floor while the feet appear to walk forward, one heel lifted as the flat foot glides, upper body upright and loose", "term": "moonwalks backward across the floor" },
  { "id": "do-the-robot", "label": "The robot", "category": "dance", "description": "Stiff mechanical segments, stopping at joints",
    "promptHint": "the subject does the robot, moving the arms and head in stiff mechanical segments that stop dead at each joint, torso locking between moves, with small jerky ticks between positions", "term": "does the robot with stiff isolations" },
  { "id": "do-the-twist", "label": "The twist", "category": "dance", "description": "Feet planted, hips swiveling against shoulders",
    "promptHint": "the subject does the twist, feet planted while the hips and knees swivel side to side in opposition to the shoulders, bending lower and rising back up as the arms pump", "term": "does the twist with swiveling hips" },
  { "id": "throw-disco-point", "label": "Disco point", "category": "dance", "description": "Arm sweeps across then shoots up diagonally",
    "promptHint": "the subject strikes a disco point, one arm sweeping across the body then shooting up diagonally with the index finger extended, hips pushing the other way on each beat", "term": "throws a disco point across the body" },
  { "id": "do-the-floss", "label": "The floss", "category": "dance", "description": "Straight arms swing past the hips, hips opposite",
    "promptHint": "the subject does the floss dance, both arms held straight and swinging together past the hips, passing behind the body on one side and in front on the other, while the hips swing the opposite way", "term": "does the floss arm swing" },
  { "id": "hit-a-dab", "label": "Dab", "category": "dance", "description": "Head drops into the elbow, other arm shoots out",
    "promptHint": "the subject dabs, dropping the head into the crook of one bent elbow while the other arm shoots straight out to the side and up, holding the shape then straightening", "term": "dabs into the elbow" },
  { "id": "hit-the-woah", "label": "The woah", "category": "dance", "description": "Fists circle then lock sharply on the beat",
    "promptHint": "the subject hits the woah, both fists circling once in front of the chest then locking sharply, one fist above the other, the body freezing in a lean on the beat", "term": "hits the woah" },
  { "id": "do-the-griddy", "label": "The griddy", "category": "dance", "description": "Heels kick back on hops, arms pump, hands to eyes",
    "promptHint": "the subject does the griddy, hopping forward on alternating feet as each heel kicks up behind, arms pumping in loose circles, then raises both hands to the eyes in a binocular shape", "term": "does the griddy" },
  { "id": "do-the-running-man", "label": "Running man", "category": "dance", "description": "Knees lift while the standing foot slides back",
    "promptHint": "the subject does the running man, one knee lifting high while the standing foot slides back, then switching, the feet appearing to run in place with the arms pumping", "term": "does the running man shuffle" },
  { "id": "shuffle-cutting-shapes", "label": "Melbourne shuffle", "category": "dance", "description": "Running man into T-steps, cutting shapes",
    "promptHint": "the subject dances the melbourne shuffle, feet kicking and sliding through running-man steps then twisting sideways into t-steps, heels and toes pivoting across the floor while the arms swing loosely", "term": "dances the Melbourne shuffle" },
  { "id": "headbang-to-music", "label": "Headbang", "category": "dance", "description": "Head whips forward and back, hair flying",
    "promptHint": "the subject headbangs, whipping the head forward and down then back up from the neck in time with a heavy beat, hair flying, shoulders hunched and hands gripping the air", "term": "headbangs to the music" },
  { "id": "whip-hair-in-circle", "label": "Hair whip circle", "category": "dance", "description": "Head swings the hair through a full circle",
    "promptHint": "the subject whips the hair in a full circle, bending forward at the waist and swinging the head around in a wide loop so the hair fans out and trails through the air", "term": "whips hair in a full circle" },
  { "id": "roll-the-body", "label": "Body roll", "category": "dance", "description": "Wave from chest through ribs to hips",
    "promptHint": "the subject rolls the body in a wave, the chest pushing forward first, then the ribs, stomach and hips following in sequence, ending with the hips tucked under", "term": "rolls the body from chest to hips" },
]
