import type { CharacterMotion } from "./types.js"

/** Entrances & Exits — 36 entries. Category id `entrances-exits`. */
export const ENTRANCES_EXITS_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "walk-in-from-left", label: "Walk In From Left", category: "entrances-exits", description: "Enters from the left edge and stops at center",
    promptHint: "the subject walks into frame from the left edge at an even stride, weight rolling heel to toe, crosses toward center and stops facing forward",
    term: "walks in from frame left" },
  { id: "walk-in-from-right", label: "Walk In From Right", category: "entrances-exits", description: "Enters from the right edge and stops at center",
    promptHint: "the subject walks into frame from the right edge at an even stride, weight rolling heel to toe, crosses toward center and stops facing forward",
    term: "walks in from frame right" },
  { id: "enter-from-behind-camera", label: "Enter From Behind Camera", category: "entrances-exits", description: "Passes the lens and walks into the scene",
    promptHint: "the subject steps into frame from behind the camera, passing close beside the lens with their back to it, and walks forward into the scene to stop mid-frame",
    term: "enters past the camera from behind" },
  { id: "approach-from-background", label: "Approach From Background", category: "entrances-exits", description: "Distant figure walks up to mid-frame",
    promptHint: "the subject walks straight toward the camera from deep in the background, growing larger with each step, and stops at mid-distance facing forward",
    term: "approaches from deep background" },
  { id: "walk-up-to-camera", label: "Walk Up To Camera", category: "entrances-exits", description: "Closes in until the face fills the frame",
    promptHint: "the subject walks straight toward the camera from mid-frame, closing the distance until their face and shoulders fill the frame, and stops just short of the lens",
    term: "walks up to the camera and stops" },
  { id: "run-toward-camera", label: "Run Toward Camera", category: "entrances-exits", description: "Sprints straight at the lens and pulls up short",
    promptHint: "the subject runs straight toward the camera from deep in the background, arms pumping and torso leaning into the stride, and pulls up short just in front of the lens with chest heaving",
    term: "runs toward the camera and stops" },
  { id: "run-in-and-stop", label: "Run In & Stop", category: "entrances-exits", description: "Sprints in from the left, pulls up at center",
    promptHint: "the subject runs into frame from the left edge at full stride, decelerates over several steps with weight rocking back onto the heels, and stops upright at center",
    term: "runs in from frame left and stops" },
  { id: "burst-in-through-doorway", label: "Burst In Through Doorway", category: "entrances-exits", description: "Slams through a door and plants both feet",
    promptHint: "the subject bursts through a doorway in the background, shoving the door open with one arm, lunging two steps forward and planting both feet with shoulders squared to the camera",
    term: "bursts in through a doorway" },
  { id: "kick-open-door", label: "Kick Open Door", category: "entrances-exits", description: "Boots a door open from behind and strides in",
    promptHint: "the subject kicks a closed door in the background open from the far side with the sole of one foot, the door swinging wide, and strides through the doorway toward the camera with shoulders squared, stopping in clear view",
    term: "kicks the door open and steps through" },
  { id: "dive-through-window", label: "Dive Through Window", category: "entrances-exits", description: "Launches headfirst through a window and rolls up",
    promptHint: "the subject launches headfirst through a window in the background toward the camera, arms crossed over the face, tucks into a shoulder roll on landing and comes up onto both feet",
    term: "dives through a window and rolls" },
  { id: "climb-through-window", label: "Climb Through Window", category: "entrances-exits", description: "Hoists in over a windowsill and drops to the floor",
    promptHint: "the subject grips a windowsill, hoists one leg over it followed by the other, ducks the head under the top of the window and drops quietly onto both feet inside",
    term: "climbs in through a window" },
  { id: "stumble-in", label: "Stumble In", category: "entrances-exits", description: "Trips in from the right and recovers balance",
    promptHint: "the subject stumbles into frame from the right edge, one foot catching, torso pitching forward with arms flung out for balance, and regains balance to straighten up at center",
    term: "stumbles in from frame right" },
  { id: "sneak-in", label: "Sneak In", category: "entrances-exits", description: "Creeps in low from the left, then stands",
    promptHint: "the subject creeps into frame from the left edge in a low crouch, placing each foot carefully and glancing side to side, and straightens up cautiously at center",
    term: "sneaks in from frame left" },
  { id: "dash-across-frame", label: "Dash Across Frame", category: "entrances-exits", description: "Sprints in from the left and out the right edge",
    promptHint: "the subject sprints across frame from the left edge to the right edge without slowing, body leaning into the run, and is gone out the far side",
    term: "dashes across frame left to right" },
  { id: "slide-in-on-knees", label: "Slide In On Knees", category: "entrances-exits", description: "Glides in on both knees, arms spread",
    promptHint: "the subject slides into frame from the left edge on both knees, torso upright and arms spread wide, gliding across the floor to a stop at center",
    term: "knee-slides in from frame left" },
  { id: "sock-slide-into-frame", label: "Sock Slide Into Frame", category: "entrances-exits", description: "Skids in on socked feet and catches balance",
    promptHint: "the subject slides into frame from the left edge on socked feet, knees soft and arms out for balance, skidding across a smooth floor and catching balance at center",
    term: "sock-slides in from frame left" },
  { id: "drop-in-from-above", label: "Drop In From Above", category: "entrances-exits", description: "Lands from above, knees absorb, stands up",
    promptHint: "the subject drops into frame from above the top edge, lands on both feet with knees bending deep to absorb the impact and one hand touching the ground, and rises to stand",
    term: "drops in from above and lands" },
  { id: "rise-into-frame", label: "Rise Into Frame", category: "entrances-exits", description: "Stands up into view from the bottom edge",
    promptHint: "the subject rises into frame from below the bottom edge, standing up out of a crouch so the head appears first with shoulders and torso following until they stand fully upright at center",
    term: "rises into frame from below" },
  { id: "pop-up-from-cover", label: "Pop Up From Cover", category: "entrances-exits", description: "Springs into view from behind foreground cover",
    promptHint: "the subject pops up from behind an object in the foreground, head and shoulders springing into view above its top edge, and straightens to stand facing the camera",
    term: "pops up from behind an object" },
  { id: "lean-into-frame", label: "Lean Into Frame", category: "entrances-exits", description: "Head and shoulders tip in, then back out",
    promptHint: "the subject leans into frame from the left edge, head and shoulders tipping into view while the feet stay planted out of shot, and leans back out of frame",
    term: "leans in and out from frame left" },
  { id: "peek-into-frame", label: "Peek Into Frame", category: "entrances-exits", description: "Head appears from the right edge, eyes on lens",
    promptHint: "the subject peeks into frame from the right edge, head and one shoulder appearing first with the eyes finding the lens, and the rest of the body follows into view",
    term: "peeks in from frame right" },
  { id: "enter-through-doorway", label: "Enter Through Doorway", category: "entrances-exits", description: "Crosses a threshold and walks into view",
    promptHint: "the subject steps out through a doorway in the background, crossing the threshold with one foot after the other, and walks a few paces forward to stop in clear view",
    term: "enters through a doorway" },
  { id: "step-out-of-shadow", label: "Step Out Of Shadow", category: "entrances-exits", description: "Emerges from a dark recess into clear view",
    promptHint: "the subject steps forward out of a dark recess at the back of the frame into clear view, face and body fully visible, and stops facing the camera",
    term: "steps out of the shadows" },
  { id: "emerge-from-crowd", label: "Emerge From Crowd", category: "entrances-exits", description: "Pushes through bodies into open space",
    promptHint: "the subject pushes forward through a crowd of people, angling their shoulders past the people around them, and steps clear into open space at the front of the frame, stopping to face forward",
    term: "emerges from a crowd" },
  { id: "step-around-corner", label: "Step Around Corner", category: "entrances-exits", description: "Shoulder first, then the body swings into view",
    promptHint: "the subject steps around a corner into frame, one shoulder appearing first and the body swinging into view behind it, and walks a few paces forward to stop in the open",
    term: "steps around a corner into frame" },
  { id: "walk-out-left", label: "Walk Out Left", category: "entrances-exits", description: "Crosses from center and exits the left edge",
    promptHint: "the subject starts at center of frame, walks toward the left edge at an even stride with the body in profile, and exits the frame completely, leaving it empty",
    term: "walks out frame left" },
  { id: "walk-out-right", label: "Walk Out Right", category: "entrances-exits", description: "Crosses from center and exits the right edge",
    promptHint: "the subject starts at center of frame, walks toward the right edge at an even stride with the body in profile, and exits the frame completely, leaving it empty",
    term: "walks out frame right" },
  { id: "run-out-of-frame", label: "Run Out Of Frame", category: "entrances-exits", description: "Breaks from center into a sprint out the right edge",
    promptHint: "the subject breaks from standing at center into a run toward the right edge, body leaning into the first strides, and sprints out of frame, leaving it empty",
    term: "runs out frame right" },
  { id: "walk-away-into-distance", label: "Walk Away Into Distance", category: "entrances-exits", description: "Back to camera, shrinks into the background",
    promptHint: "the subject stands with their back to the camera and walks straight away into the background, shrinking with each step until they are a small distant figure",
    term: "walks away into the distance" },
  { id: "run-away-into-distance", label: "Run Away Into Distance", category: "entrances-exits", description: "Back to camera, sprints off into the background",
    promptHint: "the subject turns their back to the camera and runs straight away into the background, arms pumping, shrinking with each stride until they are a small distant figure",
    term: "runs away into the distance" },
  { id: "turn-and-walk-away", label: "Turn & Walk Away", category: "entrances-exits", description: "Pivots away from camera and walks off",
    promptHint: "the subject stands facing the camera, pivots on one foot to turn their back, and walks off into the background, growing smaller until they are far from the camera",
    term: "turns and walks away" },
  { id: "back-out-of-frame", label: "Back Out Of Frame", category: "entrances-exits", description: "Retreats backward until out of frame",
    promptHint: "the subject faces the camera and steps backward, one foot reaching behind the other, retreating on a diagonal toward the left edge until they back out of frame and are gone",
    term: "backs out of frame" },
  { id: "dragged-out-of-frame", label: "Dragged Out Of Frame", category: "entrances-exits", description: "Hauled backward out of shot, hands clawing the floor",
    promptHint: "the subject is yanked backward off their feet and dragged flat on their back along the floor toward the bottom edge of frame, fingers clawing at the ground and legs kicking, until pulled out of shot",
    term: "is dragged backward out of frame" },
  { id: "exit-past-camera", label: "Exit Past Camera", category: "entrances-exits", description: "Walks up to and past the lens",
    promptHint: "the subject walks straight toward the camera, growing larger in frame, passes close beside the lens and exits, leaving the background empty behind them",
    term: "exits past the camera" },
  { id: "duck-out-of-frame", label: "Duck Out Of Frame", category: "entrances-exits", description: "Crouches down and out the bottom edge",
    promptHint: "the subject drops into a crouch and ducks down below the bottom edge of frame, the head disappearing last, leaving the frame empty above",
    term: "ducks out below frame" },
  { id: "exit-through-doorway", label: "Exit Through Doorway", category: "entrances-exits", description: "Opens a door, steps through, closes it",
    promptHint: "the subject walks to a doorway in the background, opens the door with one hand, steps through it and pulls it closed behind them, leaving the frame empty",
    term: "exits through a doorway" },
]
