import type { CharacterMotion } from "./types.js"

/** entrances-exits — authored motion fragments. Stable ids survive copy revisions. */
export const ENTRANCES_EXITS_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { "id": "walk-in-from-left", "label": "Walk in from left", "category": "entrances-exits", "description": "Enters from the left edge and stops at center",
    "promptHint": "the subject walks into frame from the left edge at an even stride, weight rolling heel to toe, crosses toward center and stops facing forward", "term": "walks in from frame left" },
  { "id": "walk-in-from-right", "label": "Walk in from right", "category": "entrances-exits", "description": "Enters from the right edge and stops at center",
    "promptHint": "the subject walks into frame from the right edge at an even stride, weight rolling heel to toe, crosses toward center and stops facing forward", "term": "walks in from frame right" },
  { "id": "enter-from-behind-camera", "label": "Enter from behind camera", "category": "entrances-exits", "description": "Passes the lens and walks into the scene",
    "promptHint": "the subject steps into frame from behind the camera, passing close beside the lens with their back to it, and walks forward into the scene to stop mid-frame", "term": "enters past the camera from behind" },
  { "id": "approach-from-background", "label": "Approach from background", "category": "entrances-exits", "description": "Distant figure walks up to mid-frame",
    "promptHint": "the subject walks straight toward the camera from deep in the background, growing larger with each step, and stops at mid-distance facing forward", "term": "approaches from deep background" },
  { "id": "walk-up-to-camera", "label": "Walk up to camera", "category": "entrances-exits", "description": "Closes in until the face fills the frame",
    "promptHint": "the subject walks straight toward the camera from mid-frame, closing the distance until their face and shoulders fill the frame, and stops just short of the lens", "term": "walks up to the camera and stops" },
  { "id": "run-toward-camera", "label": "Run toward camera", "category": "entrances-exits", "description": "Sprints straight at the lens and pulls up short",
    "promptHint": "the subject runs straight toward the camera from deep in the background, arms pumping and torso leaning into the stride, and pulls up short just in front of the lens with chest heaving", "term": "runs toward the camera and stops" },
  { "id": "run-in-and-stop", "label": "Run in from left and stop", "category": "entrances-exits", "description": "Runs in through frame left and stops near center.",
    "promptHint": "the subject runs into frame from the left edge, slows over several steps and comes to a balanced stop near the center", "term": "runs in from frame left, stopping near center",
    "aliases": ["Run In & Stop"] },
  { "id": "burst-in-through-doorway", "label": "Burst in through doorway", "category": "entrances-exits", "description": "Slams through a door and plants both feet",
    "promptHint": "the subject bursts through a doorway in the background, shoving the door open with one arm, lunging two steps forward and planting both feet with shoulders squared to the camera", "term": "bursts in through a doorway" },
  { "id": "kick-open-door", "label": "Kick open door", "category": "entrances-exits", "description": "Boots a door open from behind and strides in",
    "promptHint": "the subject kicks a closed door in the background open from the far side with the sole of one foot, the door swinging wide, and strides through the doorway toward the camera with shoulders squared, stopping in clear view", "term": "kicks the door open and steps through" },
  { "id": "dive-through-window", "label": "Dive through window", "category": "entrances-exits", "description": "Launches headfirst through a window and rolls up",
    "promptHint": "the subject launches headfirst through a window in the background toward the camera, arms crossed over the face, tucks into a shoulder roll on landing and comes up onto both feet", "term": "dives through a window and rolls" },
  { "id": "climb-through-window", "label": "Climb through window", "category": "entrances-exits", "description": "Hoists in over a windowsill and drops to the floor",
    "promptHint": "the subject grips a windowsill, hoists one leg over it followed by the other, ducks the head under the top of the window and drops quietly onto both feet inside", "term": "climbs in through a window" },
  { "id": "stumble-in", "label": "Stumble in — right", "category": "entrances-exits", "description": "Trips in from the right and recovers balance (frame right).",
    "promptHint": "the subject stumbles into frame from the right edge, one foot catching, torso pitching forward with arms flung out for balance, and regains balance to straighten up at center", "term": "stumbles in from frame right",
    "aliases": ["Stumble In"] },
  { "id": "sneak-in", "label": "Sneak in — left", "category": "entrances-exits", "description": "Creeps in low from the left, then stands (frame left).",
    "promptHint": "the subject creeps into frame from the left edge in a low crouch, placing each foot carefully and glancing side to side, and straightens up cautiously at center", "term": "sneaks in from frame left",
    "aliases": ["Sneak In"] },
  { "id": "dash-across-frame", "label": "Dash across frame — left to right", "category": "entrances-exits", "description": "Sprints in from the left and out the right edge (frame left to right).",
    "promptHint": "the subject sprints across frame from the left edge to the right edge without slowing, body leaning into the run, and is gone out the far side", "term": "dashes across frame left to right",
    "endVisibility": "out-of-frame", "aliases": ["Dash Across Frame"] },
  { "id": "slide-in-on-knees", "label": "Slide in from left on knees", "category": "entrances-exits", "description": "Slides in from frame left on both knees and comes to a stop.",
    "promptHint": "the subject enters from the left edge sliding on both knees, slows and comes to a stop", "term": "slides from frame left on both knees, stopping",
    "startPose": "floor", "endPose": "floor", "requires": ["smooth floor"], "aliases": ["Slide In On Knees"] },
  { "id": "sock-slide-into-frame", "label": "Sock slide into frame", "category": "entrances-exits", "description": "Skids in on socked feet and catches balance",
    "promptHint": "the subject slides into frame from the left edge on socked feet, knees soft and arms out for balance, skidding across a smooth floor and catching balance at center", "term": "sock-slides in from frame left" },
  { "id": "drop-in-from-above", "label": "Drop in from above", "category": "entrances-exits", "description": "Lands from above, knees absorb, stands up",
    "promptHint": "the subject drops into frame from above the top edge, lands on both feet with knees bending deep to absorb the impact and one hand touching the ground, and rises to stand", "term": "drops in from above and lands" },
  { "id": "rise-into-frame", "label": "Rise into frame", "category": "entrances-exits", "description": "Stands up into view from the bottom edge",
    "promptHint": "the subject rises into frame from below the bottom edge, standing up out of a crouch so the head appears first with shoulders and torso following until they stand fully upright at center", "term": "rises into frame from below" },
  { "id": "pop-up-from-cover", "label": "Pop up from cover", "category": "entrances-exits", "description": "Springs into view from behind foreground cover",
    "promptHint": "the subject pops up from behind an object in the foreground, head and shoulders springing into view above its top edge, and straightens to stand facing the camera", "term": "pops up from behind an object" },
  { "id": "lean-into-frame", "label": "Lean into frame — left", "category": "entrances-exits", "description": "Head and shoulders tip in, then back out (frame left).",
    "promptHint": "the subject leans into frame from the left edge, head and shoulders tipping into view while the feet stay planted out of shot, and leans back out of frame", "term": "leans in and out from frame left",
    "endVisibility": "out-of-frame", "aliases": ["Lean Into Frame"] },
  { "id": "peek-into-frame", "label": "Peek in from frame right", "category": "entrances-exits", "description": "Leans the head into view from the right and holds the peek.",
    "promptHint": "the subject leans the head and one shoulder into view from the right edge of the frame and holds the peek while the rest of the body stays out of view", "term": "peeks into frame from the right",
    "aliases": ["Peek Into Frame"] },
  { "id": "enter-through-doorway", "label": "Enter through doorway", "category": "entrances-exits", "description": "Crosses a threshold and walks into view",
    "promptHint": "the subject steps out through a doorway in the background, crossing the threshold with one foot after the other, and walks a few paces forward to stop in clear view", "term": "enters through a doorway" },
  { "id": "step-out-of-shadow", "label": "Step out of shadow", "category": "entrances-exits", "description": "Emerges from a dark recess into clear view",
    "promptHint": "the subject steps forward out of a dark recess at the back of the frame into clear view, face and body fully visible, and stops facing the camera", "term": "steps out of the shadows" },
  { "id": "emerge-from-crowd", "label": "Emerge from crowd", "category": "entrances-exits", "description": "Pushes through bodies into open space",
    "promptHint": "the subject pushes forward through a crowd of people, angling their shoulders past the people around them, and steps clear into open space at the front of the frame, stopping to face forward", "term": "emerges from a crowd" },
  { "id": "step-around-corner", "label": "Step around corner", "category": "entrances-exits", "description": "Shoulder first, then the body swings into view",
    "promptHint": "the subject steps around a corner into frame, one shoulder appearing first and the body swinging into view behind it, and walks a few paces forward to stop in the open", "term": "steps around a corner into frame" },
  { "id": "walk-out-left", "label": "Exit frame left", "category": "entrances-exits", "description": "Walks out through the left edge of the frame.",
    "promptHint": "the subject walks toward the left edge of the frame and continues until completely out of view", "term": "walks out through frame left",
    "endVisibility": "out-of-frame", "aliases": ["Walk Out Left"] },
  { "id": "walk-out-right", "label": "Exit frame right", "category": "entrances-exits", "description": "Walks out through the right edge of the frame.",
    "promptHint": "the subject walks toward the right edge of the frame and continues until completely out of view", "term": "walks out through frame right",
    "endVisibility": "out-of-frame", "aliases": ["Walk Out Right"] },
  { "id": "run-out-of-frame", "label": "Run out through frame right", "category": "entrances-exits", "description": "Runs out of view through the right edge.",
    "promptHint": "the subject runs toward the right edge of the frame and continues until completely out of view", "term": "runs out through frame right",
    "endVisibility": "out-of-frame", "aliases": ["Run Out Of Frame"] },
  { "id": "walk-away-into-distance", "label": "Walk away into distance", "category": "entrances-exits", "description": "Back to camera, shrinks into the background",
    "promptHint": "the subject stands with their back to the camera and walks straight away into the background, shrinking with each step until they are a small distant figure", "term": "walks away into the distance" },
  { "id": "run-away-into-distance", "label": "Run away into distance", "category": "entrances-exits", "description": "Back to camera, sprints off into the background",
    "promptHint": "the subject turns their back to the camera and runs straight away into the background, arms pumping, shrinking with each stride until they are a small distant figure", "term": "runs away into the distance" },
  { "id": "turn-and-walk-away", "label": "Turn & walk away", "category": "entrances-exits", "description": "Pivots away from camera and walks off",
    "promptHint": "the subject stands facing the camera, pivots on one foot to turn their back, and walks off into the background, growing smaller until they are far from the camera", "term": "turns and walks away" },
  { "id": "back-out-of-frame", "label": "Back out through frame left", "category": "entrances-exits", "description": "Retreats diagonally backward out of the left edge.",
    "promptHint": "the subject keeps facing into the scene and steps diagonally backward toward the left edge until completely out of view", "term": "backs diagonally out through frame left",
    "endVisibility": "out-of-frame", "aliases": ["Back Out Of Frame"] },
  { "id": "dragged-out-of-frame", "label": "Dragged out of frame", "category": "entrances-exits", "description": "Hauled backward out of shot, hands clawing the floor",
    "promptHint": "the subject is yanked backward off their feet and dragged flat on their back along the floor toward the bottom edge of frame, fingers clawing at the ground and legs kicking, until pulled out of shot", "term": "is dragged backward out of frame",
    "endVisibility": "out-of-frame" },
  { "id": "exit-past-camera", "label": "Exit past camera", "category": "entrances-exits", "description": "Walks past the camera and out of view.",
    "promptHint": "the subject walks toward the camera, passes beside it and continues out of view", "term": "walks past the camera and out of view",
    "endVisibility": "out-of-frame" },
  { "id": "duck-out-of-frame", "label": "Duck below frame", "category": "entrances-exits", "description": "Lowers the body until out of view below the frame.",
    "promptHint": "the subject bends the knees and lowers the head and torso until completely below the bottom edge of the frame", "term": "ducks below the bottom of the frame",
    "endVisibility": "out-of-frame", "aliases": ["Duck Out Of Frame"] },
  { "id": "exit-through-doorway", "label": "Exit through doorway", "category": "entrances-exits", "description": "Walks through a doorway and out of view.",
    "promptHint": "the subject walks through the open doorway and continues until out of view", "term": "walks through a doorway and out of view",
    "requires": ["open doorway"], "endVisibility": "out-of-frame" },
]
