import type { CharacterMotion } from "./types.js"

/** evasive-falls — authored motion fragments. Stable ids survive copy revisions. */
export const EVASIVE_FALLS_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { "id": "duck-under", "label": "Duck under", "category": "evasive-falls", "description": "Drops head and shoulders under a passing threat",
    "promptHint": "the subject snaps the head and shoulders down, knees bending so the whole body dips below the line of a passing threat, before rising back to full height", "term": "ducks under a passing threat" },
  { "id": "dodge-sideways", "label": "Sidestep dodge", "category": "evasive-falls", "description": "Lateral step out of the line of attack",
    "promptHint": "the subject pushes off one foot and steps wide sideways, torso twisting out of the line of attack, weight landing on the outside leg before the feet reset square", "term": "sidesteps out of the line of attack" },
  { "id": "lean-back-dodge", "label": "Lean-back dodge", "category": "evasive-falls", "description": "Bends backward from the waist under a swing",
    "promptHint": "the subject bends backward from the waist and knees as if under a swing passing overhead, spine arching and arms trailing, the head dipping below the line of attack before snapping back upright", "term": "leans back under a swing" },
  { "id": "flinch-away", "label": "Flinch", "category": "evasive-falls", "description": "Sharp involuntary jerk of the head and shoulders",
    "promptHint": "the subject jerks the head and shoulders back and away, eyes squeezing shut and one hand half-raising toward the face, the body tensing before settling again", "term": "flinches back from a sudden threat" },
  { "id": "jump-back-startled", "label": "Startled jump back", "category": "evasive-falls", "description": "Hops backward with hands rising in surprise",
    "promptHint": "the subject startles and hops backward off both feet, hands flying up to chest height and shoulders hunching, landing a step behind the start position with the eyes wide", "term": "jumps back in surprise" },
  { "id": "dive-for-cover", "label": "Dive for cover", "category": "evasive-falls", "description": "Launches headlong behind the nearest cover",
    "promptHint": "the subject drives off both legs into a headlong dive toward the nearest cover, arms leading, body stretching horizontal through the air and landing on the forearms and chest behind it", "term": "dives for cover" },
  { "id": "duck-behind-cover", "label": "Duck behind cover", "category": "evasive-falls", "description": "Drops low behind cover and presses against it",
    "promptHint": "the subject darts sideways and drops into a crouch behind cover, back pressing flat against it, knees pulled in and head tucked below the top edge", "term": "drops into a crouch behind cover" },
  { "id": "evasive-roll", "label": "Evasive roll", "category": "evasive-falls", "description": "Dives into a shoulder roll and comes up clear",
    "promptHint": "the subject dives sideways into a shoulder roll, tucking the head and rolling diagonally across the back from shoulder to opposite hip, and comes up onto one knee clear of the danger", "term": "rolls out of the way" },
  { "id": "hurdle-low-obstacle", "label": "Hurdle obstacle", "category": "evasive-falls", "description": "Leaps over something low without breaking stride",
    "promptHint": "the subject takes off from one foot and clears a low obstacle, lead leg driving up and over with the trailing leg tucked, landing on the far side and carrying on", "term": "hurdles a low obstacle" },
  { "id": "spin-away-from-danger", "label": "Half-turn and move away", "category": "evasive-falls", "description": "Turns halfway around and moves away in the new direction.",
    "promptHint": "the subject pivots through a half-turn to face away from the original direction, then moves forward in the new direction", "term": "turns halfway around and moves away",
    "startPose": "standing", "endPose": "standing", "aliases": ["Spin Away"] },
  { "id": "hit-the-deck", "label": "Hit the deck", "category": "evasive-falls", "description": "Throws the body flat with arms over the head",
    "promptHint": "the subject throws the body flat to the ground in one motion, landing on the forearms and belly with both hands clamped over the back of the head and the face pressed down", "term": "hits the deck" },
  { "id": "drop-to-ground", "label": "Drop prone", "category": "evasive-falls", "description": "Lowers straight down to lie flat on the ground",
    "promptHint": "the subject drops straight down from standing, knees folding and hands hitting the ground, and flattens out prone with the chest to the earth and head kept low", "term": "drops prone to the ground" },
  { "id": "stumble-and-recover", "label": "Stumble & recover", "category": "evasive-falls", "description": "Loses footing mid-step and regains balance",
    "promptHint": "the subject mis-steps and pitches forward off balance, arms windmilling outward and one foot slapping down ahead to catch the weight, before straightening up and continuing on", "term": "stumbles and recovers balance" },
  { "id": "trip-and-fall", "label": "Trip & fall", "category": "evasive-falls", "description": "Catches a foot and goes down onto hands and knees",
    "promptHint": "the subject catches a foot on something low, pitches forward past the point of recovery and goes down, hands slapping the ground first and knees following, ending sprawled on all fours", "term": "trips and falls forward" },
  { "id": "slip-on-surface", "label": "Slip", "category": "evasive-falls", "description": "Feet shoot out on a slick surface",
    "promptHint": "the subject steps onto a slick patch and the leading foot shoots out forward, arms flailing upward for balance, and drops onto one hip with both hands slapping the ground", "term": "slips on a slick surface" },
  { "id": "fall-backward", "label": "Fall backward", "category": "evasive-falls", "description": "Topples onto the back, arms flung out",
    "promptHint": "the subject tips backward past the heels, arms flinging out to the sides and knees buckling, landing seat-first and rolling flat onto the back with the head coming down last", "term": "falls flat on the back" },
  { "id": "fall-forward", "label": "Fall forward", "category": "evasive-falls", "description": "Pitches face-down onto the ground",
    "promptHint": "the subject pitches forward from the ankles like a felled tree, arms coming up too late to break the fall, and lands chest-first on the ground, head turning to one side on impact", "term": "falls forward face-down" },
  { "id": "collapse-to-knees", "label": "Collapse to knees", "category": "evasive-falls", "description": "Legs give way and the body drops to both knees",
    "promptHint": "the subject buckles at the knees and drops straight down onto both of them, torso folding forward, hands landing on the thighs as the head hangs low", "term": "collapses to both knees" },
  { "id": "faint-and-crumple", "label": "Faint", "category": "evasive-falls", "description": "Goes limp and folds to the floor",
    "promptHint": "the subject goes limp, eyes closing and knees folding first, the torso sagging sideways and the head lolling as the body crumples to the floor in a loose heap", "term": "faints and crumples to the floor" },
  { "id": "knocked-back-by-blast", "label": "Blast knockback", "category": "evasive-falls", "description": "Body thrown backward off its feet by an unseen force",
    "promptHint": "the subject is thrown backward off both feet as if hit by a shockwave, arms and legs flung forward, back arching, and lands hard on the shoulders sliding to a stop", "term": "is thrown backward by a blast" },
  { "id": "stagger-backward", "label": "Stagger back", "category": "evasive-falls", "description": "Reels backward on unsteady feet",
    "promptHint": "the subject reels backward on unsteady legs, heels catching and torso swaying, one arm reaching behind for balance, and steadies only after three or four lurching steps", "term": "staggers backward" },
  { "id": "catch-on-wall", "label": "Catch on wall", "category": "evasive-falls", "description": "Lurches sideways and stops the fall against a wall",
    "promptHint": "the subject lurches off balance toward a wall and throws out a hand flat against it, arm locking to catch the body weight, shoulder braced as the feet find footing again", "term": "catches a fall against the wall" },
  { "id": "scramble-to-feet", "label": "Scramble to feet", "category": "evasive-falls", "description": "Pushes up from the ground and gets back upright",
    "promptHint": "the subject pushes up from the ground onto hands and one knee, drives through the front foot to stand, and finds balance with a half-step as the body straightens", "term": "scrambles back to their feet" },
  { "id": "scramble-backward", "label": "Scramble backward", "category": "evasive-falls", "description": "Crab-crawls away on hands and heels from the ground",
    "promptHint": "the subject scrambles backward from the ground on hands and heels in a crab-crawl, pelvis lifting and dropping with each push, eyes locked on the threat as the distance opens", "term": "scrambles backward on hands and heels" },
  { "id": "brace-for-impact", "label": "Brace for impact", "category": "evasive-falls", "description": "Plants the feet and tenses the whole body",
    "promptHint": "the subject plants both feet wide, drops the weight low, tucks the chin and raises both forearms across the face and chest, every muscle tensing against an incoming impact", "term": "braces for impact" },
  { "id": "cower-and-cover-head", "label": "Cower", "category": "evasive-falls", "description": "Shrinks down with both arms wrapped over the head",
    "promptHint": "the subject shrinks down into a crouch, back rounding and both arms wrapping over the head with elbows tucked in, face turned down and away from the threat", "term": "cowers covering the head" },
  { "id": "freeze-in-place", "label": "Freeze in place", "category": "evasive-falls", "description": "Stops dead mid-motion and holds completely still",
    "promptHint": "the subject stops dead mid-motion, weight caught between steps, body locking rigid with the breath held and only the eyes moving as the stillness holds", "term": "freezes in place" },
  { "id": "recoil-from-heat", "label": "Recoil from heat", "category": "evasive-falls", "description": "Turns away with a raised arm shielding the face",
    "promptHint": "the subject recoils, twisting the torso away and throwing one forearm across the face as if against searing heat, taking two steps back with the eyes narrowed and the head turned", "term": "recoils from searing heat" },
  { "id": "snatch-hand-back", "label": "Snatch hand back", "category": "evasive-falls", "description": "Yanks the hand away from something hot or sharp",
    "promptHint": "the subject reaches toward something and yanks the hand back the instant it makes contact, cradling the fingers against the chest and taking a half step away", "term": "snatches the hand back" },
  { "id": "shield-eyes", "label": "Shield eyes", "category": "evasive-falls", "description": "Raises a hand against a sudden glare",
    "promptHint": "the subject squints and raises one hand flat above the brow as if against a sudden glare, head turning slightly aside and shoulders lifting, and lowers the hand once the eyes adjust", "term": "shields the eyes from glare" },
  { "id": "flinch-from-loud-noise", "label": "Flinch from noise", "category": "evasive-falls", "description": "Claps both hands over the ears and hunches down",
    "promptHint": "the subject claps both hands over the ears and hunches the shoulders up to the jaw, face screwing tight and the head ducking as if against a deafening noise", "term": "flinches from a deafening noise" },
  { "id": "leap-back-from-edge", "label": "Leap back from edge", "category": "evasive-falls", "description": "Jumps back from a drop with arms windmilling",
    "promptHint": "the subject teeters at the lip of a drop with toes over the edge and throws the weight backward, arms windmilling, landing two steps back from the brink with the chest heaving", "term": "leaps back from an edge" },
  { "id": "back-away-hands-up", "label": "Hands-up retreat", "category": "evasive-falls", "description": "Retreats step by step with open palms raised",
    "promptHint": "the subject raises both open palms to shoulder height and retreats one step at a time, eyes fixed ahead, weight staying on the back foot with each step", "term": "backs away with hands raised" },
  { "id": "walk-into-glass-door", "label": "Walk into glass door", "category": "evasive-falls", "description": "Strides into an unseen pane and bounces off it",
    "promptHint": "the subject strides forward and stops dead as the face and chest hit an unseen pane of glass, the head snapping back, one hand rising to the nose as the body rebounds a step", "term": "walks face-first into a glass door" },
  { "id": "peek-through-fingers", "label": "Peek through fingers", "category": "evasive-falls", "description": "Covers the eyes, then parts the fingers to look",
    "promptHint": "the subject claps both hands over the eyes and hunches the shoulders, then parts two fingers of one hand to peek through the gap before snapping them shut again", "term": "peeks through the fingers" },
  { "id": "brace-back-against-door", "label": "Brace back against door", "category": "evasive-falls", "description": "Slams the back to a door and digs the heels in",
    "promptHint": "the subject spins and slams the back flat against a door, both palms spread on it and heels digging into the floor, knees bent and shoulders driving into the door as if holding it shut", "term": "braces back against the door" },
  { "id": "windmill-arms-losing-balance", "label": "Windmill arms", "category": "evasive-falls", "description": "Teeters on the toes and circles the arms to stay up",
    "promptHint": "the subject teeters forward onto the toes, both arms whirling in big backward circles and the pelvis pushing back, holding the wobble on the balls of the feet before settling back onto the heels", "term": "windmills the arms to keep balance" },
  { "id": "trip-on-stairs", "label": "Trip on stairs", "category": "evasive-falls", "description": "Clips a step going up and lands on the hands",
    "promptHint": "the subject clips a toe on a stair while climbing, pitches forward onto the steps with both hands slapping the treads above, knees banging down, then pushes back up and climbs on", "term": "trips going up the stairs" },
  { "id": "tip-over-in-chair", "label": "Tip over in chair", "category": "evasive-falls", "description": "Leans back too far and goes over with the chair",
    "promptHint": "the subject leans back in a chair until it passes the tipping point, arms shooting out and feet lifting off the floor as the chair goes over backward and the subject lands on the back with legs in the air", "term": "tips over backward in a chair" },
  { "id": "fall-into-pool", "label": "Fall into pool", "category": "evasive-falls", "description": "Loses footing at the edge and drops into the water",
    "promptHint": "the subject loses footing at the edge of the water and topples in fully clothed, arms flailing, hitting the surface side-on with a splash and surfacing a moment later with hair and clothes streaming", "term": "falls into the water fully clothed" },
  { "id": "pulled-under-water", "label": "Pulled under water", "category": "evasive-falls", "description": "Jerked down beneath the surface, arms grabbing up",
    "promptHint": "the subject is treading water when the body jerks downward as if yanked from below, both arms shooting up and clawing at the surface, head going under and the fingertips vanishing last", "term": "is pulled under the water" },
  { "id": "clutch-hat-in-wind", "label": "Clutch hat in wind", "category": "evasive-falls", "description": "Grabs a hat to the head and leans into a gust",
    "promptHint": "the subject slaps one hand down onto the crown of a hat and holds it there, leaning the body forward and squinting as if into a hard gust, the free hand pinning a flapping coat", "term": "clutches a hat against the wind" },
  { "id": "run-shielding-from-rain", "label": "Run shielding from rain", "category": "evasive-falls", "description": "Hurries with a jacket held over the head",
    "promptHint": "the subject pulls a jacket up over the head with both hands, shoulders hunched and elbows tucked, and hurries forward in short steps as if dodging a downpour", "term": "runs with a jacket held overhead" },
]
