import type { CharacterMotion } from "./types.js"

/** Everyday Actions — 91 entries. Category id `everyday-actions`. */
export const EVERYDAY_ACTIONS_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "take-a-sip", label: "Take a Sip", category: "everyday-actions", description: "Lifts a cup to the lips, sips, lowers it",
    promptHint: "the subject lifts a cup from waist height to the lips with one hand, tips it and sips, then lowers it back down and swallows",
    term: "takes a sip from a cup" },
  { id: "drink-from-bottle", label: "Drink from Bottle", category: "everyday-actions", description: "Tips a bottle up, head back, drinks",
    promptHint: "the subject raises a bottle to the mouth, tilts the head back as the bottle tips up and drinks, then lowers it and wipes the mouth with the back of the hand",
    term: "drinks from a bottle" },
  { id: "cradle-mug-and-sip", label: "Cradle Mug and Sip", category: "everyday-actions", description: "Cradles a warm mug in both hands and sips",
    promptHint: "the subject cradles a mug in both hands, lifts it to the lips with elbows tucked in, takes a sip, then lowers the mug to chest height still held in both hands",
    term: "sips coffee cradling the mug in both hands" },
  { id: "take-a-bite", label: "Take a Bite", category: "everyday-actions", description: "Bites into food, lowers it, chews and swallows",
    promptHint: "the subject raises a piece of food to the mouth, bites into it, lowers the hand and chews with the jaw working, then swallows",
    term: "takes a bite and chews" },
  { id: "put-on-jacket", label: "Put On Jacket", category: "everyday-actions", description: "Threads both arms in, settles the collar",
    promptHint: "the subject slides one arm into a jacket sleeve, swings the jacket around the back, threads the other arm through, then tugs the collar and shoulders into place",
    term: "shrugs on a jacket" },
  { id: "take-off-jacket", label: "Take Off Jacket", category: "everyday-actions", description: "Shrugs the jacket off one shoulder at a time",
    promptHint: "the subject unfastens the jacket, shrugs it off one shoulder then the other, pulls both arms free and lets it hang from one hand",
    term: "shrugs off a jacket" },
  { id: "put-on-sunglasses", label: "Put On Sunglasses", category: "everyday-actions", description: "Unfolds sunglasses and settles them on",
    promptHint: "the subject unfolds a pair of sunglasses with one hand, raises them to the face and settles them onto the nose, then lets the hand drop",
    term: "puts on sunglasses" },
  { id: "take-off-sunglasses", label: "Take Off Sunglasses", category: "everyday-actions", description: "Pulls sunglasses off and folds them",
    promptHint: "the subject reaches up with one hand, pinches the sunglasses by the frame and pulls them off the face, folding them as the hand lowers",
    term: "takes off sunglasses" },
  { id: "put-on-glasses", label: "Put On Glasses", category: "everyday-actions", description: "Hooks eyeglasses over the ears, pushes them up",
    promptHint: "the subject unfolds a pair of eyeglasses, raises them to the face with one hand and hooks the arms over the ears, then pushes them up the nose with one finger",
    term: "puts on eyeglasses" },
  { id: "take-off-glasses", label: "Take Off Glasses", category: "everyday-actions", description: "Lifts eyeglasses off the face and folds them",
    promptHint: "the subject reaches up with one hand, pinches the eyeglasses by one arm and lifts them off the face, folds them and lowers the hand",
    term: "takes off eyeglasses" },
  { id: "put-on-hat", label: "Put On Hat", category: "everyday-actions", description: "Settles a hat on and adjusts the brim",
    promptHint: "the subject lifts a hat with both hands, settles it onto the head, then adjusts the brim with one hand until it sits straight",
    term: "puts on a hat" },
  { id: "take-off-hat", label: "Take Off Hat", category: "everyday-actions", description: "Lifts the hat clear and lowers it to the chest",
    promptHint: "the subject grips the hat by the crown or brim, lifts it clear of the head and lowers it to chest height as the hair settles",
    term: "takes off a hat" },
  { id: "pull-up-hood", label: "Pull Up Hood", category: "everyday-actions", description: "Pulls the hood up and forward over the head",
    promptHint: "the subject reaches back with both hands, grabs the edge of the hood and pulls it up and forward over the head, then tugs the front edges down",
    term: "pulls the hood up" },
  { id: "wrap-scarf", label: "Wrap Scarf", category: "everyday-actions", description: "Loops a scarf around the neck, tucks the ends",
    promptHint: "the subject drapes a scarf around the back of the neck, wraps one end across the front and around, then tucks both tails into the coat collar",
    term: "wraps a scarf around the neck" },
  { id: "loosen-tie", label: "Loosen Tie", category: "everyday-actions", description: "Tugs the knot down and pops the top button",
    promptHint: "the subject hooks one finger into the tie knot, tugs it down and to the side, then pops the top shirt button open and lets the arm drop",
    term: "loosens the tie" },
  { id: "open-door", label: "Open Door", category: "everyday-actions", description: "Turns the handle, opens, steps through",
    promptHint: "the subject reaches for a door handle, turns it and pulls or pushes the door open, then steps through the doorway",
    term: "opens a door and steps through" },
  { id: "close-door", label: "Close Door", category: "everyday-actions", description: "Turns back and swings the door shut",
    promptHint: "the subject turns back to the open door, swings it closed and holds the handle until it clicks shut",
    term: "turns back and shuts the door" },
  { id: "knock-on-door", label: "Knock on Door", category: "everyday-actions", description: "Raps the knuckles on a door and waits",
    promptHint: "the subject raises one hand in a loose fist and raps the knuckles against a door two or three times, then drops the hand and waits",
    term: "knocks on a door" },
  { id: "pound-on-door", label: "Pound on Door", category: "everyday-actions", description: "Hammers a fist on the door with body weight",
    promptHint: "the subject hammers the heel of a fist against a door with the whole arm, leaning the body weight into each blow, then slaps the palm flat against it",
    term: "pounds on the door with a fist" },
  { id: "rattle-locked-door-handle", label: "Rattle Locked Door Handle", category: "everyday-actions", description: "Jerks the handle, shoulders the door, steps back",
    promptHint: "the subject grabs a door handle, jerks it up and down and shoves one shoulder against the door, then steps back from it",
    term: "rattles a locked door handle" },
  { id: "unlock-door-with-keys", label: "Unlock Door with Keys", category: "everyday-actions", description: "Selects a key, turns the lock, pushes in",
    promptHint: "the subject fishes keys from a pocket, selects one, slides it into the lock, turns it and pushes the door open",
    term: "unlocks a door with keys" },
  { id: "press-palm-to-window", label: "Press Palm to Window", category: "everyday-actions", description: "Presses a palm flat to the glass, head tilts",
    promptHint: "the subject steps up to a window, raises one hand and presses the palm flat against the glass, holding it there as the head tilts forward",
    term: "presses a palm to the window" },
  { id: "draw-back-curtains", label: "Draw Back Curtains", category: "everyday-actions", description: "Pulls the curtains apart to the sides",
    promptHint: "the subject grasps the edges of a pair of curtains with both hands and draws them apart to the sides, then lets go and stands facing the window",
    term: "draws the curtains open" },
  { id: "pull-back-shower-curtain", label: "Pull Back Shower Curtain", category: "everyday-actions", description: "Yanks the shower curtain aside in one sweep",
    promptHint: "the subject grips the edge of a shower curtain with one hand and yanks it aside in a single sweep, the other arm held back at the side",
    term: "pulls back the shower curtain" },
  { id: "wipe-steam-off-mirror", label: "Wipe Steam Off Mirror", category: "everyday-actions", description: "Clears a patch of fogged mirror with the palm",
    promptHint: "the subject raises one hand and wipes the palm across a fogged mirror in a broad arc, clearing a patch, then leans in to look at the reflection",
    term: "wipes steam off the mirror" },
  { id: "check-reflection-in-mirror", label: "Check Reflection in Mirror", category: "everyday-actions", description: "Leans into the mirror, turns the head, adjusts",
    promptHint: "the subject steps up to a mirror, leans in toward the reflection, turns the head from side to side, then smooths the hair with one hand and straightens up",
    term: "checks reflection in a mirror" },
  { id: "pick-up-object", label: "Pick Up Object", category: "everyday-actions", description: "Bends down, grasps an object, straightens up",
    promptHint: "the subject bends at the knees and waist, reaches down with one hand to grasp an object, then straightens up lifting it to waist height",
    term: "bends down and picks up an object" },
  { id: "put-down-object", label: "Put Down Object", category: "everyday-actions", description: "Sets an object on a surface and lets go",
    promptHint: "the subject lowers an object held in one hand onto a nearby surface, sets it down with care, releases the grip and withdraws the hand",
    term: "sets an object down" },
  { id: "drop-object", label: "Drop Object", category: "everyday-actions", description: "Lets an object slip from the hand, watches it fall",
    promptHint: "the subject opens the hand and lets an object slip free, the eyes following it down until it hits the floor",
    term: "drops an object" },
  { id: "fumble-and-catch", label: "Fumble and Catch", category: "everyday-actions", description: "Juggles a slipping object, clutches it to the chest",
    promptHint: "the subject lets an object slip from the grip, juggles it between both hands as it bounces, then clutches it to the chest with both arms",
    term: "fumbles and catches an object" },
  { id: "throw-object-across-room", label: "Throw Object Across Room", category: "everyday-actions", description: "Snatches an object and hurls it, full follow-through",
    promptHint: "the subject snatches up an object, cocks the arm back and hurls it across the room, the torso twisting through the throw and the arm following through",
    term: "hurls an object across the room" },
  { id: "sweep-desk-clear", label: "Sweep Desk Clear", category: "everyday-actions", description: "Sweeps a forearm across the desk, everything falls",
    promptHint: "the subject plants one hand on the desk edge and sweeps the other forearm across the surface, sending everything on it tumbling off the far side",
    term: "sweeps everything off the desk" },
  { id: "carry-heavy-box", label: "Carry Heavy Box", category: "everyday-actions", description: "Squats, lifts a big box to the chest, walks",
    promptHint: "the subject squats beside a large box, wraps both arms under it and drives up through the legs to lift it against the chest, then walks forward leaning back against the weight",
    term: "lifts and carries a heavy box" },
  { id: "reach-for-high-shelf", label: "Reach for High Shelf", category: "everyday-actions", description: "Rises on tiptoes, stretches up, grabs an item",
    promptHint: "the subject rises onto the toes and stretches one arm straight up toward a high shelf, fingertips straining for an item, then grasps it and settles back onto the heels",
    term: "reaches up on tiptoes for a shelf" },
  { id: "open-box", label: "Open Box", category: "everyday-actions", description: "Lifts the lid off and looks inside",
    promptHint: "the subject grips the lid of a box with both hands, lifts it off and sets it aside, then leans forward to look inside",
    term: "opens a box and looks inside" },
  { id: "unwrap-gift", label: "Unwrap Gift", category: "everyday-actions", description: "Pulls the ribbon, tears the paper, lifts the lid",
    promptHint: "the subject tugs the ribbon loose on a wrapped gift, tears the paper away with both hands, and lifts the lid to reveal what is inside",
    term: "unwraps a gift" },
  { id: "pull-item-from-bag", label: "Pull Item from Bag", category: "everyday-actions", description: "Reaches into a bag and draws out an item",
    promptHint: "the subject opens a bag, reaches inside with one hand, draws out an item and raises it to chest height to look it over",
    term: "pulls an item from a bag" },
  { id: "open-letter", label: "Open Letter", category: "everyday-actions", description: "Tears an envelope open and reads the letter",
    promptHint: "the subject tears open an envelope, slides out a folded letter, unfolds it with both hands and reads, eyes tracking across the lines",
    term: "opens and reads a letter" },
  { id: "tear-paper-in-half", label: "Tear Paper in Half", category: "everyday-actions", description: "Rips a sheet down the middle, drops the pieces",
    promptHint: "the subject grips a sheet of paper at the top with both hands and rips it down the middle, then tears the halves again and lets the pieces drop",
    term: "tears a paper in half" },
  { id: "pull-phone-from-pocket", label: "Pull Phone from Pocket", category: "everyday-actions", description: "Draws a phone out and looks down at the screen",
    promptHint: "the subject reaches into a pocket, draws out a phone, turns it face up in the hand and lowers the gaze to the screen",
    term: "pulls a phone from a pocket" },
  { id: "answer-phone", label: "Answer Phone", category: "everyday-actions", description: "Pulls out a ringing phone and raises it to the ear",
    promptHint: "the subject pulls a ringing phone from a pocket, glances at the screen, swipes to answer and raises it to the ear, beginning to speak",
    term: "answers a phone call" },
  { id: "hang-up-phone", label: "Hang Up Phone", category: "everyday-actions", description: "Lowers the phone, ends the call, pockets it",
    promptHint: "the subject lowers the phone from the ear, taps the screen to end the call, then slides it back into a pocket",
    term: "hangs up the phone" },
  { id: "look-up-from-phone", label: "Look Up from Phone", category: "everyday-actions", description: "Glances at the phone, then lifts the head",
    promptHint: "the subject glances down at a phone held in one hand, thumbs the screen, then lifts the head and looks up and ahead",
    term: "checks phone and looks up" },
  { id: "scroll-on-phone", label: "Scroll on Phone", category: "everyday-actions", description: "Thumb flicks the screen in repeated scrolls",
    promptHint: "the subject flicks the thumb upward across the screen of a phone held in one hand at chest height, scrolling again and again, eyes tracking the feed",
    term: "scrolls on phone with thumb" },
  { id: "take-a-selfie", label: "Take a Selfie", category: "everyday-actions", description: "Arm out, poses, taps, lowers to review",
    promptHint: "the subject raises a phone at arm's length with the screen turned toward the face, tilts the head and poses, taps the screen, then lowers the phone to review the shot",
    term: "takes a selfie" },
  { id: "take-a-photo", label: "Take a Photo", category: "everyday-actions", description: "Raises a phone, frames, presses the shutter",
    promptHint: "the subject raises a phone to eye level with both hands, frames a shot ahead, holds still and taps the shutter, then lowers it",
    term: "takes a photo" },
  { id: "tap-to-pay", label: "Tap to Pay", category: "everyday-actions", description: "Taps a card or phone on a payment terminal",
    promptHint: "the subject holds a card or phone out in one hand and taps it flat against a payment terminal, then pulls it back and slips it into a pocket",
    term: "taps a card to pay" },
  { id: "type-on-laptop", label: "Type on Laptop", category: "everyday-actions", description: "Opens the lid and types, eyes on keys and screen",
    promptHint: "the subject opens a laptop lid, places both hands on the keyboard and types, fingers moving across the keys and eyes shifting between the keys and the screen",
    term: "opens laptop and types" },
  { id: "write-in-notebook", label: "Write in Notebook", category: "everyday-actions", description: "Opens a notebook, uncaps a pen, writes a line",
    promptHint: "the subject flips a notebook open, uncaps a pen and writes a line across the page with the hand moving left to right, then pauses to reread it",
    term: "writes a line in a notebook" },
  { id: "write-on-whiteboard", label: "Write on Whiteboard", category: "everyday-actions", description: "Writes a line across a whiteboard, turns to the room",
    promptHint: "the subject uncaps a marker, reaches up to a whiteboard and writes across it in a line from left to right, then steps aside and turns to face the room",
    term: "writes on a whiteboard" },
  { id: "sign-document", label: "Sign Document", category: "everyday-actions", description: "Leans over a page and signs with a flourish",
    promptHint: "the subject picks up a pen, leans over a document and signs along the line with a flourish, then sets the pen down and straightens up",
    term: "signs a document" },
  { id: "turn-a-page", label: "Turn a Page", category: "everyday-actions", description: "Sweeps a page across and smooths it flat",
    promptHint: "the subject pinches the corner of a page with the fingertips, lifts and sweeps it across from right to left, then smooths it flat with the palm",
    term: "turns a page" },
  { id: "tie-shoelaces", label: "Tie Shoelaces", category: "everyday-actions", description: "Crouches, loops and knots the laces, stands",
    promptHint: "the subject crouches or props one foot up, pulls the laces taut, loops and knots them with both hands, then stands back up",
    term: "ties shoelaces" },
  { id: "kick-off-shoes", label: "Kick Off Shoes", category: "everyday-actions", description: "Steps out of each shoe heel-first",
    promptHint: "the subject presses the heel of one shoe down with the toe of the other, steps out of it, then repeats with the second foot and nudges both shoes aside",
    term: "kicks off shoes" },
  { id: "sling-bag-over-shoulder", label: "Sling Bag Over Shoulder", category: "everyday-actions", description: "Swings a bag strap up over one shoulder",
    promptHint: "the subject picks up a bag by the strap, swings it up and over one shoulder, and settles the strap in place with a tug",
    term: "slings a bag over one shoulder" },
  { id: "put-on-headphones", label: "Put On Headphones", category: "everyday-actions", description: "Settles the cups over both ears",
    promptHint: "the subject lifts a pair of headphones from around the neck, settles the cups over both ears, and adjusts the band with both hands",
    term: "puts on headphones" },
  { id: "open-umbrella", label: "Open Umbrella", category: "everyday-actions", description: "Pushes the canopy open and rests it on a shoulder",
    promptHint: "the subject raises a closed umbrella, presses the release and pushes the canopy open overhead, then settles the handle against one shoulder",
    term: "opens an umbrella" },
  { id: "snap-on-medical-gloves", label: "Snap On Medical Gloves", category: "everyday-actions", description: "Pulls each glove on and snaps the cuff at the wrist",
    promptHint: "the subject pulls a disposable glove over one hand, tugs the cuff and lets it snap against the wrist, then repeats with the other hand and flexes both",
    term: "snaps on medical gloves" },
  { id: "brush-hair", label: "Brush Hair", category: "everyday-actions", description: "Long brush strokes from crown to ends",
    promptHint: "the subject draws a hairbrush from the crown down through the hair in long strokes, the free hand smoothing each section as it falls",
    term: "brushes hair in long strokes" },
  { id: "tie-hair-up", label: "Tie Hair Up", category: "everyday-actions", description: "Gathers the hair back and loops a tie around it",
    promptHint: "the subject gathers the hair back with both hands, holds it in one fist at the back of the head and loops a hair tie around it, then drops both hands",
    term: "ties hair up in a ponytail" },
  { id: "let-hair-down", label: "Let Hair Down", category: "everyday-actions", description: "Pulls the hair tie free and shakes hair loose",
    promptHint: "the subject reaches back with one hand, pulls the hair tie free and shakes the head once so the hair falls loose around the shoulders",
    term: "pulls the hair tie and shakes hair loose" },
  { id: "apply-lipstick", label: "Apply Lipstick", category: "everyday-actions", description: "Glides lipstick across the lips and presses them",
    promptHint: "the subject uncaps a lipstick, holds the mouth still and glides the color across the upper lip then the lower, then presses the lips together",
    term: "applies lipstick" },
  { id: "apply-skincare", label: "Apply Skincare", category: "everyday-actions", description: "Dabs cream on the cheeks and rubs it in",
    promptHint: "the subject dabs cream from the fingertips onto both cheeks, then rubs it in with upward circles of the fingers until it disappears into the skin",
    term: "rubs cream into the cheeks" },
  { id: "spray-perfume-on-wrist", label: "Spray Perfume on Wrist", category: "everyday-actions", description: "Sprays the wrist, presses both wrists together",
    promptHint: "the subject raises a perfume bottle, sprays once onto the inside of the opposite wrist, then presses both wrists together and rubs them",
    term: "sprays perfume on the wrist" },
  { id: "lift-and-sniff", label: "Lift and Sniff", category: "everyday-actions", description: "Raises an item to the nose and inhales",
    promptHint: "the subject raises an item in one hand to just under the nose, closes the eyes and inhales through the nose, then lowers it and opens the eyes",
    term: "lifts to the nose and sniffs" },
  { id: "brush-teeth", label: "Brush Teeth", category: "everyday-actions", description: "Scrubs the teeth, leans forward and spits",
    promptHint: "the subject raises a toothbrush to the mouth and scrubs it back and forth across the teeth, the free hand resting on the sink edge, then leans forward and spits",
    term: "brushes teeth" },
  { id: "splash-water-on-face", label: "Splash Water on Face", category: "everyday-actions", description: "Cups water in both hands and splashes the face",
    promptHint: "the subject bends over a sink, cups water in both hands and splashes it up onto the face, then straightens up and drags both palms down the cheeks",
    term: "splashes water on the face" },
  { id: "light-cigarette", label: "Light Cigarette", category: "everyday-actions", description: "Cups a lighter, lights up, draws and exhales",
    promptHint: "the subject places a cigarette between the lips, cups one hand around a lighter, flicks it and touches the flame to the tip, then draws in and exhales",
    term: "lights a cigarette" },
  { id: "pour-a-drink", label: "Pour a Drink", category: "everyday-actions", description: "Tilts a bottle over a glass and pours",
    promptHint: "the subject lifts a bottle by the neck, tilts it over a glass and pours until the glass is part full, then rights the bottle and sets it down",
    term: "pours a drink into a glass" },
  { id: "raise-glass-to-toast", label: "Raise Glass to Toast", category: "everyday-actions", description: "Lifts a glass forward in a toast, then sips",
    promptHint: "the subject lifts a glass from the table to shoulder height, extends it forward in a toast with a small nod, then draws it back for a sip",
    term: "raises a glass in a toast" },
  { id: "pop-and-spray-champagne", label: "Pop and Spray Champagne", category: "everyday-actions", description: "Shakes the bottle, pops the cork, sprays foam",
    promptHint: "the subject shakes a champagne bottle with both hands, thumbs the cork out so it pops free, then aims the neck and sprays the foam in a wide arc",
    term: "pops and sprays champagne" },
  { id: "do-a-spit-take", label: "Do a Spit Take", category: "everyday-actions", description: "Freezes mid-sip and sprays the drink out",
    promptHint: "the subject takes a mouthful from a cup, freezes mid-swallow with the eyes widening, then sprays the drink out of the mouth in a burst and coughs, wiping the chin",
    term: "does a spit take" },
  { id: "blow-out-candle", label: "Blow Out Candle", category: "everyday-actions", description: "Leans in, draws a breath, blows out the flame",
    promptHint: "the subject leans toward a candle, draws in a breath with the cheeks filling, and blows out the flame, then straightens up",
    term: "blows out a candle" },
  { id: "cut-cake", label: "Cut Cake", category: "everyday-actions", description: "Presses a knife through a cake, lifts a slice",
    promptHint: "the subject grips a knife in one hand, presses it down through a cake from the center outward, then lifts a slice onto a plate with the flat of the blade",
    term: "cuts a slice of cake" },
  { id: "toss-bouquet", label: "Toss Bouquet", category: "everyday-actions", description: "Turns away and tosses the bouquet over a shoulder",
    promptHint: "the subject turns away, holds a bouquet in both hands at chest height, then swings it up and over one shoulder in an underhand toss and looks back",
    term: "tosses the bouquet over the shoulder" },
  { id: "lick-ice-cream", label: "Lick Ice Cream", category: "everyday-actions", description: "Turns the cone, licks the rim, bites the top",
    promptHint: "the subject raises an ice cream cone, turns it in the hand and licks around the rim where it drips, then takes a bite from the top",
    term: "licks an ice cream cone" },
  { id: "stir-a-pot", label: "Stir a Pot", category: "everyday-actions", description: "Stirs in circles, then lifts the spoon to taste",
    promptHint: "the subject stirs a pot in circles with a spoon in one hand while the other hand steadies the pot handle, then lifts the spoon to the lips to taste",
    term: "stirs a pot on the stove" },
  { id: "taste-from-spoon", label: "Taste from Spoon", category: "everyday-actions", description: "Dips a spoon, blows on it, tastes, nods",
    promptHint: "the subject dips a spoon into a dish, raises it to the mouth, blows across it and tastes, then nods and lowers the spoon",
    term: "tastes from a spoon" },
  { id: "chop-vegetables", label: "Chop Vegetables", category: "everyday-actions", description: "Rocks a knife through vegetables on a board",
    promptHint: "the subject steadies a vegetable on a cutting board with curled fingertips and rocks a knife through it in even strokes, sweeping the pieces aside",
    term: "chops vegetables on a board" },
  { id: "toss-food-in-pan", label: "Toss Food in Pan", category: "everyday-actions", description: "Flicks the pan so the food flips and lands back",
    promptHint: "the subject grips a pan handle with one hand and jerks it forward and up so the food flips into the air, then catches it back in the pan",
    term: "tosses food in a pan" },
  { id: "sprinkle-salt-flourish", label: "Sprinkle Salt Flourish", category: "everyday-actions", description: "Arm raised high, salt trickles from the fingertips",
    promptHint: "the subject pinches salt between the fingertips, raises the arm high with the wrist cocked back, then lets the grains trickle down from the fingertips over the dish",
    term: "sprinkles salt with a flourish" },
  { id: "open-fridge", label: "Open Fridge", category: "everyday-actions", description: "Opens the fridge, takes something, shuts it",
    promptHint: "the subject pulls a refrigerator door open, leans in to look, takes something out with one hand and swings the door shut with the hip",
    term: "opens the fridge and takes something out" },
  { id: "water-plants", label: "Water Plants", category: "everyday-actions", description: "Tips a watering can over each plant",
    promptHint: "the subject lifts a watering can with one hand, tips the spout over a plant and pours in a steady stream, then moves on to the next pot",
    term: "waters plants with a watering can" },
  { id: "cradle-and-rock-baby", label: "Cradle and Rock Baby", category: "everyday-actions", description: "Holds a baby to the chest and sways side to side",
    promptHint: "the subject holds a baby against the chest with both arms, one hand supporting the head, and sways from foot to foot, rocking the arms while looking down at the baby",
    term: "cradles and rocks a baby" },
  { id: "slap-alarm-clock", label: "Slap Alarm Clock", category: "everyday-actions", description: "Flings an arm out and slaps the alarm off",
    promptHint: "the subject flings one arm out from under the covers and slaps the palm down on an alarm clock, then drags the arm back and buries the face in the pillow",
    term: "slaps the alarm clock" },
  { id: "pull-covers-over-head", label: "Pull Covers Over Head", category: "everyday-actions", description: "Yanks the covers up over the head and curls up",
    promptHint: "the subject grabs the edge of the bed covers with both hands and yanks them up over the head, curling onto one side underneath them",
    term: "pulls the covers over the head" },
  { id: "put-on-seatbelt", label: "Put On Seatbelt", category: "everyday-actions", description: "Pulls the belt across and clicks the buckle",
    promptHint: "the subject reaches over one shoulder to grab the seatbelt, pulls it across the chest and clicks the buckle in at the hip, then settles back",
    term: "buckles a seatbelt" },
  { id: "grab-keys-and-leave", label: "Grab Keys & Leave", category: "everyday-actions", description: "Scoops keys in passing and walks out",
    promptHint: "the subject scoops keys off a surface in passing, pockets them, and walks out through a doorway without breaking stride",
    term: "grabs keys and heads out" },
  { id: "flip-a-coin", label: "Flip a Coin", category: "everyday-actions", description: "Flicks a coin up, catches it, slaps it on the hand",
    promptHint: "the subject balances a coin on the thumb, flicks it spinning into the air, catches it and slaps it onto the back of the other hand, then lifts the hand to look",
    term: "flips a coin" },
  { id: "shuffle-cards", label: "Shuffle Cards", category: "everyday-actions", description: "Splits the deck, riffles the halves, squares it",
    promptHint: "the subject splits a deck of cards in two, bends the halves and riffles them together with the thumbs, then squares the deck with both hands",
    term: "shuffles a deck of cards" },
  { id: "sweep-flashlight", label: "Sweep Flashlight", category: "everyday-actions", description: "Sweeps a flashlight in an arc, head following",
    promptHint: "the subject raises a flashlight to shoulder height and sweeps it in an arc from one side to the other, the head turning to follow it",
    term: "sweeps a flashlight from side to side" },
]
