import type { CharacterMotion } from "./types.js"

/** Face & Expression — 59 entries. Category id `face-expression`. */
export const FACE_EXPRESSION_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "break-into-smile", label: "Break Into Smile", category: "face-expression", description: "Neutral face lifts into a full warm smile",
    promptHint: "the subject breaks into a smile, the corners of the mouth lifting from a neutral line into a full warm smile as the cheeks rise and the eyes crinkle at the outer corners",
    term: "breaks into a warm smile" },
  { id: "let-smile-creep-in", label: "Creeping Smile", category: "face-expression", description: "A smile dawns one corner at a time",
    promptHint: "the subject lets a smile creep in, one corner of the mouth twitching up first, the other side catching up until the whole face has eased into a knowing smile",
    term: "lets a smile creep in" },
  { id: "widen-into-grin", label: "Grin Widens", category: "face-expression", description: "Small smile opens into a broad toothy grin",
    promptHint: "the subject widens a small closed-lip smile into a broad grin, the lips parting to show teeth, cheeks bunching upward and the eyes narrowing with delight",
    term: "widens smile into a toothy grin" },
  { id: "let-smile-fade", label: "Smile Fades", category: "face-expression", description: "Smile drains away to a flat still face",
    promptHint: "the subject lets the smile fade, the corners of the mouth dropping back to a flat line as the brightness leaves the eyes and the face goes still and guarded",
    term: "lets the smile fade" },
  { id: "force-a-smile", label: "Forced Smile", category: "face-expression", description: "Stiff polite smile that never reaches the eyes",
    promptHint: "the subject forces a smile, the mouth stretching wide and tight while the eyes stay flat and unmoving, the expression holding stiffly for a beat before dropping away",
    term: "forces a stiff smile" },
  { id: "smirk-knowingly", label: "Smirk", category: "face-expression", description: "One corner of the mouth curls up, eyes narrow",
    promptHint: "the subject smirks, one corner of the mouth curling upward while the other side stays put, the eyes narrowing knowingly and the head tilting a fraction to that side",
    term: "smirks, one corner of the mouth curling" },
  { id: "burst-out-laughing", label: "Burst Out Laughing", category: "face-expression", description: "Sudden full laugh, head back, shoulders shaking",
    promptHint: "the subject bursts out laughing, the head tipping back and the mouth opening wide, shoulders shaking with each breath before the laugh settles into a lingering grin",
    term: "bursts out laughing" },
  { id: "giggle-lightly", label: "Giggle", category: "face-expression", description: "Light bubbling laugh, shoulders bobbing",
    promptHint: "the subject giggles, the shoulders bobbing in short bursts and the lips pressing together then breaking open in quick light laughs, the gaze darting away and back",
    term: "giggles, shoulders bobbing" },
  { id: "chuckle-quietly", label: "Chuckle", category: "face-expression", description: "Single quiet laugh through the nose, head dips",
    promptHint: "the subject chuckles quietly, a single exhale through the nose as the head dips once and the mouth pulls into a lopsided smile before the face settles again",
    term: "chuckles quietly, head dipping once" },
  { id: "tears-well-up", label: "Tears Well Up", category: "face-expression", description: "Eyes glisten and fill, a single tear spills",
    promptHint: "the subject fights back tears, the eyes glistening and welling up as the chin trembles and the lips press together, until a single tear spills over and tracks down one cheek",
    term: "wells up, a single tear spilling" },
  { id: "break-down-sobbing", label: "Break Down Sobbing", category: "face-expression", description: "Face crumples into heaving sobs",
    promptHint: "the subject breaks down sobbing, the face crumpling and the mouth pulling downward, shoulders heaving with each ragged breath as the head bows and tears stream",
    term: "breaks down sobbing" },
  { id: "gasp-in-shock", label: "Gasp", category: "face-expression", description: "Sharp intake of breath, mouth and eyes fly open",
    promptHint: "the subject gasps, the mouth dropping open and the eyes flying wide as the chest lifts on a sharp intake of breath, the whole body freezing for a beat before it releases",
    term: "gasps, mouth and eyes flying open" },
  { id: "drop-jaw-in-astonishment", label: "Jaw Drop", category: "face-expression", description: "Jaw falls slack in open-mouthed astonishment",
    promptHint: "the subject gapes in astonishment, the jaw dropping open and the mouth going slack as the eyes widen and the brows lift, the head pulling back a fraction and freezing there",
    term: "gapes, jaw dropping in astonishment" },
  { id: "register-dawning-realization", label: "Dawning Realization", category: "face-expression", description: "Stillness, then eyes widen as it sinks in",
    promptHint: "the subject goes still as understanding lands, the eyes widening and the brows lifting, the lips parting slightly before the jaw sets with new resolve",
    term: "registers a dawning realization" },
  { id: "startle-then-relax", label: "Surprise to Relief", category: "face-expression", description: "Jolt of surprise melting into relieved release",
    promptHint: "the subject startles in surprise, the eyes widening and the mouth opening, before the shoulders drop and the breath leaves in a relieved laugh as the whole face softens",
    term: "startles, relaxing into relief" },
  { id: "wink-one-eye", label: "Wink", category: "face-expression", description: "One eye closes in a quick squeeze and reopens",
    promptHint: "the subject winks, one eye closing in a quick deliberate squeeze while the other stays open, the mouth tugging up on the same side before the eye opens again",
    term: "gives a quick wink" },
  { id: "roll-eyes-exasperated", label: "Eye Roll", category: "face-expression", description: "Gaze sweeps up and over in exasperation",
    promptHint: "the subject rolls the eyes, the gaze sweeping upward and across to one side with a small tilt of the head and a huff of breath, then settling back forward unimpressed",
    term: "rolls eyes in exasperation" },
  { id: "give-slow-blink", label: "Slow Blink", category: "face-expression", description: "Lids lower fully, hold a beat, then lift",
    promptHint: "the subject gives a long deliberate blink, the lids lowering until fully closed and resting there for a beat, then lifting again with the gaze settling back where it was",
    term: "gives a slow deliberate blink" },
  { id: "let-eyes-drift-closed", label: "Eyes Drift Closed", category: "face-expression", description: "Lids lower until shut, face settles into rest",
    promptHint: "the subject lets both eyes drift closed, the lids lowering until fully shut as the face goes still and the brow smooths, the head settling as if into rest",
    term: "lets the eyes drift closed" },
  { id: "flutter-eyes-open", label: "Eyes Flutter Open", category: "face-expression", description: "Closed eyes flicker open and find focus",
    promptHint: "the subject flutters the eyes open from closed, the lids flickering a few times before lifting fully, the gaze unfocused at first and then sharpening onto a point ahead",
    term: "flutters eyes open and focuses" },
  { id: "stare-blankly-snap-back", label: "Blank Stare & Refocus", category: "face-expression", description: "Vacant unfocused stare, then a jolt back to alert",
    promptHint: "the subject stares blankly into the middle distance, the eyes unfocused and the face slack, then blinks and snaps back to attention as focus returns sharply to the eyes",
    term: "stares blankly, snaps back to focus" },
  { id: "nod-in-agreement", label: "Nod", category: "face-expression", description: "Chin dips and lifts in one or two clear beats",
    promptHint: "the subject nods, the chin dipping down and lifting back up in one or two clear beats while the eyes hold steady in agreement, the head settling level again",
    term: "nods in agreement" },
  { id: "shake-head-no", label: "Shake Head No", category: "face-expression", description: "Head swings side to side, mouth tightening",
    promptHint: "the subject shakes the head no, turning it side to side in two or three short swings while the mouth tightens, then bringing it back to center and holding",
    term: "shakes head no" },
  { id: "raise-one-eyebrow", label: "Raise an Eyebrow", category: "face-expression", description: "One brow arches high in skeptical doubt",
    promptHint: "the subject raises one eyebrow, the brow arching high on that side while the other stays level, the head tilting slightly and the mouth pulling into a skeptical line",
    term: "raises one skeptical eyebrow" },
  { id: "narrow-eyes-suspiciously", label: "Narrow Eyes", category: "face-expression", description: "Lids lower to a squint of suspicion",
    promptHint: "the subject narrows the eyes in suspicion, the lids lowering to a squint and the head tilting a fraction as the mouth tightens, holding the appraising look",
    term: "narrows eyes in suspicion" },
  { id: "frown-in-displeasure", label: "Frown", category: "face-expression", description: "Brows draw together, mouth corners pull down",
    promptHint: "the subject frowns, the brows drawing together and lowering while the corners of the mouth pull downward, the whole face settling into troubled displeasure",
    term: "frowns in displeasure" },
  { id: "scowl-in-anger", label: "Scowl", category: "face-expression", description: "Brows knit hard, nose wrinkles, jaw sets",
    promptHint: "the subject scowls, the brows knitting hard and low, the nose wrinkling and the upper lip lifting slightly as the jaw sets forward in open anger",
    term: "scowls in open anger" },
  { id: "fix-hard-glare", label: "Glare", category: "face-expression", description: "Eyes lock on one point in a hard hostile stare",
    promptHint: "the subject fixes a hard glare, the eyes narrowing and locking onto one point as the head lowers a fraction, the brow flat and the jaw clenched, holding without blinking",
    term: "glares hard without blinking" },
  { id: "clench-jaw-tight", label: "Clench Jaw", category: "face-expression", description: "Jaw muscles bunch, lips press, nostrils flare",
    promptHint: "the subject clenches the jaw, the muscles bunching at the hinge as the lips press tight and the nostrils flare, the breath held and the eyes hardening in restrained anger",
    term: "clenches jaw, nostrils flaring" },
  { id: "grimace-in-pain", label: "Grimace", category: "face-expression", description: "Lips bare teeth, nose scrunches, eyes squeeze",
    promptHint: "the subject grimaces, the lips pulling back to bare the teeth as the nose scrunches and the eyes squeeze half-shut in a flash of pain, before the face relaxes again",
    term: "grimaces, baring teeth" },
  { id: "wince-and-recover", label: "Wince", category: "face-expression", description: "Whole face flinches tight, then eases open",
    promptHint: "the subject winces, the whole face flinching tight for an instant with the eyes squeezing shut and the head pulling back a fraction, then the features easing open again",
    term: "winces and recovers" },
  { id: "scream-mouth-wide", label: "Scream", category: "face-expression", description: "Mouth stretches wide, eyes wide, neck strains",
    promptHint: "the subject screams, the mouth stretching wide open and the eyes going wide under raised brows, the cords of the neck standing out as the head thrusts forward with the force of it",
    term: "screams, mouth wide open" },
  { id: "swallow-hard", label: "Swallow Hard", category: "face-expression", description: "Throat works in a nervous gulp",
    promptHint: "the subject swallows hard, the throat visibly working as the lips press together and the eyes hold steady with unease, the chin dipping slightly on the gulp",
    term: "swallows hard, throat working" },
  { id: "sigh-heavily", label: "Sigh", category: "face-expression", description: "Deep breath in, shoulders drop as it leaves",
    promptHint: "the subject sighs heavily, the chest rising on a deep breath, then the shoulders dropping and the eyes closing briefly as the breath leaves, the face settling into resignation",
    term: "sighs heavily, shoulders dropping" },
  { id: "yawn-wide", label: "Yawn", category: "face-expression", description: "Mouth stretches wide, eyes squeeze, head tips back",
    promptHint: "the subject yawns, the mouth stretching wide open as the eyes squeeze shut and the head tips back, then the jaw closing and the face relaxing on the exhale",
    term: "yawns wide, head tipping back" },
  { id: "sneeze-and-recover", label: "Sneeze", category: "face-expression", description: "Face scrunches, head jerks forward, then relaxes",
    promptHint: "the subject sneezes, the face scrunching and the eyes clamping shut as the head jerks forward on the burst, then the features relaxing and the head lifting back up",
    term: "sneezes, head jerking forward" },
  { id: "blow-out-cheeks", label: "Blow Out Cheeks", category: "face-expression", description: "Cheeks puff full, then a long deflating exhale",
    promptHint: "the subject blows out the cheeks, puffing them full of air, then releases the breath in a long exhale as the cheeks deflate and the shoulders sag",
    term: "puffs out cheeks and exhales" },
  { id: "purse-lips-thoughtfully", label: "Purse Lips", category: "face-expression", description: "Lips press into a tight pucker, eyes narrow",
    promptHint: "the subject purses the lips, pressing them together and pushing them forward into a tight pucker while the eyes narrow in thought, before the mouth relaxes again",
    term: "purses lips in thought" },
  { id: "pout-sulkily", label: "Pout", category: "face-expression", description: "Lower lip pushes out, chin dips in a sulk",
    promptHint: "the subject pouts, the lower lip pushing out and the brows lowering as the chin dips, the shoulders drawing in and the sulky look holding for a beat",
    term: "pouts sulkily" },
  { id: "chew-lip-nervously", label: "Chew Lip Nervously", category: "face-expression", description: "Teeth worry the lower lip, eyes flick about",
    promptHint: "the subject chews the lower lip nervously, the teeth working at it while the eyes flick side to side, then releases it with a swallow and a small exhale",
    term: "chews lower lip nervously" },
  { id: "soften-into-tenderness", label: "Soften Into Tenderness", category: "face-expression", description: "Hard set of the face melts into warmth",
    promptHint: "the subject softens, the hard set of the jaw and brow releasing as the eyes warm and the mouth eases into a tender half-smile, the head tilting gently to one side",
    term: "softens into tenderness" },
  { id: "bite-lip-teasingly", label: "Bite Lip", category: "face-expression", description: "Catches the lower lip, holds, releases with a smile",
    promptHint: "the subject catches the lower lip between the teeth and holds it for a beat as the gaze lifts, then releases it with a small teasing smile",
    term: "bites lower lip and releases", adultOnly: true },
  { id: "lick-lips-suggestively", label: "Lick Lips", category: "face-expression", description: "Tongue traces the lower lip end to end",
    promptHint: "the subject runs the tongue across the lips, tracing the lower lip from one corner to the other, then closes the mouth with a faint suggestive smile",
    term: "licks lips suggestively", adultOnly: true },
  { id: "smolder-heavy-lidded", label: "Smolder", category: "face-expression", description: "Gaze goes heavy-lidded, lips part, chin dips",
    promptHint: "the subject lets the gaze go heavy-lidded, the chin dipping and the lips parting slightly as the eyes lock forward, holding the smoldering look without blinking",
    term: "smolders with a heavy-lidded gaze", adultOnly: true },
  { id: "break-into-blush", label: "Blush", category: "face-expression", description: "Color floods the cheeks, gaze drops, shy smile",
    promptHint: "the subject blushes, color rising up the neck and flooding the cheeks as the gaze drops and a shy smile tugs at the mouth, the shoulders lifting a little toward the ears",
    term: "blushes, color flooding the cheeks" },
  { id: "cringe-and-recoil", label: "Cringe", category: "face-expression", description: "Face scrunches tight, shoulders hitch up, head pulls back",
    promptHint: "the subject cringes, the face scrunching tight with the eyes squeezing half-shut and the teeth baring in a pained grin as the shoulders hitch up toward the ears and the head pulls back",
    term: "cringes, face scrunching, shoulders up" },
  { id: "cough-into-fist", label: "Cough", category: "face-expression", description: "Two or three sharp hacks into a raised fist",
    promptHint: "the subject coughs into a raised fist, the head dipping forward on two or three sharp hacks with the eyes squeezing shut, before the fist lowers and the face clears",
    term: "coughs into a fist" },
  { id: "laugh-nervously", label: "Nervous Laugh", category: "face-expression", description: "Short breathy laugh that stalls, eyes flick away",
    promptHint: "the subject laughs nervously, a short breathy laugh that stalls and restarts as the eyes flick away and back, the smile stretched too wide and the shoulders hunching",
    term: "laughs nervously, eyes flicking away" },
  { id: "furrow-brow-in-confusion", label: "Furrow Brow", category: "face-expression", description: "Brows draw together, crease forms, mouth slackens",
    promptHint: "the subject furrows the brow in confusion, the eyebrows drawing together and down until a crease forms between them, the eyes narrowing and the mouth going slack in puzzlement",
    term: "furrows brow in confusion" },
  { id: "wrinkle-nose-in-disgust", label: "Wrinkle Nose", category: "face-expression", description: "Nostrils pinch, upper lip curls, head pulls back",
    promptHint: "the subject wrinkles the nose in disgust, the nostrils pinching upward and the upper lip curling as the eyes squint and the head pulls back a fraction",
    term: "wrinkles nose in disgust" },
  { id: "pant-out-of-breath", label: "Pant", category: "face-expression", description: "Mouth open, chest heaving in rapid shallow breaths",
    promptHint: "the subject pants out of breath, the mouth hanging open and the chest heaving in rapid shallow breaths as the shoulders rise and fall and the head droops, before the breathing steadies",
    term: "pants, out of breath" },
  { id: "stifle-a-laugh", label: "Stifle a Laugh", category: "face-expression", description: "Hand claps over the mouth, shoulders shake anyway",
    promptHint: "the subject stifles a laugh behind a hand, the palm clapping over the mouth as the shoulders shake and the eyes crinkle, the cheeks bulging against the pressure until the laugh leaks out through the nose",
    term: "stifles a laugh behind a hand" },
  { id: "pucker-and-whistle", label: "Whistle", category: "face-expression", description: "Lips draw into a tight O and hold a note",
    promptHint: "the subject puckers the lips and whistles, the mouth drawing into a tight round O and the cheeks hollowing as the brows lift, holding the note before the lips relax",
    term: "puckers and whistles" },
  { id: "stick-out-tongue", label: "Stick Out Tongue", category: "face-expression", description: "Tongue pushes out past the lips, eyes squint playfully",
    promptHint: "the subject sticks out the tongue, the mouth opening and the tongue pushing out past the lips as the eyes squint playfully, holding it for a beat before pulling it back in",
    term: "sticks out the tongue playfully" },
  { id: "widen-eyes-in-dread", label: "Widen Eyes in Dread", category: "face-expression", description: "Eyes open wide, mouth stays shut, breath catches",
    promptHint: "the subject widens the eyes in dread, the lids lifting until white shows above the iris while the mouth stays closed and the breath catches, the whole body going still",
    term: "widens eyes in dread, mouth closed" },
  { id: "dart-eyes-nervously", label: "Darting Eyes", category: "face-expression", description: "Gaze flicks side to side while the head stays still",
    promptHint: "the subject darts the eyes nervously, the gaze flicking from side to side and back to center in quick jumps while the head stays still and the lips press together",
    term: "darts eyes nervously, head still" },
  { id: "waggle-eyebrows", label: "Waggle Eyebrows", category: "face-expression", description: "Both brows bounce up and down, playful grin spreads",
    promptHint: "the subject waggles both eyebrows, the brows bouncing up and down together two or three times in quick succession while a playful grin spreads and the chin tips forward",
    term: "waggles both eyebrows" },
  { id: "blow-bubblegum-bubble", label: "Bubblegum Bubble", category: "face-expression", description: "Pink bubble swells from the lips and pops flat",
    promptHint: "the subject blows a bubblegum bubble, the lips pushing forward as a pink bubble swells from the mouth until it pops flat against the lips, the tongue pulling the gum back in with a bored chew",
    term: "blows a bubblegum bubble and pops it" },
  { id: "laugh-maniacally", label: "Maniacal Laugh", category: "face-expression", description: "Head thrown back in a wild unhinged laugh, eyes wide",
    promptHint: "the subject laughs maniacally, the head throwing back and the mouth stretching wide as the shoulders heave, the eyes wild and unblinking when the head snaps forward again with the grin still fixed",
    term: "laughs maniacally, head thrown back" },
]
