import type { CharacterMotion } from "./types.js"

/** gestures — authored motion fragments. Stable ids survive copy revisions. */
export const GESTURES_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { "id": "wave-hello", "label": "Wave hello", "category": "gestures", "description": "Raises a hand and waves in greeting",
    "promptHint": "the subject lifts one hand to shoulder height, palm forward, and waves it side to side in a friendly greeting before letting the arm drop back to the side", "term": "waves hello",
    "startPose": "standing", "endPose": "standing", "needsFreeHands": true, "aliases": ["greet", "greeting"] },
  { "id": "wave-goodbye", "label": "Wave goodbye", "category": "gestures", "description": "Arm raised high, wide farewell wave",
    "promptHint": "the subject raises one arm high overhead, palm open, and sweeps the hand in wide side-to-side arcs of farewell, then lets the arm sink and the hand settle at the hip", "term": "waves goodbye with arm raised high",
    "startPose": "standing", "endPose": "standing", "needsFreeHands": true, "aliases": ["farewell"] },
  { "id": "thumbs-up", "label": "Thumbs up", "category": "gestures", "description": "Fist with thumb raised in approval",
    "promptHint": "the subject closes one hand into a fist, extends the thumb upward and pushes the hand forward to chest height in approval, holding it there before lowering it", "term": "gives a thumbs up" },
  { "id": "thumbs-down", "label": "Thumbs down", "category": "gestures", "description": "Thumb jabbed toward the floor",
    "promptHint": "the subject raises a closed fist to chest height, rotates the wrist so the extended thumb points at the floor and jabs it downward once in disapproval", "term": "gives a thumbs down" },
  { "id": "beckon", "label": "Beckon", "category": "gestures", "description": "Curls the fingers in a come-here scoop",
    "promptHint": "the subject extends one arm forward, palm up, and curls the fingers back toward the chest in repeated come-here scoops, the elbow drawing in and the head tilting in invitation", "term": "beckons come here with one hand" },
  { "id": "stop-hand", "label": "Stop hand", "category": "gestures", "description": "Open palm thrust forward like a wall",
    "promptHint": "the subject thrusts one arm straight forward and snaps the open palm up like a wall, fingers together and elbow locked, holding the hand firm before it relaxes", "term": "holds up a stop hand" },
  { "id": "salute", "label": "Salute", "category": "gestures", "description": "Crisp military salute to the brow",
    "promptHint": "the subject snaps to attention and brings the right hand up in one crisp arc until the fingertips touch the brow, holds the salute, then drops the arm to the side", "term": "snaps a military salute" },
  { "id": "shrug", "label": "Shrug", "category": "gestures", "description": "Shoulders up, palms turned out",
    "promptHint": "the subject lifts both shoulders toward the ears while the forearms rotate outward so the palms turn up, eyebrows rising, then the shoulders drop and the hands fall", "term": "shrugs with palms up" },
  { "id": "clap", "label": "Clap", "category": "gestures", "description": "Claps hands in applause",
    "promptHint": "the subject brings both hands together in front of the chest and claps repeatedly, palms meeting squarely with loose elbows, the face brightening with applause", "term": "claps in applause" },
  { "id": "slow-clap", "label": "Slow clap", "category": "gestures", "description": "Sarcastic, widely spaced claps",
    "promptHint": "the subject raises both hands to chest height and claps in deliberate, widely spaced strokes, each meeting of the palms held a beat, face flat and unimpressed", "term": "slow claps sarcastically" },
  { "id": "facepalm", "label": "Facepalm", "category": "gestures", "description": "Palm pressed over the face in dismay",
    "promptHint": "the subject lifts one hand to the face and presses the palm over the eyes and forehead, head dropping into the hand and shoulders sagging, then the hand slides down", "term": "facepalms" },
  { "id": "cross-arms", "label": "Cross arms", "category": "gestures", "description": "Folds both arms across the chest",
    "promptHint": "the subject brings both arms up and folds them across the chest one over the other, each hand tucking under the opposite elbow, shoulders squaring as the weight settles back", "term": "folds arms across the chest" },
  { "id": "plant-hands-on-hips", "label": "Plant hands on hips", "category": "gestures", "description": "Swings both hands up onto the hips",
    "promptHint": "the subject swings both hands up from the sides and plants them on the hips, elbows flaring out, chest lifting as the stance settles and the chin comes up", "term": "plants hands on hips" },
  { "id": "shush", "label": "Shush", "category": "gestures", "description": "Index finger pressed to the lips",
    "promptHint": "the subject raises one index finger and presses it vertically against the lips, eyebrows lifting in a hush, holding the finger there before lowering it", "term": "shushes with a finger to the lips" },
  { "id": "blow-a-kiss", "label": "Blow a kiss", "category": "gestures", "description": "Kisses the fingertips and sends it out",
    "promptHint": "the subject touches the fingertips of one hand to the lips, then extends the arm outward and opens the hand, sending the kiss forward with a small smile", "term": "blows a kiss" },
  { "id": "peace-sign", "label": "Peace sign", "category": "gestures", "description": "Flashes a V beside the face",
    "promptHint": "the subject raises one hand beside the face and splits the index and middle fingers into a V, palm outward, holding the sign with a grin before dropping the hand", "term": "flashes a peace sign" },
  { "id": "heart-hands", "label": "Heart hands", "category": "gestures", "description": "Both hands form a heart shape",
    "promptHint": "the subject brings both hands together in front of the chest, curling the fingers and touching the thumbs so the hands form a heart shape, and holds it up", "term": "makes a heart with both hands" },
  { "id": "fist-pump", "label": "Fist pump", "category": "gestures", "description": "Sharp downward pump of triumph",
    "promptHint": "the subject clenches one fist at shoulder height and yanks it down and in toward the ribs in a sharp pump of triumph, the elbow snapping back and the shoulders rising as the mouth shapes a silent yes", "term": "fist pumps in triumph" },
  { "id": "raise-a-fist", "label": "Raise a fist", "category": "gestures", "description": "Fist driven straight up overhead",
    "promptHint": "the subject clenches one hand into a fist and drives it straight up overhead, arm fully extended, chest lifting and jaw set in a gesture of defiance", "term": "raises a fist overhead" },
  { "id": "bow", "label": "Bow", "category": "gestures", "description": "Bends from the waist and straightens",
    "promptHint": "the subject bends forward from the waist in a respectful bow, head lowering and one hand pressed flat across the stomach, then straightens back up", "term": "bows from the waist" },
  { "id": "curtsy", "label": "Curtsy", "category": "gestures", "description": "Foot behind, knees dip, rises",
    "promptHint": "the subject places one foot behind the other, bends the knees while lightly lifting the sides of the garment, dips the head, then rises back to standing", "term": "curtsies" },
  { "id": "tip-a-hat", "label": "Tip a hat", "category": "gestures", "description": "Pinches the brim and tips it forward",
    "promptHint": "the subject raises one hand to the brim of the hat, pinches it and tips it forward with a small nod of the head, then releases the brim and lowers the hand", "term": "tips their hat" },
  { "id": "adjust-glasses", "label": "Adjust glasses", "category": "gestures", "description": "Pushes glasses up the nose",
    "promptHint": "the subject lifts one hand to the face and pushes the glasses up the bridge of the nose with a fingertip, head tipping back a fraction, then lowers the hand", "term": "pushes up their glasses" },
  { "id": "run-hand-through-hair", "label": "Run hand through hair", "category": "gestures", "description": "Rakes fingers from hairline to nape",
    "promptHint": "the subject raises one hand to the forehead and rakes the fingers back through the hair in one full pass from hairline to nape, head tilting with the stroke, then the hand drops away", "term": "runs a hand through their hair" },
  { "id": "count-on-fingers", "label": "Count on fingers", "category": "gestures", "description": "Extends fingers one by one, ticking off",
    "promptHint": "the subject holds up one hand and extends the fingers one at a time, starting with the thumb, ticking off items while the lips move as if listing them", "term": "counts on their fingers" },
  { "id": "point-off-frame", "label": "Point off-frame", "category": "gestures", "description": "Points at something off to one side",
    "promptHint": "the subject extends one arm and points with the index finger toward something off to one side, gaze following the finger, the arm holding before it lowers", "term": "points off to one side" },
  { "id": "snap-fingers", "label": "Snap fingers", "category": "gestures", "description": "Snaps the fingers with a wrist flick",
    "promptHint": "the subject raises one hand and snaps the fingers, the middle finger sliding off the thumb into the palm with a flick of the wrist, as if an idea just landed", "term": "snaps their fingers" },
  { "id": "wipe-brow", "label": "Wipe brow", "category": "gestures", "description": "Back of the hand dragged across the forehead",
    "promptHint": "the subject drags the back of one hand across the forehead in a relieved wipe, exhaling, then flicks the hand away and lets the arm drop", "term": "wipes their brow" },
  { "id": "cover-mouth-shock", "label": "Cover mouth in shock", "category": "gestures", "description": "Hand flies up over the open mouth",
    "promptHint": "the subject gasps and flings one hand up to cover the open mouth, fingers pressed over the lips and eyes widening, the body drawing back half a step", "term": "covers mouth in shock" },
  { "id": "prayer-hands", "label": "Prayer hands", "category": "gestures", "description": "Palms pressed together at the chest",
    "promptHint": "the subject brings both palms together in front of the chest, fingers pointing up, and bows the head slightly over the joined hands in a plea or thanks", "term": "presses palms together in prayer" },
  { "id": "ok-sign", "label": "Ok sign", "category": "gestures", "description": "Index and thumb form a circle",
    "promptHint": "the subject raises one hand and touches the tip of the index finger to the thumb, forming a circle while the other three fingers extend, holding the OK sign", "term": "makes an ok sign" },
  { "id": "finger-wag", "label": "Finger wag", "category": "gestures", "description": "Index finger wagged in a scolding no",
    "promptHint": "the subject raises one index finger and wags it side to side at the level of the face in a scolding no-no, the head shaking slightly in time", "term": "wags a finger" },
  { "id": "air-quotes", "label": "Air quotes", "category": "gestures", "description": "Two fingers curled beside the head",
    "promptHint": "the subject lifts both hands beside the head and curls the index and middle fingers twice in sarcastic air quotes, eyebrows arched, then drops the hands", "term": "makes air quotes" },
  { "id": "talk-with-hands", "label": "Talk with hands", "category": "gestures", "description": "Hands shape each point while speaking",
    "promptHint": "the subject speaks while the hands move with the words, one hand rolling forward from the wrist and the palms opening and closing to shape each point", "term": "talks with expressive hand gestures" },
  { "id": "chef-kiss", "label": "Chef kiss", "category": "gestures", "description": "Kisses pinched fingertips and flicks open",
    "promptHint": "the subject pinches the fingertips of one hand together, kisses them, and flicks the hand open outward in a flourish of perfection", "term": "does a chef's kiss" },
  { "id": "brush-off-shoulder", "label": "Brush off shoulder", "category": "gestures", "description": "Flicks imaginary dust off the shoulder",
    "promptHint": "the subject raises one hand to the opposite shoulder and flicks imaginary dust off it with two short backhand swipes, chin lifting in cool dismissal", "term": "brushes off their shoulder" },
  { "id": "flex-biceps", "label": "Flex biceps", "category": "gestures", "description": "Both arms curled to show the muscles",
    "promptHint": "the subject raises both arms and bends them at the elbows, fists curling in to flex the biceps, chest puffing out as the muscles are held on display", "term": "flexes both biceps" },
  { "id": "throw-hands-up", "label": "Throw hands up", "category": "gestures", "description": "Both hands flung up in exasperation",
    "promptHint": "the subject flings both hands up and outward to shoulder height, palms open, in exasperation, then lets the arms slap back down against the sides", "term": "throws their hands up" },
  { "id": "place-hand-over-heart", "label": "Place hand over heart", "category": "gestures", "description": "Hand rises and settles flat over the chest",
    "promptHint": "the subject raises one hand and lays the open palm flat over the heart, fingers spread and pressing gently, head dipping in sincerity, then lets the hand slide away", "term": "places a hand over the heart" },
  { "id": "pinch-bridge-of-nose", "label": "Pinch bridge of nose", "category": "gestures", "description": "Eyes closed, thumb and finger at the nose",
    "promptHint": "the subject closes the eyes and pinches the bridge of the nose between thumb and forefinger, head tipping forward in weary frustration, then lets go", "term": "pinches the bridge of the nose" },
  { "id": "raise-a-hand", "label": "Raise a hand", "category": "gestures", "description": "Arm straight up, asking to speak",
    "promptHint": "the subject lifts one arm straight up with the palm open and fingers together, as if asking to speak, holds it high for a beat, then lowers it", "term": "raises a hand to speak" },
  { "id": "cup-hands-to-shout", "label": "Cup hands to shout", "category": "gestures", "description": "Hands cupped around the mouth, calling out",
    "promptHint": "the subject cups both hands around the mouth, leans forward and calls out into the distance, chest expanding with the shout, then lowers the hands", "term": "cups hands to shout" },
  { "id": "wave-off", "label": "Wave off", "category": "gestures", "description": "Loose backhand flick of dismissal",
    "promptHint": "the subject flicks one hand away from the body in a loose backhand wave of dismissal, wrist limp, turning the head aside as the arm drops", "term": "waves a hand dismissively" },
  { "id": "dust-off-hands", "label": "Dust off hands", "category": "gestures", "description": "Palms slapped together, job done",
    "promptHint": "the subject slaps the palms against each other in alternating strokes, brushing dust off the hands in a job-done gesture, then drops the arms", "term": "dusts off their hands" },
  { "id": "straighten-tie", "label": "Straighten tie", "category": "gestures", "description": "Tugs the knot snug and smooths the shirt",
    "promptHint": "the subject raises both hands to the collar, tugs the tie knot snug and straightens it with a tilt of the head, then smooths the front of the shirt", "term": "straightens their tie" },
  { "id": "raise-hands-in-surrender", "label": "Raise hands in surrender", "category": "gestures", "description": "Feet planted, both palms rise to shoulder height",
    "promptHint": "the subject keeps both feet planted and raises both hands, palms out and fingers spread, until they hover at shoulder height with the elbows bent, and holds them there", "term": "raises both hands in surrender" },
  { "id": "present-with-open-palm", "label": "Present with open palm", "category": "gestures", "description": "Open-palm sweep toward something beside them",
    "promptHint": "the subject extends one arm out to the side with the palm open and facing up, sweeping the hand toward whatever stands beside them as the head turns to follow, then draws the arm back", "term": "presents with an open-palm sweep" },
  { "id": "point-to-self", "label": "Point to self", "category": "gestures", "description": "Finger taps own chest, who me",
    "promptHint": "the subject brings one hand up and points the index finger at the center of the chest, tapping it twice while the eyebrows lift and the head tilts in disbelief", "term": "points at own chest in disbelief" },
  { "id": "mind-blown", "label": "Mind blown", "category": "gestures", "description": "Fists at the temples burst open outward",
    "promptHint": "the subject raises both fists to the temples, then springs the fingers open and pulls the hands outward and away from the head in a bursting arc, mouth dropping open and eyes wide", "term": "mimes mind blown from the temples" },
  { "id": "stroke-chin", "label": "Stroke chin", "category": "gestures", "description": "Thumb and finger stroke the chin in thought",
    "promptHint": "the subject raises one hand to the face and draws the thumb and forefinger down along the jaw to the chin in repeated strokes, eyes narrowing and gaze drifting upward in thought, then lowers the hand", "term": "strokes the chin in thought" },
  { "id": "steeple-fingers", "label": "Steeple fingers", "category": "gestures", "description": "Fingertips meet in a steeple at chest height",
    "promptHint": "the subject lifts both hands to chest height and touches the fingertips of each hand to their opposites, forming a steeple, elbows settling as the hands hold and the fingertips tap together once", "term": "steeples the fingers" },
  { "id": "cup-hand-to-ear", "label": "Cup hand to ear", "category": "gestures", "description": "Hand cupped behind the ear, leaning in",
    "promptHint": "the subject raises one hand and cups it behind the ear, leaning the head toward it and turning that ear forward as the eyebrows lift, then drops the hand", "term": "cups a hand behind the ear" },
  { "id": "fingers-crossed", "label": "Cross fingers", "category": "gestures", "description": "Middle finger hooks over the index for luck",
    "promptHint": "the subject raises one hand to chest height and hooks the middle finger over the index finger, holding the crossed fingers up beside the face with a hopeful grimace, then uncrosses them", "term": "crosses fingers for luck" },
  { "id": "scratch-head", "label": "Scratch head", "category": "gestures", "description": "Fingers scratch the crown, puzzled",
    "promptHint": "the subject lifts one hand to the top of the head and scratches the crown with the fingertips, brow furrowing and mouth pulling to one side in puzzlement, then lets the hand drop", "term": "scratches head in puzzlement" },
  { "id": "jump-up-and-down-excited", "label": "Jump up and down", "category": "gestures", "description": "Bounces on both feet, clapping, in excitement",
    "promptHint": "the subject bounces up and down on both feet in small repeated hops, clapping the hands in front of the chest with each landing, shoulders rising and the face breaking into a wide grin", "term": "jumps up and down clapping" },
  { "id": "open-arms-to-sky", "label": "Open arms to sky", "category": "gestures", "description": "Arms spread wide, head tipping back",
    "promptHint": "the subject spreads both arms wide and out to the sides, palms turning up, chest opening and head tipping back so the face lifts toward the sky, and holds the pose", "term": "spreads arms wide to the sky" },
  { "id": "bury-face-in-hands", "label": "Bury face in hands", "category": "gestures", "description": "Both palms cover the face, head sinking",
    "promptHint": "the subject raises both hands and presses the palms over the face, fingers covering the eyes, head sinking forward into the hands and shoulders curling in, then the hands slide down", "term": "buries face in both hands" },
  { "id": "clutch-head-both-hands", "label": "Clutch head", "category": "gestures", "description": "Both hands grip the skull in frustration",
    "promptHint": "the subject brings both hands up and clamps them onto the sides of the head, fingers digging into the hair, elbows pulling forward and the head shaking from side to side, then the hands drop", "term": "clutches head with both hands" },
  { "id": "wipe-tears", "label": "Wipe tears", "category": "gestures", "description": "Back of the hand drawn under each eye",
    "promptHint": "the subject lifts one hand and draws the back of it under one eye and then the other, wiping tears away, sniffing as the head dips and the hand falls back down", "term": "wipes tears with the back of a hand" },
  { "id": "slam-fist-on-table", "label": "Slam fist on table", "category": "gestures", "description": "Fist raised and driven onto the tabletop",
    "promptHint": "the subject raises one clenched fist above the table and drives it down onto the surface, the arm stiff on impact, leaning forward over the fist with the jaw set", "term": "slams a fist on the table" },
  { "id": "fan-and-toss-cash", "label": "Fan and toss cash", "category": "gestures", "description": "Fans a stack of bills, then flings them up",
    "promptHint": "the subject holds a stack of bills in one hand, fans it open with the thumb, then flicks the wrist and flings the notes up into the air so they scatter all around", "term": "fans out cash and tosses it" },
  { "id": "rub-fingers-money", "label": "Rub fingers for money", "category": "gestures", "description": "Thumb rubs across the fingertips, pay up",
    "promptHint": "the subject raises one hand to chest height and rubs the thumb back and forth across the tips of the index and middle fingers in the money sign, eyebrows lifting", "term": "rubs thumb and fingers in the money sign" },
  { "id": "finger-guns", "label": "Finger guns", "category": "gestures", "description": "Both index fingers aim and fire with a wink",
    "promptHint": "the subject points both index fingers forward with the thumbs up like pistols, then flicks the hands upward as if firing while winking and clicking the tongue", "term": "fires finger guns" },
  { "id": "jazz-hands", "label": "Jazz hands", "category": "gestures", "description": "Palms out, fingers spread and shaking",
    "promptHint": "the subject throws both hands up beside the shoulders, palms forward and fingers spread wide, and shakes them in a flutter with a big showy grin", "term": "flashes jazz hands" },
  { "id": "peekaboo", "label": "Peekaboo", "category": "gestures", "description": "Covers the eyes with both hands, then opens",
    "promptHint": "the subject covers both eyes with the palms, holds for a beat, then swings the hands apart and outward to reveal a wide-eyed, open-mouthed face", "term": "plays peekaboo with both hands" },
  { "id": "wave-both-arms-overhead", "label": "Wave both arms overhead", "category": "gestures", "description": "Both arms high, crossing side to side",
    "promptHint": "the subject raises both arms fully overhead and sweeps them side to side in wide crossing arcs, the whole torso swaying with the wave to draw attention", "term": "waves both arms overhead" },
  { "id": "rub-eyes", "label": "Rub eyes", "category": "gestures", "description": "Fists knuckle both eyes, tired",
    "promptHint": "the subject curls both hands into loose fists and rubs the knuckles into the eyes in small circles, head tipping forward and a yawn stretching the mouth, then lowers the hands", "term": "rubs eyes with fists" },
  { "id": "rub-belly", "label": "Rub belly", "category": "gestures", "description": "Palm circles the stomach, hungry",
    "promptHint": "the subject places one open hand flat on the stomach and rubs it in circles, licking the lips and glancing down at the belly, then pats it once", "term": "rubs belly in hunger" },
  { "id": "stomp-foot", "label": "Stomp foot", "category": "gestures", "description": "One foot lifted and slammed down",
    "promptHint": "the subject lifts one foot and slams it down flat onto the ground, fists clenching at the sides and the shoulders jolting with the stomp, chin jutting forward", "term": "stomps a foot" },
  { "id": "shake-fist-at-sky", "label": "Shake fist at sky", "category": "gestures", "description": "Fist raised overhead and shaken at the sky",
    "promptHint": "the subject thrusts one clenched fist up overhead and shakes it at the sky in short angry jerks, head thrown back and mouth open in a shout, then drops the arm", "term": "shakes a fist at the sky" },
  { "id": "cross-arms-x", "label": "Cross forearms in x", "category": "gestures", "description": "Forearms snap into an X before the chest",
    "promptHint": "the subject snaps both forearms up and across each other into an X in front of the chest, fists closed, head shaking once in a firm no, then flings the arms apart", "term": "crosses forearms in an x" },
  { "id": "raise-one-finger-wait", "label": "Raise one finger", "category": "gestures", "description": "Index finger up, one moment",
    "promptHint": "the subject raises one index finger to shoulder height, palm facing outward, and holds it up with the eyebrows lifted as if asking for one moment, then lowers it", "term": "raises one finger for a moment" },
  { "id": "hoist-trophy", "label": "Hoist trophy", "category": "gestures", "description": "Trophy lifted overhead in both hands",
    "promptHint": "the subject grips a trophy in both hands at chest height and thrusts it straight up overhead, arms locking out, chest lifting and the mouth opening in a roar of celebration", "term": "hoists a trophy overhead" },
  { "id": "toss-cap-in-air", "label": "Toss cap in air", "category": "gestures", "description": "Graduation cap flung up overhead",
    "promptHint": "the subject pulls the graduation cap off the head with one hand and flings it straight up into the air, the arm following through overhead as the face tilts up to watch it", "term": "tosses a graduation cap" },
  { "id": "pat-pockets-searching", "label": "Pat pockets", "category": "gestures", "description": "Pats each pocket, searching for something lost",
    "promptHint": "the subject pats the front pockets with both hands, then the back pockets and the chest, the head dipping to check each one with a growing frown", "term": "pats pockets searching" },
  { "id": "flash-shaka-sign", "label": "Shaka sign", "category": "gestures", "description": "Thumb and pinky out, hand rocking loosely",
    "promptHint": "the subject raises one hand beside the shoulder, curls the three middle fingers into the palm with the thumb and little finger extended, rocks the hand side to side from the wrist a few times, then lowers it", "term": "flashes a shaka sign" },
  { "id": "throw-rock-horns", "label": "Rock horns", "category": "gestures", "description": "Index and pinky raised in the horns sign",
    "promptHint": "the subject thrusts one hand up above the shoulder with the index and little fingers extended and the middle and ring fingers folded under the thumb, pumps the hand upward twice with the chin jutting, then drops the arm", "term": "raises the rock horns" },
  { "id": "make-call-me-sign", "label": "Call me sign", "category": "gestures", "description": "Thumb-and-pinky phone held beside the face",
    "promptHint": "the subject folds the middle three fingers of one hand into the palm, extends the thumb and little finger, holds the hand beside the face with the thumb at the ear and the pinky at the mouth, then lowers it", "term": "mimes call me with thumb and pinky" },
  { "id": "zip-lips-shut", "label": "Zip lips", "category": "gestures", "description": "Pinched fingers drawn across closed lips",
    "promptHint": "the subject presses the lips together, pinches thumb and forefinger at one corner of the mouth and draws them across to the other corner like a zipper, then drops the hand, mouth sealed", "term": "zips the lips shut" },
  { "id": "lock-lips-toss-key", "label": "Lock lips, toss key", "category": "gestures", "description": "Turns a key at the lips, flicks it away",
    "promptHint": "the subject brings pinched fingertips to the corner of the closed mouth, twists the wrist a quarter turn like turning a key, then flicks the hand back over the shoulder to toss the key away", "term": "locks the lips and tosses the key" },
  { "id": "signal-watching-you", "label": "I'm watching you", "category": "gestures", "description": "Two fingers at the eyes, then pointed out",
    "promptHint": "the subject raises one hand, spreads the index and middle fingers into a V and touches the fingertips just below both eyes, then swings the hand forward to point the index finger straight out, eyes narrowing, and holds the point", "term": "points two fingers at the eyes, then out" },
  { "id": "circle-finger-at-temple", "label": "Circle finger at temple", "category": "gestures", "description": "Index finger twirled beside the head",
    "promptHint": "the subject raises one index finger to the side of the head and circles it in small loops beside the temple, the eyebrows lifting and the mouth pulling to one side in disbelief, then lowers the hand", "term": "twirls a finger beside the temple" },
  { "id": "tap-temple", "label": "Tap temple", "category": "gestures", "description": "Fingertip taps the head for a clever idea",
    "promptHint": "the subject lifts one index finger to the temple and taps it twice against the side of the head, the eyebrows raising and a sly smile forming as if struck by a clever idea, then lowers the hand", "term": "taps the temple knowingly" },
  { "id": "show-size-with-hands", "label": "Show size with hands", "category": "gestures", "description": "Palms held apart to show how big",
    "promptHint": "the subject raises both hands in front of the torso with the palms facing each other, spreads them apart until they frame the width of something, widens the gap once more, and holds the measurement in the air", "term": "holds hands apart to show size" },
  { "id": "pinch-a-tiny-bit", "label": "Pinch a tiny bit", "category": "gestures", "description": "Thumb and finger held nearly touching",
    "promptHint": "the subject raises one hand to eye level and brings the thumb and index finger toward each other until only a sliver of space remains between the tips, squinting through the gap, and holds the tiny measure", "term": "pinches a tiny gap between fingers" },
  { "id": "waggle-hand-so-so", "label": "So-so hand", "category": "gestures", "description": "Flat hand rocked side to side for meh",
    "promptHint": "the subject holds one hand out flat at chest height, palm down and fingers spread, rocks it from the wrist so the thumb side and little-finger side dip in turn, the mouth pulling to one side, then lowers the hand", "term": "waggles a flat hand so-so" },
  { "id": "signal-time-out", "label": "Time-out sign", "category": "gestures", "description": "Flat hand on upright fingertips forms a T",
    "promptHint": "the subject holds one hand upright, fingers pointing up, and lays the other hand flat across those upright fingertips to form a T in front of the chest, holds the sign firm, then separates the hands", "term": "makes a time-out t with the hands" },
  { "id": "roll-hand-keep-going", "label": "Roll hand, keep going", "category": "gestures", "description": "Hand circles forward to say keep going",
    "promptHint": "the subject holds one hand out at chest height with the fingers loose and circles it forward in repeated rolling loops from the wrist, the eyebrows lifting impatiently, then lets the hand stop and drop", "term": "rolls a hand forward to say keep going" },
  { "id": "jerk-thumb-over-shoulder", "label": "Jerk thumb over shoulder", "category": "gestures", "description": "Thumb jabbed backward to say get out",
    "promptHint": "the subject makes a fist with the thumb extended, raises it beside the shoulder and jabs the thumb backward over that shoulder twice toward the space behind, the chin jerking the same way, then lowers the hand", "term": "jerks a thumb over the shoulder" },
  { "id": "tap-wrist-for-time", "label": "Tap wrist", "category": "gestures", "description": "Fingers tap the wrist for time's up",
    "promptHint": "the subject raises one forearm across the body and taps two fingers of the other hand against the top of that wrist several times while looking pointedly ahead, then lowers both arms", "term": "taps the wrist, time's up" },
  { "id": "press-hands-to-cheeks", "label": "Hands on cheeks", "category": "gestures", "description": "Both palms pressed to the cheeks in surprise",
    "promptHint": "the subject brings both hands up and presses the palms flat against the cheeks with the fingers reaching toward the temples, the mouth dropping into an open O and the eyes widening, and holds the pose", "term": "presses both palms to the cheeks" },
  { "id": "fan-face-with-hand", "label": "Fan face", "category": "gestures", "description": "Flapping hand cools an overheated face",
    "promptHint": "the subject raises one open hand beside the face and flaps it back and forth from the wrist to push air across the cheeks, the mouth slightly open and the eyes half closed as if overheated, then lowers the hand", "term": "fans the face with a hand" },
  { "id": "hold-nose-at-smell", "label": "Hold nose", "category": "gestures", "description": "Pinches the nostrils, waves the air away",
    "promptHint": "the subject pinches both nostrils shut between the thumb and forefinger of one hand and waves the other hand back and forth in front of the face, squinting and pulling the head back, then releases the nose", "term": "pinches the nose and waves off a smell" },
  { "id": "cross-my-heart", "label": "Cross my heart", "category": "gestures", "description": "Index finger traces an X over the heart",
    "promptHint": "the subject raises one index finger to the left side of the chest, traces a small X over the heart one diagonal stroke at a time, then lifts the hand beside the shoulder, palm out, in a solemn promise", "term": "crosses the heart with a finger" },
  { "id": "clasp-hands-behind-back", "label": "Hands behind back", "category": "gestures", "description": "Hands clasp at the base of the spine",
    "promptHint": "the subject draws both arms back from the sides and clasps the hands together behind the lower back, one hand gripping the other wrist, the shoulders drawing back and the chest opening, and holds the composed stance", "term": "clasps hands behind the back" },
  { "id": "rub-temples", "label": "Rub temples", "category": "gestures", "description": "Fingertips circle both temples under stress",
    "promptHint": "the subject raises both hands to the sides of the head and presses the fingertips into the temples, rubbing them in small circles as the eyes close and the brow tightens, then lowers the hands on an exhale", "term": "rubs the temples in stress" },
  { "id": "swoon-hand-to-brow", "label": "Swoon", "category": "gestures", "description": "Back of a hand to the brow, head tipping back",
    "promptHint": "the subject lifts one hand and lays the back of it against the forehead, the head tipping back and the eyes fluttering closed in a theatrical swoon while the other hand drifts to the chest, and holds the pose", "term": "swoons, back of hand to the brow" },
  { "id": "raise-victory-arms", "label": "Raise victory arms", "category": "gestures", "description": "Both arms thrust overhead in a wide V",
    "promptHint": "the subject drives both arms up and out overhead into a wide V, fists closed and elbows locked, the chest lifting and the chin rising in triumph, and holds the arms high", "term": "thrusts both arms up in a victory v" },
  { "id": "count-down-fingers", "label": "Finger countdown", "category": "gestures", "description": "Three fingers fold down one by one to a fist",
    "promptHint": "the subject holds one hand up beside the face with three fingers extended and folds them down into the palm one at a time, the lips shaping each number, until the hand closes into a fist, then lowers it", "term": "counts down three-two-one on fingers" },
  { "id": "clap-once-and-point", "label": "Clap and point", "category": "gestures", "description": "One clap, then an emphatic point forward",
    "promptHint": "the subject brings both palms together in a single clap in front of the chest, then shoots one arm straight forward with the index finger extended in an emphatic you-got-it point, holds it, and drops the arm", "term": "claps once and points straight ahead" },
  { "id": "tap-side-of-nose", "label": "Tap side of nose", "category": "gestures", "description": "Fingertip taps the side of the nose",
    "promptHint": "the subject raises one index finger and taps it twice against the side of the nose, one eye narrowing and the corner of the mouth lifting in a conspiratorial look, then lowers the hand", "term": "taps the side of the nose" },
  { "id": "seated-wave", "label": "Wave while seated", "category": "gestures", "description": "Wave while seated.",
    "term": "waves one hand while remaining seated", "promptHint": "the subject remains seated and raises one hand to wave gently, then lowers it",
    "startPose": "seated", "endPose": "seated", "needsFreeHands": true, "handsAfter": "free" },
  { "id": "press-hands-to-neck", "label": "Rest hands at collarbone", "category": "gestures", "description": "Rests both hands lightly at the collarbone and holds.",
    "promptHint": "the subject raises both hands to rest lightly along the collarbone and holds them there without sliding down the chest", "term": "rests both hands lightly at the collarbone",
    "aliases": ["Hands to Neck"] },
]
