import type { CharacterMotion } from "./types.js"

/** Head Gestures — 31 entries. Category id `head-gestures`. */
export const HEAD_GESTURES_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "nod-eagerly", label: "Eager Nodding", category: "head-gestures", description: "A quick run of small, excited nods",
    promptHint: "the subject nods eagerly in a quick run of small bouncing nods, the chin bobbing down and up as the eyebrows lift and a smile widens, the head settling level after the last nod",
    term: "nods eagerly in small quick nods" },
  { id: "give-firm-nod", label: "Firm Single Nod", category: "head-gestures", description: "One sharp, decisive nod of agreement",
    promptHint: "the subject gives a single firm nod, the chin dropping sharply once and stopping dead with the jaw set and the eyes steady, before lifting the head back to level and holding it there",
    term: "gives one firm decisive nod" },
  { id: "nod-knowingly", label: "Knowing Nod", category: "head-gestures", description: "Small nods with a closed, knowing half-smile",
    promptHint: "the subject nods knowingly in small nods, the lips pressing into a closed half-smile and the eyes narrowing slightly as if a suspicion is confirmed, the head settling level after the last nod",
    term: "nods knowingly with a half-smile" },
  { id: "give-chin-up-nod", label: "Chin-Up Nod", category: "head-gestures", description: "Casual upward chin-nod of greeting",
    promptHint: "the subject flicks the chin upward in a single short nod of greeting, the head tipping back slightly and the eyebrows lifting briefly, before dropping the head back to level with a relaxed look",
    term: "gives a chin-up nod" },
  { id: "dip-head-in-thanks", label: "Nod of Thanks", category: "head-gestures", description: "Small grateful dip of the head, eyes closing",
    promptHint: "the subject dips the head forward in a small grateful nod, the eyes closing briefly and a faint smile forming, and lifts the head back to level as the eyes reopen",
    term: "dips head in a grateful nod" },
  { id: "nod-along-listening", label: "Listening Nods", category: "head-gestures", description: "Small intermittent nods while someone talks",
    promptHint: "the subject gives small intermittent nods while keeping the gaze on someone speaking nearby, the chin dipping lightly with a pause between nods, the lips closed and the face attentive throughout",
    term: "nods along while listening" },
  { id: "shake-head-in-disbelief", label: "Disbelieving Head Shake", category: "head-gestures", description: "Side-to-side head shake, eyes wide, mouth open",
    promptHint: "the subject shakes the head side to side in wide, heavy turns of disbelief, the eyes wide and fixed ahead and the mouth slightly open, until the head comes to rest at center",
    term: "shakes head in disbelief" },
  { id: "shake-head-sadly", label: "Sad Head Shake", category: "head-gestures", description: "Small reluctant refusal with lowered eyes",
    promptHint: "the subject shakes the head side to side in two small reluctant turns of refusal, the gaze lowered, the inner brows lifting and the lips pressed together in apology, the head settling still and slightly bowed",
    term: "shakes head sadly in refusal" },
  { id: "shake-head-no-no-no", label: "Rapid No-No-No", category: "head-gestures", description: "Rapid tiny head shakes, urgently refusing",
    promptHint: "the subject shakes the head in rapid tiny side-to-side shakes, the eyes wide and the lips mouthing no, the chin barely leaving center, until the head stops square and still",
    term: "shakes head no in rapid tiny shakes" },
  { id: "shake-head-amused", label: "Amused Head Shake", category: "head-gestures", description: "Shakes head with a crooked, amused smile",
    promptHint: "the subject shakes the head side to side with the eyes cast down, a breath of laughter puffing through the nose and a crooked smile spreading, before stopping the head and lifting the gaze back up",
    term: "shakes head with an amused smile" },
  { id: "tilt-head-both-ways", label: "Puzzled Double Tilt", category: "head-gestures", description: "Tilts one way, then the other, puzzling it out",
    promptHint: "the subject tips the head toward one shoulder and holds it with narrowed eyes, and swings it across to the other shoulder in a second puzzled tilt, the gaze staying fixed ahead",
    term: "tilts head one way and the other, puzzled" },
  { id: "wobble-head-so-so", label: "Head Wobble", category: "head-gestures", description: "Loose side-to-side wobble meaning so-so",
    promptHint: "the subject rocks the head in a loose side-to-side wobble, each ear dipping toward its shoulder in turn while the face stays forward and the lips purse noncommittally, before the head settles upright",
    term: "wobbles head side to side, so-so" },
  { id: "flick-hair-back-with-head", label: "Flick Hair Back", category: "head-gestures", description: "Snaps head aside to throw the hair back",
    promptHint: "the subject snaps the head sharply to one side and back, throwing the hair off the face so it swings over the shoulder and falls behind it, the chin ending slightly lifted",
    term: "flicks hair back with a head snap" },
  { id: "jut-chin-defiantly", label: "Jut Chin Defiantly", category: "head-gestures", description: "Chin thrust forward, jaw set in defiance",
    promptHint: "the subject juts the chin forward and slightly up, the jaw setting hard and the neck stiffening, the lips pressed tight and the eyes locked straight ahead in defiance, and holds the defiant set",
    term: "juts chin forward defiantly" },
  { id: "raise-chin-proudly", label: "Raise Chin Proudly", category: "head-gestures", description: "Chin lifts a notch, gaze down the nose",
    promptHint: "the subject lifts the chin a notch from level, the neck lengthening and the shoulders drawing back, the eyelids lowering so the gaze looks down the nose, and holds the proud angle",
    term: "raises chin proudly" },
  { id: "toss-head-haughtily", label: "Haughty Head Toss", category: "head-gestures", description: "Chin flicks up as the face turns away",
    promptHint: "the subject flicks the chin up and turns the face sharply away to one side in a haughty toss, the eyes closing briefly and the nose lifted, and holds the head averted",
    term: "tosses head up and away haughtily" },
  { id: "lower-head-in-shame", label: "Lower Head in Shame", category: "head-gestures", description: "Head sinks, eyes slide away, shoulders curl",
    promptHint: "the subject lowers the head until the chin nears the chest, the eyes dropping and sliding away to one side and the shoulders curling inward, and holds the bowed, averted head",
    term: "lowers head in shame" },
  { id: "bow-head-solemnly", label: "Bow Head Solemnly", category: "head-gestures", description: "Head bowed from the neck in quiet respect",
    promptHint: "the subject bows the head forward from the neck until the chin rests near the chest, the eyes closing and the body going still, and holds the lowered head in quiet respect",
    term: "bows head in solemn silence" },
  { id: "hang-head-in-defeat", label: "Hang Head in Defeat", category: "head-gestures", description: "Head drops heavy as the shoulders slump",
    promptHint: "the subject lets the head drop and hang heavy from the neck, the shoulders slumping forward on a long exhale and the eyes going unfocused toward the floor, and leaves the head hanging",
    term: "hangs head in defeat" },
  { id: "drop-head-back-against-wall", label: "Head Back Against Wall", category: "head-gestures", description: "Head falls back to rest on the wall, exhausted",
    promptHint: "the subject lets the head fall back until the back of the skull rests against the wall behind, the eyes closing and the throat lengthening as the breath leaves in an exhausted exhale",
    term: "lets head fall back against the wall" },
  { id: "rest-temple-on-window", label: "Temple Against Window", category: "head-gestures", description: "Head tilts to rest against the glass",
    promptHint: "the subject tilts the head sideways until the temple comes to rest against the window, the shoulders loosening and the gaze drifting out through the glass, and stays leaning there",
    term: "rests head against the window" },
  { id: "point-with-chin", label: "Chin Point", category: "head-gestures", description: "Jerks the chin toward a spot, over there",
    promptHint: "the subject jerks the chin toward a spot or person off to one side, the lips pushing forward and the eyebrows lifting as the eyes flick the same way, before bringing the head back to center",
    term: "points with a jerk of the chin" },
  { id: "beckon-with-head", label: "Head Beckon", category: "head-gestures", description: "Jerk of the head saying come on, follow",
    promptHint: "the subject jerks the head sideways toward one shoulder in a come-on signal, the chin swinging out toward the direction to follow and back once or twice as the eyebrows lift, and faces forward again",
    term: "beckons with a jerk of the head" },
  { id: "pull-head-back-surprised", label: "Pull Head Back", category: "head-gestures", description: "Head draws straight back, chin tucked, brows up",
    promptHint: "the subject pulls the head straight back in surprise, the chin tucking in against the neck, the eyebrows shooting up and the eyes widening, and holds the drawn-back position",
    term: "pulls head back in surprise" },
  { id: "avert-head-in-disgust", label: "Avert Head in Disgust", category: "head-gestures", description: "Head rears back and twists away from a smell",
    promptHint: "the subject rears the head back and twists it away to one side, the chin tucking toward the shoulder on that side and the nose wrinkling, and holds the face turned away from the smell",
    term: "averts head in disgust" },
  { id: "lean-head-in-to-listen", label: "Lean In to Listen", category: "head-gestures", description: "Head pushes forward, one ear toward the sound",
    promptHint: "the subject pushes the head forward and tilts it to bring one ear toward a faint sound, the eyes drifting unfocused and the brow knitting in concentration, and holds still to listen",
    term: "leans head in to listen" },
  { id: "rest-chin-in-hand", label: "Rest Chin in Hand", category: "head-gestures", description: "Chin sinks into the palm, gaze drifting",
    promptHint: "the subject props one elbow on a surface and lowers the chin into the open palm, the cheek pushing up against the fingers as the weight of the head settles and the gaze drifts idly",
    term: "rests chin in one hand" },
  { id: "shake-off-daze", label: "Shake Off Daze", category: "head-gestures", description: "Hard head shakes to clear a dazed mind",
    promptHint: "the subject squeezes the eyes shut and gives the head a few hard shakes side to side, the cheeks jostling, and blinks the eyes open wide as focus returns",
    term: "shakes head to clear a daze" },
  { id: "shake-out-wet-hair", label: "Shake Out Wet Hair", category: "head-gestures", description: "Vigorous head shake flinging water from hair",
    promptHint: "the subject bends slightly forward and shakes the head vigorously side to side, the wet hair whipping and flinging droplets outward, and straightens up with the hair tousled across the face",
    term: "shakes water out of wet hair" },
  { id: "duck-head-sheepishly", label: "Duck Head Sheepishly", category: "head-gestures", description: "Head ducks down, eyes peek up, sheepish grin",
    promptHint: "the subject ducks the head down and forward, the shoulders creeping up and the chin tucking, the eyes peeking up from under the brows with an apologetic grin, and holds the sheepish look",
    term: "ducks head sheepishly" },
  { id: "roll-head-full-circle", label: "Full Neck Roll", category: "head-gestures", description: "Head rolls in one full circle around the neck",
    promptHint: "the subject drops the chin toward the chest and rolls the head in one full circle, past one shoulder, tipping back, past the other shoulder and down to the chest again, before lifting the head upright",
    term: "rolls head in a full circle" },
]
