import type { CharacterMotion } from "./types.js"

/** idle-ambient — authored motion fragments. Stable ids survive copy revisions. */
export const IDLE_AMBIENT_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { "id": "breathe-visibly", "label": "Breathe visibly", "category": "idle-ambient", "description": "Chest rises and falls in a steady resting rhythm",
    "promptHint": "the subject holds still while the chest and shoulders rise on each inhale and sink back on each exhale in a steady resting rhythm, the rest of the body relaxed", "term": "breathes visibly at rest" },
  { "id": "sway-subtly", "label": "Sway subtly", "category": "idle-ambient", "description": "Barely-there side-to-side drift of a standing body",
    "promptHint": "the subject holds a standing position while the whole body drifts an inch or two to one side and back the other way in a barely visible balancing sway, feet planted", "term": "sways subtly in place" },
  { "id": "shift-weight", "label": "Shift weight", "category": "idle-ambient", "description": "Weight moves from one foot to the other and back",
    "promptHint": "the subject stands with weight on one leg, eases the pelvis across to load the other foot as the free knee softens, settles there, and drifts back again", "term": "shifts weight foot to foot" },
  { "id": "fidget-with-hands", "label": "Fidget with hands", "category": "idle-ambient", "description": "Restless small hand movements, fingers picking and rubbing",
    "promptHint": "the subject keeps both hands low in front of the body, fingers rubbing against each other, thumbs picking at the opposite palm and knuckles in restless small movements that never fully stop", "term": "fidgets with hands" },
  { "id": "blink-naturally", "label": "Blink naturally", "category": "idle-ambient", "description": "Relaxed natural blinks over a steady gaze",
    "promptHint": "the subject holds a steady gaze while the eyelids close and reopen in relaxed natural blinks at irregular intervals, the head and shoulders otherwise still", "term": "blinks naturally" },
  { "id": "look-around", "label": "Look around", "category": "idle-ambient", "description": "Eyes and head scan the surroundings side to side",
    "promptHint": "the subject turns the head to one side, eyes scanning the surroundings, brings it back through center and turns to the other side, gaze resting on each point of interest", "term": "looks around the space" },
  { "id": "tap-foot", "label": "Tap foot", "category": "idle-ambient", "description": "Heel planted, toes tap the ground in a steady beat",
    "promptHint": "the subject keeps one heel planted while the toes of that foot lift and tap back down against the ground in a steady beat, the leg bouncing slightly with each tap", "term": "taps a foot" },
  { "id": "drum-fingertips", "label": "Drum fingertips", "category": "idle-ambient", "description": "Fingertips ripple against a surface, pinky to index",
    "promptHint": "the subject rests one hand on a nearby surface and drums the fingertips against it in a rolling ripple from little finger to index, repeating the pattern absently in a loose restless rhythm", "term": "drums fingertips on a surface" },
  { "id": "adjust-clothes", "label": "Adjust clothes", "category": "idle-ambient", "description": "Tugs a hem, straightens a collar, smooths the front",
    "promptHint": "the subject tugs the hem of the garment down straight with both hands, smooths the front down over the torso, straightens the collar or strap with one hand and lets the arms drop back to rest", "term": "adjusts clothing" },
  { "id": "crack-neck", "label": "Crack neck", "category": "idle-ambient", "description": "Sharp head tilt to each side with a release",
    "promptHint": "the subject tips the head sharply toward one shoulder until it stops, brings it back to center and tips it to the other side, jaw loosening after each release", "term": "cracks the neck" },
  { "id": "roll-shoulders", "label": "Roll shoulders", "category": "idle-ambient", "description": "Shoulders lift, rotate back and drop in loose circles",
    "promptHint": "the subject lifts both shoulders up toward the ears, rolls them back and down in a loose circle and lets them drop, repeating the circle as the upper back loosens", "term": "rolls the shoulders" },
  { "id": "stretch-arms-overhead", "label": "Stretch arms overhead", "category": "idle-ambient", "description": "Reaches up, palms pushed upward, then releases",
    "promptHint": "the subject reaches both arms straight up overhead, interlaces the fingers and pushes the palms upward as the back arches, and releases the arms back down to the sides with the shoulders dropping", "term": "stretches arms overhead" },
  { "id": "pace-restlessly", "label": "Pace restlessly", "category": "idle-ambient", "description": "Short restless line walked one way, turned, walked back",
    "promptHint": "the subject walks a few restless steps in one direction, plants a foot, turns about and walks the same short line back the other way, hands clasped behind the back, repeating the circuit", "term": "paces restlessly in a short line" },
  { "id": "rock-on-heels", "label": "Rock on heels", "category": "idle-ambient", "description": "Weight rolls from heels to toes and back",
    "promptHint": "the subject stands with feet together and rolls the weight back onto the heels so the toes lift, tips forward onto the balls of the feet, and rocks back again, hands at rest", "term": "rocks heel to toe" },
  { "id": "fiddle-with-ring", "label": "Fiddle with ring", "category": "idle-ambient", "description": "Twists a ring around one finger, back and forth",
    "promptHint": "the subject holds the hands together low in front and turns a ring around one finger with the thumb and fingertips of the other hand, twisting it back and forth in an absent repeated motion", "term": "fiddles with a ring" },
  { "id": "bite-nail", "label": "Bite nail", "category": "idle-ambient", "description": "Raises a hand and nibbles at a fingernail",
    "promptHint": "the subject raises one hand to the mouth and nibbles at the edge of a fingernail, eyes drifting elsewhere, lowers the hand partway, and brings it back up to the lips again", "term": "bites a fingernail" },
  { "id": "hug-self-against-cold", "label": "Hug self against cold", "category": "idle-ambient", "description": "Arms wrap the torso, hands rub the upper arms for warmth",
    "promptHint": "the subject wraps both arms across the chest, grips the opposite upper arms and rubs them up and down for warmth, shoulders hunching and drawing in as the body tightens against the cold", "term": "hugs self against the cold" },
  { "id": "bounce-on-toes", "label": "Bounce on toes", "category": "idle-ambient", "description": "Light springy bounces on the balls of the feet",
    "promptHint": "the subject rises onto the balls of the feet and drops back down in light springy bounces, knees soft, heels barely touching the ground, arms loose at the sides", "term": "bounces on the toes" },
  { "id": "stretch-neck", "label": "Stretch neck", "category": "idle-ambient", "description": "Ear eases toward each shoulder in a long lean",
    "promptHint": "the subject leans the head to one side, ear easing toward the shoulder and holding the stretch, lifts it back through center and leans to the other side, shoulders staying level", "term": "stretches the neck side to side" },
  { "id": "glance-at-watch", "label": "Glance at watch", "category": "idle-ambient", "description": "Repeated wrist lift to check the time",
    "promptHint": "the subject lifts the wrist, turns it to glance down at a watch, drops the arm back to the side, looks up and away, and lifts the wrist to check the time again", "term": "glances at the watch repeatedly" },
  { "id": "exhale-and-settle", "label": "Exhale & settle", "category": "idle-ambient", "description": "Deep breath in, long breath out, shoulders drop",
    "promptHint": "the subject draws a deep breath that lifts the chest and shoulders, lets it out in a long exhale as the shoulders drop and the whole body softens into a settled stillness", "term": "exhales and settles" },
  { "id": "nod-to-music", "label": "Nod to music", "category": "idle-ambient", "description": "Head bobs in time with unheard music",
    "promptHint": "the subject bobs the head in a small steady down-up nod as if keeping time with music only they can hear, chin dipping on each beat, shoulders loose", "term": "nods along to unheard music" },
  { "id": "sway-eyes-closed", "label": "Sway with eyes closed", "category": "idle-ambient", "description": "Eyes shut, body rocks side to side in place",
    "promptHint": "the subject closes the eyes and lets the body rock from side to side in place, weight rolling foot to foot, head drifting with the motion and face relaxed", "term": "sways in place with eyes closed" },
  { "id": "twirl-hair", "label": "Twirl hair", "category": "idle-ambient", "description": "Winds a strand of hair around one finger",
    "promptHint": "the subject lifts one hand to a loose strand of hair, winds it around the index finger, lets it unwind and winds it again in an absent repeated motion, gaze elsewhere", "term": "twirls a strand of hair" },
  { "id": "knead-back-of-neck", "label": "Knead back of neck", "category": "idle-ambient", "description": "Hand reaches back to knead the neck, head dips",
    "promptHint": "the subject reaches one hand behind the head to grip the back of the neck, kneads it with the fingers as the head dips and the elbow points out, and lets the hand slide down", "term": "kneads the back of the neck" },
  { "id": "tuck-hair-behind-ear", "label": "Tuck hair behind ear", "category": "idle-ambient", "description": "Fingers sweep a strand back behind the ear",
    "promptHint": "the subject raises one hand to the face, sweeps a loose strand of hair back with the fingertips and tucks it behind the ear, and lets the hand drop back to the side", "term": "tucks hair behind the ear" },
  { "id": "wring-hands", "label": "Wring hands", "category": "idle-ambient", "description": "Hands clasp and twist over each other, restless",
    "promptHint": "the subject clasps both hands together in front of the body and wrings them, one hand twisting over the other, fingers sliding and interlacing, pressing and releasing in a restless repeated motion", "term": "wrings the hands" },
  { "id": "pop-knuckles", "label": "Pop knuckles", "category": "idle-ambient", "description": "Presses and flexes each hand's knuckles in turn",
    "promptHint": "the subject presses the fingers of one hand flat with the other, bends them back until the knuckles pop, swaps hands and does the same, and shakes both hands loose", "term": "pops the knuckles" },
  { "id": "cross-and-uncross-arms", "label": "Cross & uncross arms", "category": "idle-ambient", "description": "Arms fold across the chest, release, fold again",
    "promptHint": "the subject folds both arms across the chest, holds them there, lets them drop to the sides, and folds them again the other way round, torso settling with each change", "term": "crosses and uncrosses the arms" },
  { "id": "scuff-toe", "label": "Scuff toe", "category": "idle-ambient", "description": "Toe drags small arcs against the ground",
    "promptHint": "the subject keeps weight on one leg while the toe of the other foot drags small arcs back and forth against the ground, head tipped down toward it, hands at rest", "term": "scuffs a toe on the ground" },
  { "id": "shift-in-seat", "label": "Shift in seat", "category": "idle-ambient", "description": "Seated body resettles, legs recross",
    "promptHint": "the subject resettles in the seat, lifting the pelvis slightly to shift position, uncrossing and recrossing the legs and leaning back into a new resting posture", "term": "shifts in the seat" },
  { "id": "stifle-a-yawn", "label": "Stifle a yawn", "category": "idle-ambient", "description": "Mouth opens wide, hand covers it, eyes squeeze",
    "promptHint": "the subject opens the mouth wide in a yawn, raises one hand to cover it, eyes squeezing shut and head tipping back, and lets the hand drop as the jaw closes", "term": "stifles a yawn" },
  { "id": "shiver-tremble", "label": "Shiver & tremble", "category": "idle-ambient", "description": "Fine tremor runs through the body, shoulders drawn up",
    "promptHint": "the subject shivers, shoulders drawing up toward the ears and jaw tightening as a fine tremor runs through the arms and torso, hands shaking slightly and the body pulling in on itself", "term": "shivers and trembles" },
  { "id": "bounce-knee-seated", "label": "Bounce knee while seated", "category": "idle-ambient", "description": "Seated, one heel lifts and the knee jiggles up and down",
    "promptHint": "the subject sits with one heel lifted off the ground and bounces that knee up and down in a small restless jiggle driven from the ball of the foot, the rest of the body still", "term": "bounces a knee while seated" },
  { "id": "blow-hair-from-face", "label": "Blow hair from face", "category": "idle-ambient", "description": "Puffs air upward to lift a strand off the forehead",
    "promptHint": "the subject juts the lower lip forward and blows a puff of air upward so a loose strand of hair lifts off the forehead, flutters and drops back into place", "term": "blows a strand of hair from the face" },
  { "id": "swing-dangling-feet", "label": "Swing dangling feet", "category": "idle-ambient", "description": "Seated with feet hanging free, lower legs swing",
    "promptHint": "the subject sits with the feet dangling clear of the ground and swings the lower legs forward and back from the knees in an easy alternating rhythm, heels knocking lightly against the seat edge", "term": "swings dangling feet" },
  { "id": "twirl-pen", "label": "Twirl pen", "category": "idle-ambient", "description": "Flicks a pen around the thumb in a continuous spin",
    "promptHint": "the subject holds a pen between the fingers of one hand and flicks it around the thumb in a continuous spinning twirl, catching it each time it comes round and sending it spinning again", "term": "twirls a pen" },
  { "id": "spin-in-office-chair", "label": "Spin in office chair", "category": "idle-ambient", "description": "Pushes off to send a swivel chair round in a full turn",
    "promptHint": "the subject sits in a swivel chair, pushes off with one foot to send the chair round in a full spinning turn with the legs lifted clear, and drags a toe to stop facing forward again", "term": "spins in an office chair" },
  { "id": "nod-off-and-jerk-awake", "label": "Nod off & jerk awake", "category": "idle-ambient", "description": "Head sinks as eyes droop, then snaps upright with a jolt",
    "promptHint": "the subject nods off, eyelids drooping and head sinking forward until the chin nears the chest, and jerks awake with a jolt, head snapping upright and eyes flying open", "term": "nods off and jerks awake" },
  { "id": "rock-back-and-forth-huddled", "label": "Rock huddled", "category": "idle-ambient", "description": "Knees drawn up, arms around the shins, body rocks",
    "promptHint": "the subject sits huddled with the knees drawn up and arms wrapped around the shins, and rocks the whole body forward and back from the pelvis in a steady repeated motion, head bowed", "term": "rocks back and forth while huddled" },
  { "id": "blow-into-cupped-hands", "label": "Blow into cupped hands", "category": "idle-ambient", "description": "Cupped hands raised to the mouth, warmed with breath",
    "promptHint": "the subject raises both hands cupped together to the mouth, blows a long breath into the palms, rubs them against each other and blows into them again, shoulders hunched against the cold", "term": "blows into cupped hands" },
  { "id": "rock-back-and-forth", "label": "Rock in place", "category": "idle-ambient", "description": "Rocks the torso on one repeating beat",
    "promptHint": "the subject sits with the knees drawn up and rocks the torso forward and back on the same repeating beat, the arms wrapped around the shins and the gaze fixed on one spot", "term": "rocks back and forth in place" },
]
