import type { CharacterMotion } from "./types.js"

/** Posture Shifts — 46 entries. Category id `posture-shifts`. */
export const POSTURE_SHIFTS_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "sit-down-on-chair", label: "Sit on Chair", category: "posture-shifts", description: "Lowers from standing into a chair",
    promptHint: "the subject backs up to a chair, bends at the knees and waist, reaches one hand back to the seat and lowers their weight onto it, settling upright with both feet flat",
    term: "sits down on a chair" },
  { id: "sit-down-on-floor", label: "Sit on Floor", category: "posture-shifts", description: "Lowers from standing to sitting on the ground",
    promptHint: "the subject bends at the knees, drops one hand to the ground for support and lowers their pelvis to the floor, folding the legs in and settling into a seated position",
    term: "sits down on the floor" },
  { id: "stand-up-from-chair", label: "Stand from Chair", category: "posture-shifts", description: "Rises out of a chair to standing",
    promptHint: "the subject plants both feet, leans the torso forward over the knees, pushes down through the legs and rises out of the chair to full standing height, shoulders settling back",
    term: "stands up from a chair" },
  { id: "stand-up-from-floor", label: "Stand from Floor", category: "posture-shifts", description: "Rises from sitting on the ground to standing",
    promptHint: "the subject shifts their weight onto one hand and one foot, pushes up from the floor, brings the second foot under them and straightens to standing, brushing off their hands",
    term: "stands up from the floor" },
  { id: "kneel-down", label: "Kneel Down", category: "posture-shifts", description: "Lowers onto both knees",
    promptHint: "the subject lowers one knee to the ground and brings the second knee down beside it, settling into an upright kneeling position with hands resting on the thighs",
    term: "kneels down on both knees" },
  { id: "take-a-knee", label: "Take a Knee", category: "posture-shifts", description: "Drops onto one knee, other foot planted",
    promptHint: "the subject steps one foot forward, lowers the back knee to the ground and rests a forearm across the raised front thigh, holding the half-kneel with the torso upright",
    term: "takes a knee" },
  { id: "rise-from-kneeling", label: "Rise from Kneeling", category: "posture-shifts", description: "Stands up from a kneeling position",
    promptHint: "the subject brings one foot forward from a kneeling position, plants it flat, presses a hand to the raised knee and drives up through the legs to standing",
    term: "rises from kneeling" },
  { id: "sit-back-on-heels", label: "Sit Back on Heels", category: "posture-shifts", description: "Settles the pelvis onto the heels from kneeling",
    promptHint: "the subject lowers their pelvis back from an upright kneel to rest on the heels, hands settling on the thighs and the back staying straight in a seated kneel",
    term: "sits back on their heels" },
  { id: "crouch-down", label: "Crouch Down", category: "posture-shifts", description: "Drops low on bent knees, balanced on the toes",
    promptHint: "the subject bends deep at the knees and waist and drops into a low crouch, weight balanced on the balls of the feet, one hand touching the ground for balance",
    term: "drops into a crouch" },
  { id: "rise-from-crouch", label: "Rise from Crouch", category: "posture-shifts", description: "Straightens up from a low crouch",
    promptHint: "the subject pushes up through the legs from a low crouch, the hand leaving the ground and the torso unfolding upward until standing at full height, shoulders settling",
    term: "rises from a crouch" },
  { id: "squat-to-look", label: "Squat to Look", category: "posture-shifts", description: "Squats down to inspect something low",
    promptHint: "the subject bends at the knees and squats down level with something on the ground, forearms resting on the thighs and head tilting forward to inspect it closely",
    term: "squats down for a closer look" },
  { id: "jump-to-feet", label: "Jump to Feet", category: "posture-shifts", description: "Springs from the ground straight to standing",
    promptHint: "the subject pushes off the ground with both hands and feet in one burst, springing straight up from the floor to standing and landing balanced with knees slightly bent",
    term: "jumps to their feet" },
  { id: "lie-down-on-back", label: "Lie on Back", category: "posture-shifts", description: "Lowers from sitting to lying face-up",
    promptHint: "the subject leans back from sitting onto their elbows and lowers their back and head to the surface until lying flat face-up, legs extended and arms resting at the sides",
    term: "lies down on their back" },
  { id: "lie-down-on-side", label: "Lie on Side", category: "posture-shifts", description: "Lowers onto one side, knees bent",
    promptHint: "the subject lowers onto one hip and rolls onto their side, tucking the lower arm beneath their head as the knees bend and draw up and the body settles into a side-lying rest",
    term: "lies down on their side" },
  { id: "lie-down-on-stomach", label: "Lie on Stomach", category: "posture-shifts", description: "Lowers to lying face-down on folded arms",
    promptHint: "the subject walks their hands forward along the surface from kneeling and lowers their torso until lying face-down, propping the chin on folded forearms with legs stretched out behind",
    term: "lies down on their stomach" },
  { id: "roll-over", label: "Roll Over", category: "posture-shifts", description: "Turns from one side to the other while lying",
    promptHint: "the subject rolls from lying on one side across their back to the opposite side, lifting the top knee and shoulder to lead the turn and resettling with the other arm now on top",
    term: "rolls over onto the other side" },
  { id: "curl-up", label: "Curl Up", category: "posture-shifts", description: "Draws the knees to the chest while lying on one side",
    promptHint: "the subject draws both knees up toward the chest while lying on one side, wrapping the arms around the shins and tucking the chin down into a tight curl",
    term: "curls up on their side" },
  { id: "prop-up-on-elbow", label: "Prop on Elbow", category: "posture-shifts", description: "Lifts head and shoulders onto one elbow from lying",
    promptHint: "the subject lifts their head and shoulders off the surface and props the upper body up on one bent elbow, the other hand resting across the waist as the gaze comes level",
    term: "props up on one elbow" },
  { id: "get-up-from-lying", label: "Get Up from Lying", category: "posture-shifts", description: "Rises from lying flat all the way to standing",
    promptHint: "the subject rolls from lying flat onto one side, pushes up onto one hand into a seated position, brings the feet beneath them and rises to full standing height",
    term: "gets up from lying down" },
  { id: "sit-up-in-bed", label: "Sit Up in Bed", category: "posture-shifts", description: "Rises from lying to sitting against the pillows",
    promptHint: "the subject braces both palms against the mattress from lying in bed and curls the torso upward to sitting, shifting back to rest their shoulders against the pillows and headboard",
    term: "sits up in bed" },
  { id: "swing-legs-out-of-bed", label: "Legs Out of Bed", category: "posture-shifts", description: "Sits up and swings the feet to the floor",
    promptHint: "the subject pivots on their pelvis from sitting up in bed, swings both legs over the edge of the bed and plants their feet on the floor, settling seated on the edge with hands on the mattress",
    term: "swings legs out of bed" },
  { id: "wake-and-stretch", label: "Wake and Stretch", category: "posture-shifts", description: "Stretches arms overhead with a yawn on waking",
    promptHint: "the subject stirs from sleep, raises both arms overhead in a full-body stretch, yawning wide, and lets the arms drop back down as the eyes open",
    term: "stretches and yawns on waking" },
  { id: "flop-onto-bed", label: "Flop onto Bed", category: "posture-shifts", description: "Falls backward onto a bed, arms flung out",
    promptHint: "the subject stands at the edge of a bed, lets their knees go and falls backward onto the mattress, arms flung out to the sides, bouncing once and lying sprawled on their back",
    term: "flops backward onto the bed" },
  { id: "lean-back-in-chair", label: "Lean Back in Chair", category: "posture-shifts", description: "Eases the torso back against the chair back",
    promptHint: "the subject tips the torso backward from sitting upright until the shoulders sink into the chair back, hands coming to rest on the armrests and the chin lifting in a relaxed lean",
    term: "leans back in the chair" },
  { id: "plant-elbows-on-knees", label: "Elbows on Knees", category: "posture-shifts", description: "Leans forward, forearms braced on the thighs",
    promptHint: "the subject hinges the torso forward at the pelvis from sitting upright and plants both elbows on the knees, hands clasping loosely between the legs and the head lowering in attention",
    term: "leans forward, elbows on knees" },
  { id: "shift-to-edge-of-seat", label: "Edge of Seat", category: "posture-shifts", description: "Scoots forward to the front of the seat, alert",
    promptHint: "the subject slides their pelvis forward to the front edge of the seat, feet drawing back beneath them and the torso tilting forward, alert and ready to stand",
    term: "shifts to the edge of the seat" },
  { id: "cross-legs-seated", label: "Cross Legs", category: "posture-shifts", description: "Lifts one leg over the other while seated",
    promptHint: "the subject lifts one leg from sitting with both feet flat and lays it over the opposite knee, the foot hanging loose as the hands settle on the top thigh",
    term: "crosses one leg over the other" },
  { id: "uncross-and-stand", label: "Uncross & Stand", category: "posture-shifts", description: "Uncrosses the legs and rises to standing",
    promptHint: "the subject unhooks the crossed leg and sets both feet flat, leans the weight forward over the toes and rises from the seat to standing in one continuous motion",
    term: "uncrosses legs and stands up" },
  { id: "put-feet-up", label: "Put Feet Up", category: "posture-shifts", description: "Swings the feet up onto a table or ottoman",
    promptHint: "the subject leans back in the seat and lifts both legs, swinging the feet up onto a low table or ottoman and crossing the ankles, hands folding behind the head",
    term: "puts their feet up" },
  { id: "recline-back", label: "Recline", category: "posture-shifts", description: "Leans back until nearly lying, legs stretched out",
    promptHint: "the subject eases the torso backward from sitting upright until reclined at a low angle, legs stretching out in front and one arm folding behind the head as a rest",
    term: "reclines, legs stretched out" },
  { id: "settle-into-couch", label: "Settle into Couch", category: "posture-shifts", description: "Drops onto a couch and sinks into the cushions",
    promptHint: "the subject drops down onto a couch and sinks into the cushions, shifting the pelvis once to get comfortable and letting the arms spread along the back of the seat",
    term: "settles into a couch" },
  { id: "slump-down", label: "Slump", category: "posture-shifts", description: "Sags down, shoulders and head dropping",
    promptHint: "the subject lets the shoulders roll forward and drop, the spine rounding and the head sinking as the whole body sags lower, arms going loose at the sides",
    term: "slumps, shoulders dropping" },
  { id: "straighten-up", label: "Straighten Up", category: "posture-shifts", description: "Pulls the spine tall, shoulders back",
    promptHint: "the subject draws the spine upright from a slouch, pulling the shoulders back and down, lifting the chin and squaring the chest until sitting or standing fully tall",
    term: "straightens up, shoulders back" },
  { id: "perch-on-table-edge", label: "Perch on Table", category: "posture-shifts", description: "Rests the pelvis against a table edge, legs out",
    promptHint: "the subject backs up to a table, rests their pelvis against its edge and leans the weight onto it, legs extended forward and crossed at the ankles, hands gripping the edge",
    term: "perches on the edge of a table" },
  { id: "hop-onto-counter", label: "Hop onto Counter", category: "posture-shifts", description: "Boosts up to sit on a counter, feet dangling",
    promptHint: "the subject faces away from a counter, plants both palms on its surface behind them and hops up to sit on it, legs dangling and heels swinging free above the floor",
    term: "hops up to sit on a counter" },
  { id: "lean-against-wall", label: "Lean on Wall", category: "posture-shifts", description: "Settles one shoulder against a wall",
    promptHint: "the subject steps up to a wall, turns and settles one shoulder into it, the weight sinking into the lean as the ankles cross and the arms fold across the chest",
    term: "leans a shoulder against the wall" },
  { id: "push-off-wall", label: "Push Off Wall", category: "posture-shifts", description: "Straightens off a wall lean to standing free",
    promptHint: "the subject presses the shoulder into the wall and pushes off it, uncrossing the ankles and stepping away as the body straightens to a free-standing posture",
    term: "pushes off the wall" },
  { id: "slide-down-wall", label: "Slide Down Wall", category: "posture-shifts", description: "Slides down a wall to sit on the floor",
    promptHint: "the subject leans their back against a wall and lets the knees bend, sliding down the surface until seated on the floor with knees drawn up and forearms resting on them",
    term: "slides down the wall to the floor" },
  { id: "lean-on-counter", label: "Lean on Counter", category: "posture-shifts", description: "Rests both forearms on a counter or bar",
    promptHint: "the subject steps up to a counter, plants both forearms flat on it and lets the weight settle forward onto the elbows, hands clasping loosely and one foot hooking behind the other",
    term: "leans onto the counter on both forearms" },
  { id: "brace-hands-on-knees", label: "Hands on Knees", category: "posture-shifts", description: "Bends over and braces the hands on the knees",
    promptHint: "the subject bends forward at the waist and braces both hands on the knees, the back rounding and the head hanging low as the arms take the weight of the torso",
    term: "bends over, hands on knees" },
  { id: "snap-to-attention", label: "Snap to Attention", category: "posture-shifts", description: "Snaps upright, heels together, arms at the sides",
    promptHint: "the subject snaps upright, clicking the heels together and driving both arms straight down to the sides, chest lifting and chin level as the body locks into a rigid stance",
    term: "snaps to attention, heels together" },
  { id: "rise-on-tiptoes", label: "Rise on Tiptoes", category: "posture-shifts", description: "Rises on the toes to see over a crowd",
    promptHint: "the subject rises onto the balls of the feet, heels lifting off the ground and the neck stretching tall to see over the heads in front, arms held close for balance",
    term: "rises on tiptoes to see over a crowd" },
  { id: "lean-on-railing", label: "Lean on Railing", category: "posture-shifts", description: "Rests the forearms on a railing, gazing out",
    promptHint: "the subject steps up to a railing, lays both forearms along the top rail and lets the weight settle forward onto them, hands loosely clasped as the gaze goes out beyond",
    term: "leans on a railing on both forearms" },
  { id: "settle-into-meditation", label: "Settle into Meditation", category: "posture-shifts", description: "Sits cross-legged, spine tall, eyes closing",
    promptHint: "the subject lowers to the floor and folds the legs into a cross-legged seat, straightening the spine, resting the backs of the hands on the knees and letting the eyes close",
    term: "settles cross-legged into meditation" },
  { id: "lace-hands-behind-head", label: "Hands Behind Head", category: "posture-shifts", description: "Leans back, fingers laced behind the head",
    promptHint: "the subject leans back in the chair and laces the fingers behind the head, elbows flaring wide as the weight settles into the chair back and the chest opens",
    term: "leans back, fingers laced behind head" },
  { id: "drop-head-onto-desk", label: "Head onto Desk", category: "posture-shifts", description: "Folds forward and drops the head onto the desk",
    promptHint: "the subject folds forward from sitting and lets the forehead drop onto the desk between the outstretched arms, going limp with shoulders sagging and the arms lying flat on the surface",
    term: "drops head onto the desk" },
]
