import type { CharacterMotion } from "./types.js"

/** Runway & Model — 32 entries. Category id `runway`. */
export const RUNWAY_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "walk-the-runway", label: "Runway Walk", category: "runway", description: "Straight-line catwalk, one foot in front of the other",
    promptHint: "the subject walks a straight line toward the camera, each foot landing directly in front of the other, one hip leading each stride, shoulders back, arms swinging loosely at the sides, gaze locked ahead",
    term: "walks the runway, feet landing in one line" },
  { id: "walk-mark-and-turn", label: "Walk & Turn", category: "runway", description: "Reach the end mark, hold a beat, turn and walk back",
    promptHint: "the subject walks to the end mark, plants both feet and holds a beat squared to the camera, pivots a half turn on the ball of the front foot and walks back the way they came",
    term: "walks to the mark, turns and walks back" },
  { id: "pivot-mid-stride", label: "Mid-Stride Pivot", category: "runway", description: "Unbroken half-turn on the ball of the foot, no pause",
    promptHint: "the subject reverses direction mid-walk without breaking rhythm, the lead foot planting and the body pivoting a half turn on the ball of that foot as the trailing leg swings through into the next stride",
    term: "pivots mid-stride and returns" },
  { id: "stomp-editorial-walk", label: "Editorial Stomp", category: "runway", description: "Heavy heel-first strides, knees driving, arms rigid",
    promptHint: "the subject strides forward driving each heel hard into the floor, knees lifting high and punching down, torso rigid and arms held straight and stiff at the sides, chin level and jaw set",
    term: "stomps forward in an editorial walk" },
  { id: "sway-hips-walk", label: "Hip-Sway Walk", category: "runway", description: "Exaggerated hip swing on every step",
    promptHint: "the subject walks toward the camera with an exaggerated sway, the hips rolling side to side on every step, each foot crossing in front of the other, shoulders countering the swing and one hand trailing along the thigh",
    term: "walks with an exaggerated hip sway", adultOnly: true },
  { id: "stalk-high-fashion-walk", label: "High-Fashion Walk", category: "runway", description: "Rigid torso, pinned arms, long stiff strides, blank face",
    promptHint: "the subject takes long stiff strides with the torso held perfectly rigid, arms pinned straight at the sides barely moving, face blank and gaze fixed past the camera, the legs doing all the work",
    term: "walks rigid and stiff, arms pinned at sides" },
  { id: "stop-and-pose", label: "Stop & Pose", category: "runway", description: "Plant, shift weight back, chin up, hold, walk on",
    promptHint: "the subject walks forward, plants both feet and stops, shifts the weight onto the back leg with the front knee softening, squares the shoulders to the camera and lifts the chin, holds the shape, and walks on",
    term: "stops and hits a pose" },
  { id: "land-hand-on-hip", label: "Hand-on-Hip Stop", category: "runway", description: "Arrive, one hand rises to the hip, elbow out",
    promptHint: "the subject arrives at the mark and plants the feet as one hand rises and lands on the hip with the elbow angled out, the opposite arm hanging loose, weight settling onto one leg",
    term: "stops, one hand landing on the hip" },
  { id: "flip-the-hair", label: "Hair Flip", category: "runway", description: "Head dips and whips over, hair arcs and settles",
    promptHint: "the subject dips the head down and to one side and whips it up and over, the hair arcing through the air in a full sweep before falling and settling back across the shoulders",
    term: "flips the hair over" },
  { id: "sweep-hair-back", label: "Hair Sweep Back", category: "runway", description: "One hand rakes the hair off the face while walking",
    promptHint: "the subject brings one hand up to the forehead while walking and rakes the fingers back through the hair, pulling it off the face and letting it fall behind the shoulder without breaking stride",
    term: "sweeps the hair back with one hand" },
  { id: "drop-coat-off-shoulders", label: "Coat Drop Reveal", category: "runway", description: "Shrug the coat off and let it fall to reveal the outfit",
    promptHint: "the subject shrugs both shoulders back so the coat slides down the arms, catches it at the elbows for a beat and lets it drop to the floor behind, revealing the outfit underneath",
    term: "drops the coat off the shoulders", adultOnly: true },
  { id: "hook-jacket-over-shoulder", label: "Jacket Over Shoulder", category: "runway", description: "Shrug off the jacket and hook it over one shoulder",
    promptHint: "the subject slips one arm then the other out of the jacket while walking, gathers it in one hand and hooks it over the shoulder on a finger, the free arm swinging with the stride",
    term: "hooks the jacket over one shoulder" },
  { id: "pause-look-over-shoulder", label: "Over-the-Shoulder Pause", category: "runway", description: "Walk away, stop, look back over the shoulder, hold",
    promptHint: "the subject walks away from the camera, stops, and turns the head back over one shoulder to look at the lens, the body still facing away, holding the look before walking on",
    term: "pauses and looks back over the shoulder" },
  { id: "sultry-look-back", label: "Sultry Look Back", category: "runway", description: "Chin to shoulder, half-lidded gaze back at the lens",
    promptHint: "the subject walks away, rolls one shoulder back and drops the chin toward it, turning a half-lidded sultry gaze back over the shoulder at the camera, lips parted, before walking on",
    term: "throws a sultry look back over the shoulder", adultOnly: true },
  { id: "turn-full-circle", label: "Full Turn", category: "runway", description: "Rotate a full circle in place to show every side",
    promptHint: "the subject rotates a full circle in place, stepping the feet around in small pivots with arms held slightly away from the body so the outfit is seen from every side, finishing squared to the camera",
    term: "turns a full circle to show the outfit" },
  { id: "take-sunglasses-off", label: "Sunglasses Off", category: "runway", description: "Slide the sunglasses off and lower them, eyes to lens",
    promptHint: "the subject reaches up with one hand, grips the sunglasses by one arm and slides them off the face, lowering them to chest height as the eyes lift and lock onto the camera",
    term: "takes the sunglasses off" },
  { id: "push-sunglasses-onto-head", label: "Sunglasses Up", category: "runway", description: "One finger lifts the sunglasses off the eyes onto the crown",
    promptHint: "the subject raises one hand to the bridge of the sunglasses and pushes them up off the eyes, sliding them back to seat on the crown of the head, then drops the hand as the eyes settle on the camera",
    term: "pushes the sunglasses up onto the head" },
  { id: "swing-the-bag", label: "Bag Swing", category: "runway", description: "Handbag swings from one hand with the stride",
    promptHint: "the subject walks with a handbag held in one hand, the arm swinging it forward and back in a wide arc with each stride while the other arm swings free in counter-rhythm",
    term: "swings the bag with the stride" },
  { id: "campaign-walk-to-camera", label: "Campaign Walk", category: "runway", description: "Walk straight at the lens from far to close, gaze locked",
    promptHint: "the subject walks directly toward the camera from a distance, gaze locked on the lens the whole way, stride long and even, arms swinging naturally, stopping just short of the lens",
    term: "walks straight at the camera, gaze locked" },
  { id: "walk-away-from-camera", label: "Walk Away", category: "runway", description: "Back to camera, walk off into the distance",
    promptHint: "the subject turns their back to the camera and walks away in a straight line into the distance, shoulders square, arms swinging evenly, without looking back",
    term: "walks away, back to camera" },
  { id: "sweep-the-gown", label: "Gown Sweep", category: "runway", description: "Long strides with the hem trailing, a turn flares the train",
    promptHint: "the subject walks with long strides so the floor-length hem trails behind, gathers the skirt in one hand, turns on the spot and swings the gathered skirt around so the train sweeps across the floor",
    term: "sweeps the gown train through a turn" },
  { id: "bounce-streetwear-walk", label: "Streetwear Bounce", category: "runway", description: "Loose bouncy walk, shoulders rolling, hands in pockets",
    promptHint: "the subject walks with a loose bounce, dipping on each step and rolling the shoulders, both hands tucked into the pockets, head nodding to an internal beat",
    term: "walks with a streetwear bounce" },
  { id: "stride-menswear-walk", label: "Menswear Stride", category: "runway", description: "Long even stride, shoulders square, one hand in pocket",
    promptHint: "the subject takes long even strides with shoulders square and chest open, one hand resting in a trouser pocket and the other arm swinging naturally, gaze level and steady ahead",
    term: "strides with one hand in the pocket" },
  { id: "twirl-the-skirt", label: "Skirt Twirl", category: "runway", description: "Rise onto the toes and spin so the skirt flares out",
    promptHint: "the subject rises onto the balls of the feet and spins a full turn in place, arms lifting slightly as the skirt flares outward, and settles back down onto the heels facing the camera",
    term: "twirls so the skirt flares" },
  { id: "adjust-the-cuff", label: "Cuff Adjust", category: "runway", description: "Tug a shirt cuff straight below the sleeve mid-stride",
    promptHint: "the subject brings one hand across to the opposite wrist mid-stride, tugs the shirt cuff straight so it shows just below the jacket sleeve, and drops the arm back into its swing without breaking the stride",
    term: "adjusts the cuff mid-stride" },
  { id: "adjust-lapels", label: "Lapel Adjust", category: "runway", description: "Both hands grip the lapels and tug them square",
    promptHint: "the subject raises both hands to the jacket lapels, grips one in each hand and tugs them down and outward so the jacket sits square on the shoulders, then rolls the shoulders once and drops the hands to the sides",
    term: "tugs both lapels square" },
  { id: "button-jacket", label: "Button Jacket", category: "runway", description: "Draw the jacket fronts together and fasten the button",
    promptHint: "the subject stands tall and draws the two fronts of the jacket together with both hands, works the button through the buttonhole with the fingers, smooths the front flat with one palm and drops both hands to the sides",
    term: "buttons the jacket closed" },
  { id: "unbutton-jacket-walking", label: "Unbutton Jacket", category: "runway", description: "Pop the jacket button open mid-stride, fronts fall loose",
    promptHint: "the subject reaches one hand to the jacket button while walking, pushes it back through the buttonhole with the thumb so the two fronts fall open and swing loose, and lets the hand drop back into its stride",
    term: "unbuttons the jacket mid-stride" },
  { id: "pop-the-collar", label: "Collar Pop", category: "runway", description: "Both hands flick the collar up to stand against the neck",
    promptHint: "the subject brings both hands up to the collar, grips the points between the fingers and flicks them upward so the collar stands stiff against the neck, then drops the hands and lifts the chin",
    term: "pops the collar up" },
  { id: "throw-open-coat", label: "Coat Throw Open", category: "runway", description: "Grip the coat fronts and swing them wide, outfit in view",
    promptHint: "the subject grips the two fronts of the coat, one in each hand, and swings them wide apart, both arms held out to the sides so the outfit underneath is in full view, holding the coat open for a beat",
    term: "throws the coat open" },
  { id: "cycle-through-three-poses", label: "Three-Pose Cycle", category: "runway", description: "Hit three poses in a row, shifting weight and arms each beat",
    promptHint: "the subject hits three poses in succession, shifting the weight from one leg to the other on each beat and repositioning the arms and head, holding each shape for a beat before flowing into the next",
    term: "cycles through three poses" },
  { id: "walk-with-partner", label: "Duo Walk", category: "runway", description: "Walk side by side with a partner in matched stride",
    promptHint: "the subject walks side by side with the partner in matched stride, feet landing together, both planting at the mark and pivoting outward in mirror image before walking back",
    term: "walks in step with the partner", twoPerson: true },
]
