import type { CharacterMotion } from "./types.js"

/** Stage & Performance — 42 entries. Category id `stage-performance`. */
export const STAGE_PERFORMANCE_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "sing-into-handheld-mic", label: "Sing Into Handheld Mic", category: "stage-performance", description: "Lifts the mic and sings, free hand riding the phrasing",
    promptHint: "the subject lifts a handheld microphone to their mouth and sings into it, free hand rising and falling with the phrasing, weight shifting foot to foot with the beat",
    term: "sings into a handheld mic" },
  { id: "sing-at-stand-mic", label: "Sing at Stand Mic", category: "stage-performance", description: "Steps up to a stand mic and leans in to sing",
    promptHint: "the subject steps up to a stand microphone, wraps one hand around the stand and leans in close to the mic, singing with their chin lifted toward the crowd",
    term: "sings into a stand mic" },
  { id: "belt-high-note", label: "Belt a High Note", category: "stage-performance", description: "Deep breath, head back, arm up on the big note",
    promptHint: "the subject plants their feet, fills their chest with a deep breath and belts a high note, head tipping back, free arm rising to full extension before the note releases",
    term: "belts a high note with head thrown back" },
  { id: "hold-note-eyes-closed", label: "Hold Note Eyes Closed", category: "stage-performance", description: "Eyes close, hand on chest, one long sustained note",
    promptHint: "the subject closes their eyes, draws a breath and holds one long sustained note into the mic, a hand pressed flat over their chest until the note releases and their eyes open",
    term: "holds a long note with eyes closed" },
  { id: "hold-mic-to-crowd", label: "Mic Out to Crowd", category: "stage-performance", description: "Holds the mic out so the audience sings the line",
    promptHint: "the subject holds the handheld mic out toward the audience at arm's length, tilting it to the crowd and cupping the other hand to their ear to hear the line sung back",
    term: "holds the mic out to the crowd" },
  { id: "rap-into-mic", label: "Rap Into the Mic", category: "stage-performance", description: "Raps into the mic, free hand chopping every bar",
    promptHint: "the subject raps into a handheld mic, free hand chopping and bouncing in time with every bar, shoulders rocking and body leaning out toward the crowd on the punchlines",
    term: "raps into the mic with a chopping hand" },
  { id: "strum-guitar", label: "Strum Guitar", category: "stage-performance", description: "Strums on the beat, fretting hand changing chords",
    promptHint: "the subject strums a guitar slung across their body, strumming hand sweeping down across the strings on the beat while the fretting hand shifts between chords, head nodding with the rhythm",
    term: "strums a guitar on the beat" },
  { id: "lean-into-guitar-solo", label: "Guitar Solo Lean", category: "stage-performance", description: "Arches back into a solo, fretting hand racing",
    promptHint: "the subject leans back into a guitar solo, fretting hand racing up the neck as the picking hand tears across the strings, torso arching backward with one foot planted forward",
    term: "leans back into a guitar solo" },
  { id: "drop-to-knee-solo", label: "Knee-Drop Solo", category: "stage-performance", description: "Drops to one knee mid-solo, then pushes back up",
    promptHint: "the subject drops down onto one knee mid-solo, guitar neck tilted up toward the crowd, fretting hand climbing to the highest frets before they push back up to standing",
    term: "drops to one knee mid-solo" },
  { id: "play-air-guitar", label: "Air Guitar", category: "stage-performance", description: "Grips an invisible neck, windmills the other hand",
    promptHint: "the subject plays air guitar, one hand gripping an invisible neck while the other windmills across an invisible body, face contorting and knees bouncing with the riff",
    term: "plays air guitar" },
  { id: "smash-guitar", label: "Smash Guitar", category: "stage-performance", description: "Raises the guitar overhead and smashes it into the stage",
    promptHint: "the subject grips the guitar by the neck, raises it high overhead with both hands and swings it down hard into the stage floor, hoisting it up and smashing it down again before flinging the neck aside",
    term: "smashes a guitar on the stage" },
  { id: "play-drums", label: "Play Drums", category: "stage-performance", description: "Sticks between snare and cymbals, foot on the kick",
    promptHint: "the subject sits at a drum kit and plays, sticks alternating between snare and cymbals, one foot driving the kick pedal, shoulders rocking with the beat and hair swinging",
    term: "plays the drums" },
  { id: "play-piano", label: "Play Piano", category: "stage-performance", description: "Both hands across the keys, body swaying",
    promptHint: "the subject sits at a piano and plays, both hands moving across the keys, body swaying with the phrasing and head dipping toward the keyboard on the heavier chords",
    term: "plays the piano" },
  { id: "play-violin", label: "Play Violin", category: "stage-performance", description: "Bow arm sweeps the strings, fingers walking the neck",
    promptHint: "the subject tucks a violin under their chin and plays, bowing arm drawing the bow back and forth across the strings while the fingering hand walks up and down the neck, torso swaying with each phrase",
    term: "plays the violin" },
  { id: "play-saxophone", label: "Play Saxophone", category: "stage-performance", description: "Fingers work the keys, bell dipping on the low notes",
    promptHint: "the subject plays a saxophone hanging from a neck strap, fingers working the keys as their cheeks fill with each breath, leaning back on the high notes and dipping the bell forward on the low ones",
    term: "plays the saxophone" },
  { id: "work-the-decks", label: "DJ at the Decks", category: "stage-performance", description: "Headphone to ear, other hand on the faders",
    promptHint: "the subject works the DJ decks, one hand pressing a headphone cup to their ear while the other rides the mixer faders and cues the next track, head bobbing to the beat",
    term: "works the decks with headphone to one ear" },
  { id: "conduct-orchestra", label: "Conduct Orchestra", category: "stage-performance", description: "Baton carves the beat, left hand swells and cuts",
    promptHint: "the subject faces the orchestra and conducts, baton hand carving the beat pattern in the air while the other hand rises to swell the sound and drops to cut it off",
    term: "conducts an orchestra with a baton" },
  { id: "walk-to-center-stage", label: "Walk to Center Stage", category: "stage-performance", description: "Walks from the wings to the mark, arms opening",
    promptHint: "the subject walks from the wings out to center stage, steps steady and shoulders squared, stopping on the mark and opening both arms out toward the audience",
    term: "walks out to center stage" },
  { id: "strut-down-runway", label: "Strut the Runway", category: "stage-performance", description: "Straight-line strut down the stage runway",
    promptHint: "the subject struts down the stage runway toward the crowd, feet landing in a straight line and arms swinging with purpose, stopping at the end to face the audience",
    term: "struts down the stage runway" },
  { id: "step-up-to-podium", label: "Step Up to Podium", category: "stage-performance", description: "Steps behind the lectern and grips both sides",
    promptHint: "the subject walks up to a podium, steps onto the riser behind it and grips both sides of the lectern with their hands, squaring their shoulders and lifting their chin to face the room",
    term: "steps up to the podium and grips it" },
  { id: "sit-on-stage-edge", label: "Sit on Stage Edge", category: "stage-performance", description: "Sits on the lip of the stage to sing the verse",
    promptHint: "the subject walks to the lip of the stage, sits down on the edge with legs hanging over toward the crowd and sings the verse into the mic, leaning toward the front row",
    term: "sits on the stage edge to sing" },
  { id: "raise-hands-to-crowd", label: "Raise Hands to Crowd", category: "stage-performance", description: "Both arms straight overhead, palms open",
    promptHint: "the subject raises both arms straight overhead toward the crowd, palms open, holding them high while turning from one side of the audience to the other",
    term: "raises both hands to the crowd" },
  { id: "hype-the-crowd", label: "Hype the Crowd", category: "stage-performance", description: "Claps overhead on the beat, urging the crowd",
    promptHint: "the subject hypes the crowd, clapping both hands together above their head in time with the beat and bouncing on their toes, urging the audience to clap along",
    term: "claps overhead to hype the crowd" },
  { id: "point-to-crowd", label: "Point to Crowd", category: "stage-performance", description: "Snaps a point into the crowd and sweeps it",
    promptHint: "the subject snaps one arm out and points into the crowd, holding the point on one section of the audience before sweeping the finger across to the other side",
    term: "points out into the crowd" },
  { id: "wave-to-crowd", label: "Wave to Crowd", category: "stage-performance", description: "Wide overhead wave across the whole audience",
    promptHint: "the subject raises one arm high and waves to the crowd in wide side-to-side sweeps, turning their body to cover the whole audience from one side to the other",
    term: "waves to the crowd" },
  { id: "blow-kisses-to-crowd", label: "Blow Kisses", category: "stage-performance", description: "Fingertips to lips, kisses thrown to each side",
    promptHint: "the subject presses their fingertips to their lips and blows kisses out to the crowd, arm extending toward the audience with each one, alternating sides",
    term: "blows kisses to the crowd" },
  { id: "hold-phone-light-aloft", label: "Phone Light Aloft", category: "stage-performance", description: "Phone held high, screen out, whole body swaying",
    promptHint: "the subject raises one arm straight up with a phone held high, screen light facing the stage, and sways from side to side with the whole body while the other arm rests loosely at their side",
    term: "holds a phone light aloft and sways" },
  { id: "jump-on-the-beat", label: "Jump on the Beat", category: "stage-performance", description: "Both feet off the stage on every downbeat",
    promptHint: "the subject bounces on their toes and jumps straight up on every downbeat, both feet leaving the stage, one arm pumping overhead with each landing",
    term: "jumps on the beat" },
  { id: "headbang-on-beat", label: "Headbang on Beat", category: "stage-performance", description: "Head whips down and up on every beat, hair flying",
    promptHint: "the subject headbangs, whipping their head down toward their chest and back up on every beat, hair flying, shoulders driving the motion and knees bending with each drop",
    term: "headbangs on the beat" },
  { id: "knee-slide-across-stage", label: "Knee Slide", category: "stage-performance", description: "Runs and drops into a knee slide across the stage",
    promptHint: "the subject takes a few running steps and drops into a knee slide across the stage floor, both knees down, torso leaning back and arms thrown up, sliding to a stop facing the crowd",
    term: "drops into a knee slide across the stage" },
  { id: "hit-dance-break", label: "Dance Break", category: "stage-performance", description: "Plants the mic and hits an eight-count for the crowd",
    promptHint: "the subject plants the mic in its stand and hits a sharp dance break facing the crowd, arms and feet snapping through the eight-count in sync before returning to the mic",
    term: "hits a dance break on stage" },
  { id: "freeze-on-the-drop", label: "Freeze on the Drop", category: "stage-performance", description: "Snaps into a pose on the drop and holds it dead still",
    promptHint: "the subject dances loosely on the beat, arms and hips swinging, and on the drop snaps into a sharp pose, every limb frozen dead still, holding the freeze before releasing back into motion",
    term: "freezes in a pose on the drop" },
  { id: "spin-mic-stand", label: "Spin the Mic Stand", category: "stage-performance", description: "Swings the stand a full circle and catches it",
    promptHint: "the subject grabs the mic stand by the shaft, swings it around in a full circle with one hand and catches it upright, leaning straight back in to sing into the mic",
    term: "spins the mic stand" },
  { id: "drop-the-mic", label: "Mic Drop", category: "stage-performance", description: "Holds the mic out, opens the hand, lets it fall",
    promptHint: "the subject finishes the last line, holds the handheld mic out to the side at arm's length, opens their hand and lets it fall to the stage floor before turning away",
    term: "drops the mic" },
  { id: "jump-into-crowd", label: "Jump Into Crowd", category: "stage-performance", description: "Feet-first leap off the stage edge into the crowd",
    promptHint: "the subject runs to the lip of the stage and leaps feet-first off the edge into the crowd, arms flung wide, landing on the raised hands of the audience",
    term: "leaps off the stage into the crowd" },
  { id: "stage-dive", label: "Stage Dive", category: "stage-performance", description: "Horizontal dive onto the crowd's raised hands",
    promptHint: "the subject launches horizontally off the front of the stage in a stage dive, arms spread and body flat, dropping onto the raised hands of the front row",
    term: "dives off the stage onto the crowd" },
  { id: "crowd-surf", label: "Crowd Surf", category: "stage-performance", description: "Carried on their back hand to hand over the audience",
    promptHint: "the subject crowd surfs on their back across the audience, arms spread wide and legs loose, carried and rolled hand to hand over the sea of raised arms, head lifting to look toward the stage",
    term: "crowd surfs" },
  { id: "bow-to-audience", label: "Bow to Audience", category: "stage-performance", description: "Deep bow from the waist at the front of the stage",
    promptHint: "the subject steps forward to the front of the stage, one hand across their stomach, and bows deeply from the waist to the audience, rising back up with a smile",
    term: "bows to the audience" },
  { id: "take-curtain-call", label: "Curtain Call", category: "stage-performance", description: "Returns through the curtain, bows, credits the band",
    promptHint: "the subject walks back out through the curtain for a curtain call, arms spread wide to the applause, takes a bow and gestures back toward the band behind them",
    term: "takes a curtain call" },
  { id: "walk-off-waving", label: "Walk Off Waving", category: "stage-performance", description: "Exits toward the wings waving over the shoulder",
    promptHint: "the subject turns away from the crowd and walks off stage toward the wings, one arm raised high and waving back over their shoulder until they pass out of view",
    term: "walks off stage waving" },
  { id: "share-mic-duet", label: "Share a Mic", category: "stage-performance", description: "Two singers lean in on one mic for the chorus",
    promptHint: "the subject and the partner lean in toward one shared handheld mic from opposite sides, shoulders touching, singing the chorus together and pulling apart on the final note",
    term: "shares one mic with the partner", twoPerson: true },
  { id: "shred-back-to-back", label: "Back-to-Back Solo", category: "stage-performance", description: "Two guitarists press backs together and shred",
    promptHint: "the subject and the partner press their backs together and play a dual guitar solo, both leaning into each other for support as their fretting hands race up the necks",
    term: "shreds guitar back to back with the partner", twoPerson: true },
]
