import type { CharacterMotion } from "./types.js"

/** Turns & Looks — 37 entries. Category id `turns-looks`. */
export const TURNS_LOOKS_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "turn-to-camera", label: "Body Turn to Camera", category: "turns-looks", description: "Full body turn from back to front, ending square to camera",
    promptHint: "the subject turns from back-to-camera around to face front, stepping the feet through the rotation, shoulders squaring to the camera and weight settling evenly on both feet",
    term: "turns around to face camera" },
  { id: "turn-away-from-camera", label: "Body Turn Away", category: "turns-looks", description: "Full body turn from front to back, ending facing away",
    promptHint: "the subject rotates the whole body away from the camera until the back is to the lens, the feet stepping through the turn and the head following last",
    term: "turns away from camera" },
  { id: "quarter-turn-to-profile", label: "Quarter Turn to Profile", category: "turns-looks", description: "Body rotates a quarter turn from front to a side profile",
    promptHint: "the subject rotates the body a quarter turn from square-to-camera to one side, ending in a clean side profile with the feet realigned and the gaze forward along the new facing",
    term: "quarter-turns to profile" },
  { id: "turn-profile-to-camera", label: "Turn Profile to Camera", category: "turns-looks", description: "Side profile rotates to face the camera square-on",
    promptHint: "the subject rotates from side profile toward the camera, the near shoulder opening first and the face coming around last, until the subject is square to the lens",
    term: "turns from profile to camera" },
  { id: "spin-full-360", label: "Full 360 Spin", category: "turns-looks", description: "One complete rotation on the spot, ending facing camera",
    promptHint: "the subject rotates a full circle on the spot, arms held loose and hair and clothing fanning outward, and comes to a stop facing the camera again",
    term: "spins a full 360 on the spot" },
  { id: "pivot-on-heel", label: "Pivot on Heel", category: "turns-looks", description: "Sharp about-face pivoting on one heel",
    promptHint: "the subject plants weight on one heel and pivots the whole body a sharp half turn to face the opposite way, the free foot swinging around to land beside the other",
    term: "pivots on heel to face opposite way" },
  { id: "twist-to-look-behind", label: "Twist to Look Behind", category: "turns-looks", description: "Torso twists and head turns to check what is behind",
    promptHint: "the subject twists the torso and turns the head to look behind, one foot stepping back to open the stance, and holds the look on whatever is behind",
    term: "twists torso to look behind" },
  { id: "turn-to-face-partner", label: "Turn to Face Partner", category: "turns-looks", description: "Body turns to square off face to face with a partner",
    promptHint: "the subject turns the body toward the partner, feet shifting and shoulders squaring off, until the subject and the partner stand face to face",
    term: "turns to face the partner", twoPerson: true },
  { id: "turn-head-to-camera", label: "Turn Head to Camera", category: "turns-looks", description: "Head-only turn from the side to face the camera",
    promptHint: "the subject rotates the head on the neck from one side to the camera in one continuous motion until the face is square to the lens, the eyes arriving on the lens last",
    term: "turns head to camera" },
  { id: "snap-head-to-camera", label: "Snap Head to Camera", category: "turns-looks", description: "Head whips to camera in one sharp jerk, body still",
    promptHint: "the subject whips the head from off to one side around to the camera in a single sharp jerk, the body staying still and the eyes locking straight at the lens",
    term: "snaps head to camera" },
  { id: "turn-head-away", label: "Turn Head Away", category: "turns-looks", description: "Head-only turn from camera to a side profile",
    promptHint: "the subject rotates the head from the camera to one side until the profile is presented, the gaze leaving the lens and the shoulders staying square",
    term: "turns head away from camera" },
  { id: "look-over-left-shoulder", label: "Look Over Left Shoulder", category: "turns-looks", description: "Head turns over the left shoulder toward camera",
    promptHint: "the subject turns the head to look back over the left shoulder while keeping the back to the camera, until the face comes into view in three-quarter profile, the body staying put",
    term: "looks back over left shoulder" },
  { id: "look-over-right-shoulder", label: "Look Over Right Shoulder", category: "turns-looks", description: "Head turns over the right shoulder toward camera",
    promptHint: "the subject turns the head to look back over the right shoulder while keeping the back to the camera, until the face comes into view in three-quarter profile, the body staying put",
    term: "looks back over right shoulder" },
  { id: "glance-back", label: "Glance Back", category: "turns-looks", description: "Brief check over the shoulder, then back to front",
    promptHint: "the subject flicks the head over one shoulder to check behind, the eyes catching something, and returns the head to face front again",
    term: "glances back over shoulder" },
  { id: "double-take", label: "Double Take", category: "turns-looks", description: "Look away, then snap back to it in disbelief",
    promptHint: "the subject glances at something, looks away, and snaps the head back to it as the eyes widen in a classic double take, the body going still",
    term: "does a double take" },
  { id: "chin-lift-to-camera", label: "Chin Lift to Camera", category: "turns-looks", description: "Chin rises from a lowered head to meet the camera",
    promptHint: "the subject raises the chin from a lowered head and lifts the gaze to meet the camera directly, the neck extending and the eyes landing on the lens",
    term: "lifts chin and eyes to camera" },
  { id: "scan-surroundings", label: "Scan Surroundings", category: "turns-looks", description: "Head sweeps side to side, eyes checking the space",
    promptHint: "the subject sweeps the gaze across the surroundings, the head turning from one side to the other in a continuous scan, the eyes checking each point before coming to rest",
    term: "scans the surroundings" },
  { id: "head-follows-across-frame", label: "Head Follows Across Frame", category: "turns-looks", description: "Head turns to track something crossing the frame",
    promptHint: "the subject turns the head to follow something passing in front, tracking it from one side of the frame to the other, and holds the gaze where it exits",
    term: "turns head to track something passing" },
  { id: "look-at-partner", label: "Look at Partner", category: "turns-looks", description: "Head-only turn to meet a partner's eyes",
    promptHint: "the subject turns the head toward the partner, the eyes finding the partner's face and holding there while the body stays still",
    term: "turns head to look at the partner", twoPerson: true },
  { id: "sultry-look-over-shoulder", label: "Sultry Over-Shoulder Look", category: "turns-looks", description: "Seductive over-the-shoulder look back at camera",
    promptHint: "the subject keeps the body facing away and turns the head over one shoulder toward the camera with lowered eyelids and a knowing half-smile, the chin dipping toward the shoulder as the gaze lands",
    term: "throws a sultry look over the shoulder", adultOnly: true },
  { id: "look-up", label: "Look Up", category: "turns-looks", description: "Gaze lifts from the ground to above the frame",
    promptHint: "the subject lifts the gaze from the ground to above the top of the frame, tipping the head back so the chin rises and the throat lengthens, and holds the upward look",
    term: "looks up" },
  { id: "look-down", label: "Look Down", category: "turns-looks", description: "Gaze drops from level to the ground",
    promptHint: "the subject drops the gaze from level to the ground, lowering the chin toward the chest until the eyes settle on the floor, the shoulders softening",
    term: "looks down" },
  { id: "look-off-screen-left", label: "Look Off Left", category: "turns-looks", description: "Head and eyes turn to something out of frame left",
    promptHint: "the subject turns the head and eyes toward frame left to fix on something out of frame on that side, the body staying square to camera",
    term: "looks off-screen left" },
  { id: "look-off-screen-right", label: "Look Off Right", category: "turns-looks", description: "Head and eyes turn to something out of frame right",
    promptHint: "the subject turns the head and eyes toward frame right to fix on something out of frame on that side, the body staying square to camera",
    term: "looks off-screen right" },
  { id: "eyes-track-across-frame", label: "Eyes Track Across Frame", category: "turns-looks", description: "Eyes follow something across frame, head nearly still",
    promptHint: "the subject keeps the head nearly still while the eyes follow something moving across the frame from one side to the other, the head drifting only slightly to keep pace",
    term: "tracks something across frame with eyes only" },
  { id: "eyes-flick-to-camera", label: "Flick Eyes to Camera", category: "turns-looks", description: "Only the eyes move to lock onto the camera",
    promptHint: "the subject keeps the head turned slightly off and still and shifts only the eyes to the camera, the gaze locking straight down the lens without the head moving",
    term: "flicks eyes to camera" },
  { id: "side-eye-glance", label: "Side-Eye Glance", category: "turns-looks", description: "Eyes slide sideways without turning the head",
    promptHint: "the subject keeps the head facing forward and slides the eyes hard to one side toward something off-frame without turning the head, holding the sidelong look",
    term: "throws a side-eye glance" },
  { id: "break-eye-contact", label: "Break Eye Contact", category: "turns-looks", description: "Held eye contact drops away, face turning aside",
    promptHint: "the subject drops the eyes from the camera and turns the face slightly aside, breaking the look and settling the gaze somewhere low and away",
    term: "breaks eye contact" },
  { id: "tilt-head-curiously", label: "Tilt Head Curiously", category: "turns-looks", description: "Head tips toward one shoulder, eyes staying on the target",
    promptHint: "the subject tips the head toward one shoulder in a curious tilt, the ear dropping toward the shoulder while the eyes stay fixed on what is in front, and holds the tilt",
    term: "tilts head curiously to one side" },
  { id: "peek-around-corner", label: "Peek Around Corner", category: "turns-looks", description: "Leans the head out past an edge to check, body stays hidden",
    promptHint: "the subject leans the upper body sideways to bring one eye and the edge of the face past a corner, one hand braced on the wall, the feet staying planted behind cover",
    term: "leans out to peek around a corner" },
  { id: "look-back-and-forth", label: "Look Back and Forth", category: "turns-looks", description: "Head swings between two points, weighing them up",
    promptHint: "the subject swings the head from one point to another and back again in repeated turns, the eyes landing on each in turn as if weighing them up, the body staying still",
    term: "looks back and forth between two points" },
  { id: "snap-look-toward-sound", label: "Snap Head Toward Sound", category: "turns-looks", description: "Head snaps toward an off-screen noise, body freezing",
    promptHint: "the subject snaps the head toward an off-screen sound in one sharp turn, the body going still and the eyes fixing hard on the direction it came from",
    term: "snaps head toward an off-screen sound" },
  { id: "look-partner-up-and-down", label: "Look Partner Over", category: "turns-looks", description: "Once-over of the partner, eyes traveling down then up",
    promptHint: "the subject runs the eyes down the partner from face to feet and back up again in one deliberate once-over, the head dipping and lifting to follow, the body staying still",
    term: "looks the partner up and down", twoPerson: true },
  { id: "look-at-own-hands", label: "Look at Own Hands", category: "turns-looks", description: "Raises both hands and stares at them in realization",
    promptHint: "the subject raises both hands into view in front of the face, palms turning up and over, and stares at them with the eyes widening, the head dropping slightly to study them",
    term: "stares at own raised hands" },
  { id: "push-back-hood-reveal", label: "Push Back Hood", category: "turns-looks", description: "Hood slides back and the face lifts into view",
    promptHint: "the subject reaches up with both hands and pushes the hood back off the head, the fabric sliding down onto the shoulders as the chin lifts and the face rises into view",
    term: "pushes back hood and lifts face" },
  { id: "peer-over-glasses", label: "Peer Over Glasses", category: "turns-looks", description: "Glasses slide down the nose, eyes look over the rims",
    promptHint: "the subject hooks one finger on the bridge of the glasses and slides them down the nose, the chin dipping so the eyes look out over the top of the rims",
    term: "pulls glasses down and peers over them" },
  { id: "peer-through-door-crack", label: "Peer Through Door Crack", category: "turns-looks", description: "Door opens a crack and one eye looks through the gap",
    promptHint: "the subject eases the door open a narrow crack with one hand and brings the face to the gap, one eye peering through while the rest of the body stays behind the door",
    term: "opens door a crack and peers through" },
]
