import type { CharacterMotion } from "./types.js"

/** Two-Person — 76 entries. Category id `two-person`. */
export const TWO_PERSON_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "hug-partner", label: "Hug", category: "two-person", description: "Steps in, wraps arms around the partner, releases",
    promptHint: "the subject steps toward the partner, opens both arms and wraps them around the partner's back in a firm hug, holds the hug, and loosens the arms to step back",
    term: "hugs the partner", twoPerson: true },
  { id: "embrace-partner", label: "Long Embrace", category: "two-person", description: "Full hold, chin on shoulder, swaying, no release",
    promptHint: "the subject draws the partner into a full embrace, arms wrapped around the partner's back, chin resting on the partner's shoulder, both bodies swaying side to side as the hold continues without releasing",
    term: "holds the partner in a long embrace", twoPerson: true },
  { id: "hug-partner-from-behind", label: "Hug From Behind", category: "two-person", description: "Arms around the waist, chin on the shoulder",
    promptHint: "the subject walks up behind the partner, slides both arms around the partner's waist and rests the chin on the partner's shoulder, the partner leaning back into the hold",
    term: "hugs the partner from behind", adultOnly: true, twoPerson: true },
  { id: "bro-hug", label: "Bro Hug", category: "two-person", description: "Handshake pulled into a one-arm hug with a pat",
    promptHint: "the subject clasps the partner's hand in a handshake, pulls the partner in by that hand and wraps the free arm around the partner's back with a pat, then releases and steps back",
    term: "pulls the partner into a one-arm hug", twoPerson: true },
  { id: "run-into-partner-arms", label: "Run Into Arms", category: "two-person", description: "Runs, leaps, and is caught in a lifted hug",
    promptHint: "the subject runs toward the partner, leaps in the final stride and wraps arms around the partner's neck, and the partner catches the subject and holds the lifted hug",
    term: "runs and leaps into the partner's arms", twoPerson: true },
  { id: "bury-face-in-partner-shoulder", label: "Bury Face", category: "two-person", description: "Face pressed into the partner's shoulder, gripping",
    promptHint: "the subject steps into the partner and buries the face against the partner's shoulder, shoulders heaving, hands gripping the back of the partner's clothing as the partner's arms close around",
    term: "buries face in the partner's shoulder", twoPerson: true },
  { id: "shake-partner-hand", label: "Handshake", category: "two-person", description: "Extends a hand, grips and pumps twice, lets go",
    promptHint: "the subject extends the right hand toward the partner, the partner grips it, and the two pump the clasped hands up and down twice before letting go and dropping the arms",
    term: "shakes hands with the partner", twoPerson: true },
  { id: "high-five-partner", label: "High Five", category: "two-person", description: "Raised open palms slap together and rebound",
    promptHint: "the subject raises an open hand above shoulder height and swings it forward to slap palms with the partner's raised hand in a crisp high five, both hands rebounding after contact",
    term: "high-fives the partner", twoPerson: true },
  { id: "fist-bump-partner", label: "Fist Bump", category: "two-person", description: "Knuckles meet at chest height with a light tap",
    promptHint: "the subject makes a fist and extends it forward at chest height, the partner's fist meets it knuckle to knuckle with a light tap, and both fists pull back",
    term: "fist-bumps the partner", twoPerson: true },
  { id: "chest-bump-partner", label: "Chest Bump", category: "two-person", description: "Both hop in and bump chests mid-air",
    promptHint: "the subject hops toward the partner with the chest thrust forward, the partner hopping to meet it, the two bumping chest to chest in mid-air and landing back on their feet",
    term: "chest bumps the partner", twoPerson: true },
  { id: "pinky-promise", label: "Pinky Promise", category: "two-person", description: "Little fingers hook and shake once",
    promptHint: "the subject raises one hand with the little finger extended, the partner hooks a little finger around it, and the two shake the linked fingers up and down once",
    term: "hooks pinkies with the partner", twoPerson: true },
  { id: "bow-to-partner", label: "Bow to Partner", category: "two-person", description: "Bends from the waist, the partner returns the bow",
    promptHint: "the subject faces the partner, brings the feet together and bends forward from the waist in a respectful bow, holds it, and straightens as the partner returns the bow",
    term: "bows to the partner", twoPerson: true },
  { id: "toast-with-partner", label: "Toast", category: "two-person", description: "Glasses raised and clinked, then a drink",
    promptHint: "the subject raises a glass toward the partner, the partner lifts a glass to meet it, and the two glasses clink at chest height before each pulls the glass back to drink",
    term: "clinks glasses with the partner", twoPerson: true },
  { id: "kiss-partner-cheek", label: "Kiss on the Cheek", category: "two-person", description: "Leans in, kisses the partner's cheek, leans back",
    promptHint: "the subject leans in toward the partner, tilts the head slightly, presses a kiss to the partner's cheek, and leans back upright",
    term: "kisses the partner on the cheek", twoPerson: true },
  { id: "kiss-partner-forehead", label: "Forehead Kiss", category: "two-person", description: "Tilts the partner's head down, kisses the forehead",
    promptHint: "the subject draws the partner in, tilts the partner's head down slightly with one hand and presses a kiss to the partner's forehead, then leans back",
    term: "kisses the partner's forehead", twoPerson: true },
  { id: "lean-in-almost-kiss", label: "Almost Kiss", category: "two-person", description: "Leans in until lips nearly touch, and holds there",
    promptHint: "the subject leans in toward the partner until the lips are a breath apart, eyes dropping to the partner's mouth, and holds there without closing the last inch",
    term: "almost kisses the partner", adultOnly: true, twoPerson: true },
  { id: "kiss-partner", label: "Kiss", category: "two-person", description: "Leans in, kisses the partner on the lips, parts",
    promptHint: "the subject leans in toward the partner, tilts the head and presses the lips to the partner's lips in a kiss, eyes closing, then eases back until the two part",
    term: "kisses the partner", adultOnly: true, twoPerson: true },
  { id: "rise-on-tiptoes-to-kiss-partner", label: "Tiptoe Kiss", category: "two-person", description: "Rises on tiptoes to reach a taller partner's lips",
    promptHint: "the subject rises onto tiptoes in front of the partner, hands on the partner's shoulders for balance, and presses a kiss up to the partner's lips before settling back onto flat feet",
    term: "rises on tiptoes to kiss the partner", adultOnly: true, twoPerson: true },
  { id: "cup-partner-face", label: "Cup Face", category: "two-person", description: "Both palms cup the partner's cheeks, holding the gaze",
    promptHint: "the subject raises both hands to the partner's face and cups the cheeks in the palms, thumbs resting below the partner's eyes, holding the partner's gaze",
    term: "cups the partner's face", twoPerson: true },
  { id: "lift-partner-chin", label: "Lift Chin", category: "two-person", description: "A curled finger tilts the partner's lowered face up",
    promptHint: "the subject slides one curled finger under the partner's chin and lifts it until the partner's lowered face tilts up to meet the subject's eyes",
    term: "lifts the partner's chin", twoPerson: true },
  { id: "tuck-partner-hair-behind-ear", label: "Tuck Partner's Hair Back", category: "two-person", description: "Catches a loose strand and tucks it behind the ear",
    promptHint: "the subject reaches up with one hand, catches a loose strand of the partner's hair with the fingertips and tucks it back behind the partner's ear, the hand lingering at the temple",
    term: "tucks the partner's hair behind the ear", twoPerson: true },
  { id: "wipe-partner-tear", label: "Wipe Away a Tear", category: "two-person", description: "Thumb brushes a tear from the partner's cheek",
    promptHint: "the subject raises one hand to the partner's face and brushes a tear from the partner's cheek with the thumb, the palm resting against the partner's jaw as the partner looks up",
    term: "wipes a tear from the partner's cheek", twoPerson: true },
  { id: "touch-foreheads-with-partner", label: "Forehead Touch", category: "two-person", description: "Foreheads rest together, eyes closed, holding still",
    promptHint: "the subject leans in until the foreheads rest together, both closing their eyes, the subject's hands on the partner's shoulders, the two holding still together",
    term: "touches foreheads with the partner", twoPerson: true },
  { id: "rest-head-on-partner-shoulder", label: "Head on Shoulder", category: "two-person", description: "Leans sideways, head settling on the partner's shoulder",
    promptHint: "the subject leans sideways toward the partner and lowers the head until it rests on the partner's shoulder, eyes closing, the partner's cheek settling against the top of the subject's head",
    term: "rests head on the partner's shoulder", twoPerson: true },
  { id: "rest-head-in-partner-lap", label: "Head in Lap", category: "two-person", description: "Lies down and rests the head in the partner's lap",
    promptHint: "the subject lies down sideways along a seat and lowers the head to rest in the partner's lap, face turned upward, the partner's hand settling on the subject's hair",
    term: "rests head in the partner's lap", twoPerson: true },
  { id: "hold-partner-hand", label: "Hold Hands", category: "two-person", description: "Finds the partner's hand and laces fingers",
    promptHint: "the subject reaches sideways, finds the partner's hand and laces the fingers together, the joined hands settling between them as the two stand side by side",
    term: "holds hands with the partner", twoPerson: true },
  { id: "walk-hand-in-hand", label: "Walk Hand in Hand", category: "two-person", description: "Walks beside the partner with hands clasped",
    promptHint: "the subject walks forward beside the partner with their hands clasped between them, the joined arms swinging lightly with each matched step",
    term: "walks hand in hand with the partner", twoPerson: true },
  { id: "walk-arm-in-arm", label: "Walk Arm in Arm", category: "two-person", description: "Arms linked at the elbow, walking in step",
    promptHint: "the subject hooks one arm through the partner's arm at the elbow and the two walk forward in step together, shoulders close, arms linked the whole way",
    term: "walks arm in arm with the partner", twoPerson: true },
  { id: "lead-partner-by-hand", label: "Lead by the Hand", category: "two-person", description: "Walks ahead pulling the partner along by the hand",
    promptHint: "the subject takes the partner's hand and walks ahead, arm stretched back, pulling the partner along a half step behind as the two move forward together",
    term: "leads the partner by the hand", twoPerson: true },
  { id: "bump-shoulders-walking", label: "Shoulder Bump", category: "two-person", description: "Playful sideways nudge while walking together",
    promptHint: "the subject walks beside the partner and leans sideways to knock shoulders with the partner in a playful nudge, both rocking apart and settling back into stride",
    term: "bumps shoulders with the partner while walking", twoPerson: true },
  { id: "sit-down-together", label: "Sit Down Together", category: "two-person", description: "Both sit down side by side, shoulder to shoulder",
    promptHint: "the subject sits down on a seat and the partner sits down beside the subject, both settling shoulder to shoulder and facing the same direction",
    term: "sits down beside the partner", twoPerson: true },
  { id: "pull-out-chair-for-partner", label: "Pull Out Chair", category: "two-person", description: "Draws a chair out and slides it in as the partner sits",
    promptHint: "the subject steps to a chair, grips its back and draws it out from the table, and slides it back in under the partner as the partner sits down",
    term: "pulls out a chair for the partner", twoPerson: true },
  { id: "hold-door-for-partner", label: "Hold the Door", category: "two-person", description: "Opens a door and holds it as the partner walks through",
    promptHint: "the subject reaches the door first, pulls it open and steps aside holding it with one arm extended, and the partner walks through ahead of the subject",
    term: "holds the door for the partner", twoPerson: true },
  { id: "drape-jacket-over-partner", label: "Drape Jacket", category: "two-person", description: "Shrugs off a jacket and drapes it over the partner",
    promptHint: "the subject shrugs off a jacket, holds it open by the shoulders and drapes it over the partner's shoulders from behind, smoothing it down the partner's arms",
    term: "drapes a jacket over the partner's shoulders", twoPerson: true },
  { id: "straighten-partner-tie", label: "Straighten Partner's Tie", category: "two-person", description: "Centers the partner's tie knot and smooths it flat",
    promptHint: "the subject steps in front of the partner, takes the knot of the partner's tie in both hands, centers it with a small tug and smooths the tie flat down the partner's chest",
    term: "straightens the partner's tie", twoPerson: true },
  { id: "feed-partner-a-bite", label: "Feed a Bite", category: "two-person", description: "Lifts a bite to the partner's mouth, hand cupped below",
    promptHint: "the subject lifts a bite of food toward the partner's mouth with one hand, the other hand cupped beneath to catch drips, and the partner leans in to take the bite",
    term: "feeds the partner a bite", twoPerson: true },
  { id: "hand-partner-object", label: "Hand Over Object", category: "two-person", description: "Holds out an object, the partner takes it",
    promptHint: "the subject holds out an object toward the partner with one hand, the partner reaches to take it, and the subject lets go once the partner's grip is on it",
    term: "hands the partner an object", twoPerson: true },
  { id: "receive-object", label: "Receive Object", category: "two-person", description: "Takes an offered object and draws it in",
    promptHint: "the subject reaches out with an open hand as the partner offers an object, closes the fingers around it and draws it back in toward the body",
    term: "takes an object from the partner", twoPerson: true },
  { id: "slide-ring-onto-partner-finger", label: "Slide On Ring", category: "two-person", description: "Slides a ring down onto the partner's ring finger",
    promptHint: "the subject takes the partner's hand, holds a ring at the fingertip and slides it down onto the partner's ring finger, then closes both hands around the partner's hand",
    term: "slides a ring onto the partner's finger", twoPerson: true },
  { id: "lift-partner-veil", label: "Lift Veil", category: "two-person", description: "Lifts the veil up and back to reveal the face",
    promptHint: "the subject raises both hands to the edge of the partner's veil, lifts it up and back over the partner's head, and lowers the hands to reveal the partner's face",
    term: "lifts the partner's veil", twoPerson: true },
  { id: "kneel-before-partner", label: "Kneel Before", category: "two-person", description: "Drops to one knee and takes the partner's hand",
    promptHint: "the subject drops down onto one knee in front of the partner, takes the partner's hand in both hands and looks up at the partner's face, the partner's free hand rising to the mouth",
    term: "kneels on one knee before the partner", twoPerson: true },
  { id: "kneel-to-partner-eye-level", label: "Kneel to Eye Level", category: "two-person", description: "Lowers to one knee to meet a shorter partner's eyes",
    promptHint: "the subject lowers onto one knee in front of the partner until their eyes are level, hands resting on the raised knee, and speaks to the partner face to face",
    term: "kneels to the partner's eye level", twoPerson: true },
  { id: "tap-partner-shoulder", label: "Tap on Shoulder", category: "two-person", description: "Two taps from behind, the partner turns around",
    promptHint: "the subject steps up behind the partner, raises one hand and taps the partner's shoulder twice with the fingertips, and the partner turns around to face the subject",
    term: "taps the partner on the shoulder", twoPerson: true },
  { id: "put-hand-on-partner-shoulder", label: "Hand on Shoulder", category: "two-person", description: "Rests a hand on the partner's shoulder with a squeeze",
    promptHint: "the subject steps to the partner's side, raises one hand and rests it on the partner's shoulder with a firm squeeze, holding it there while looking at the partner",
    term: "places a hand on the partner's shoulder", twoPerson: true },
  { id: "pat-partner-back", label: "Pat on the Back", category: "two-person", description: "Open-palm pats on the partner's upper back",
    promptHint: "the subject reaches over and pats the partner firmly on the upper back three times with an open palm, before dropping the hand",
    term: "pats the partner on the back", twoPerson: true },
  { id: "whisper-to-partner", label: "Whisper", category: "two-person", description: "Leans in and whispers into the partner's ear",
    promptHint: "the subject leans in close to the side of the partner's head, cups a hand beside the mouth and whispers into the partner's ear, and the partner's expression shifts while listening",
    term: "whispers in the partner's ear", twoPerson: true },
  { id: "cover-partner-eyes-from-behind", label: "Cover Eyes", category: "two-person", description: "Sneaks up behind and covers the partner's eyes",
    promptHint: "the subject creeps up behind the partner, reaches around with both hands and covers the partner's eyes with the palms, the partner's hands rising to touch the subject's fingers",
    term: "covers the partner's eyes from behind", twoPerson: true },
  { id: "boop-partner-nose", label: "Boop Nose", category: "two-person", description: "Index finger taps the tip of the partner's nose",
    promptHint: "the subject raises one hand with the index finger extended and taps the tip of the partner's nose with a light press, then pulls the hand back as the partner scrunches the face",
    term: "boops the partner's nose", twoPerson: true },
  { id: "ruffle-partner-hair", label: "Ruffle Hair", category: "two-person", description: "Rubs a hand across the partner's head, messing the hair",
    promptHint: "the subject reaches over and rubs an open hand back and forth across the top of the partner's head, ruffling the partner's hair into disarray, and pulls the hand away",
    term: "ruffles the partner's hair", twoPerson: true },
  { id: "tickle-partner", label: "Tickle", category: "two-person", description: "Fingers wiggle at the ribs, the partner twists away",
    promptHint: "the subject reaches for the partner's sides with both hands and wiggles the fingers against the partner's ribs, the partner doubling over and twisting away laughing",
    term: "tickles the partner", twoPerson: true },
  { id: "shake-partner-awake", label: "Shake Awake", category: "two-person", description: "Grips and shakes a sleeping partner's shoulder",
    promptHint: "the subject leans over the partner lying asleep, grips the partner's shoulder and shakes it insistently until the partner's eyes open and the partner jolts upright",
    term: "shakes the partner awake", twoPerson: true },
  { id: "lift-partner", label: "Lift", category: "two-person", description: "Hands at the waist, lifts straight up, sets down",
    promptHint: "the subject grips the partner at the waist with both hands, bends the knees and lifts the partner straight up off the ground, the partner's hands on the subject's shoulders, and lowers the partner back down",
    term: "lifts the partner off the ground", twoPerson: true },
  { id: "swing-partner-around", label: "Swing Around", category: "two-person", description: "Lifts the partner and turns a full circle",
    promptHint: "the subject wraps both arms around the partner's waist, lifts the partner off the ground and turns in a full circle with the partner's feet swinging outward, before setting the partner down",
    term: "lifts and swings the partner around", twoPerson: true },
  { id: "lift-partner-overhead-airplane", label: "Airplane Lift", category: "two-person", description: "Lifts a small partner overhead, held flat, arms wide",
    promptHint: "the subject grips the partner under the arms, lifts the partner overhead at full arm extension so the partner's body lies flat with arms spread wide, and lowers the partner back down",
    term: "lifts the partner overhead like an airplane", twoPerson: true },
  { id: "carry-partner-bridal", label: "Bridal Carry", category: "two-person", description: "Scoops the partner up and walks forward",
    promptHint: "the subject scoops the partner up in a bridal carry, one arm under the partner's knees and the other behind the partner's back, the partner's arm around the subject's neck, and walks forward carrying the partner",
    term: "carries the partner bridal-style", twoPerson: true },
  { id: "piggyback-partner", label: "Piggyback", category: "two-person", description: "Crouches, the partner climbs on, stands and walks",
    promptHint: "the subject crouches, the partner climbs onto the subject's back with arms around the subject's shoulders, and the subject hooks both hands under the partner's knees, stands up and walks forward",
    term: "carries the partner piggyback", twoPerson: true },
  { id: "carry-partner-on-shoulders", label: "Shoulder Ride", category: "two-person", description: "The partner rides astride the neck, carried forward",
    promptHint: "the subject crouches, the partner climbs onto the subject's shoulders with one leg either side of the neck, and the subject holds the partner's shins and stands up to walk forward",
    term: "carries the partner on the shoulders", twoPerson: true },
  { id: "fireman-carry-partner", label: "Fireman Carry", category: "two-person", description: "Hoists the partner across the shoulders and walks",
    promptHint: "the subject ducks under the partner's arm, hoists the partner across the shoulders with the partner's torso behind the neck and legs hanging in front, and stands to walk forward",
    term: "carries the partner over one shoulder", twoPerson: true },
  { id: "help-partner-up", label: "Help Up", category: "two-person", description: "Pulls the partner up from the ground to standing",
    promptHint: "the subject extends a hand down to the partner on the ground, the partner grips the subject's forearm, and the subject leans back and pulls the partner up to standing",
    term: "helps the partner up", twoPerson: true },
  { id: "catch-partner-falling", label: "Catch a Fall", category: "two-person", description: "Lunges and catches the partner as they fall",
    promptHint: "the subject lunges forward as the partner loses balance and falls, catching the partner under the arms and around the back, taking the partner's weight and steadying the partner upright",
    term: "catches the partner mid-fall", twoPerson: true },
  { id: "support-injured-partner-walking", label: "Support Limping", category: "two-person", description: "Takes a limping partner's weight, arm over shoulder",
    promptHint: "the subject drapes the partner's arm over the subject's shoulders, wraps an arm around the partner's waist and takes the partner's weight as the partner limps, the two walking forward in a lurching step",
    term: "helps the partner limp along", twoPerson: true },
  { id: "drag-partner-to-safety", label: "Drag to Safety", category: "two-person", description: "Hauls the partner backward under the arms",
    promptHint: "the subject hooks both hands under the partner's arms from behind and drags the partner backward across the ground, the partner's heels trailing, the subject leaning back and hauling step by step",
    term: "drags the partner to safety", twoPerson: true },
  { id: "shield-partner-with-body", label: "Shield", category: "two-person", description: "Pulls the partner behind and blocks with the body",
    promptHint: "the subject grabs the partner's arm, swings the partner around behind the subject's back and plants the feet wide, one arm held out across the partner as a shield",
    term: "shields the partner with the body", twoPerson: true },
  { id: "pull-partner-close", label: "Pull Close", category: "two-person", description: "Draws the partner in until chest to chest",
    promptHint: "the subject grasps the partner's hand and pulls the partner in until the two are chest to chest, the partner's body turning to face the subject as the gap closes",
    term: "pulls the partner close", adultOnly: true, twoPerson: true },
  { id: "catch-partner-wrist", label: "Catch Wrist", category: "two-person", description: "Stops the partner leaving by catching the wrist",
    promptHint: "the subject reaches out as the partner turns to walk away and catches the partner's wrist, halting the partner mid-step so the partner turns back to face the subject",
    term: "catches the partner's wrist", twoPerson: true },
  { id: "chase-partner", label: "Chase", category: "two-person", description: "Runs after the partner, closing the gap",
    promptHint: "the subject runs after the partner, who sprints ahead across the frame glancing back, the subject pumping the arms and closing the gap stride by stride",
    term: "chases the partner", twoPerson: true },
  { id: "stare-down-partner", label: "Stare Down Partner", category: "two-person", description: "Face to face, inches apart, unbroken stare",
    promptHint: "the subject steps in to stand face to face with the partner, inches apart, and holds an unbroken stare into the partner's eyes, neither of them moving",
    term: "stares down the partner face to face", twoPerson: true },
  { id: "argue-in-partner-face", label: "Argue in Face", category: "two-person", description: "Nose to nose, jabbing a finger, both shouting",
    promptHint: "the subject steps in nose to nose with the partner, jabbing a finger at the partner's chest and shouting, the partner shouting back, neither giving ground",
    term: "argues in the partner's face", twoPerson: true },
  { id: "push-partner-away", label: "Push Away", category: "two-person", description: "Both palms to the chest, the partner steps back",
    promptHint: "the subject plants both palms on the partner's chest and pushes the partner away, the partner stepping back to absorb it, while the subject holds the arms out to keep the distance",
    term: "pushes the partner away", twoPerson: true },
  { id: "shove-partner", label: "Shove Partner", category: "two-person", description: "Two-handed shove, the partner staggers back",
    promptHint: "the subject lunges forward and shoves the partner hard in the shoulders with both hands, the partner staggering back several steps and catching balance while the subject squares up",
    term: "shoves the partner back", twoPerson: true },
  { id: "shake-partner-shoulders", label: "Shake by Shoulders", category: "two-person", description: "Grabs both shoulders and shakes back and forth",
    promptHint: "the subject grabs the partner by both shoulders and shakes the partner back and forth, the partner's head rocking with each shake, before releasing the grip",
    term: "grabs and shakes the partner by the shoulders", twoPerson: true },
  { id: "grab-partner-collar", label: "Grab Collar", category: "two-person", description: "Seizes the collar in both fists and yanks in close",
    promptHint: "the subject seizes the partner's collar with both fists and yanks the partner in close, the partner's heels lifting as the subject holds the partner up at eye level",
    term: "grabs the partner by the collar", twoPerson: true },
  { id: "pin-partner-against-wall", label: "Pin Against Wall", category: "two-person", description: "Backs the partner into the wall, forearm across chest",
    promptHint: "the subject drives the partner back until the partner's shoulders meet the wall, plants one forearm across the partner's chest and the other palm flat on the wall beside the partner's head",
    term: "pins the partner against the wall", twoPerson: true },
  { id: "slap-partner", label: "Slap", category: "two-person", description: "Open hand across the cheek, the head snaps aside",
    promptHint: "the subject swings one open hand across the partner's cheek in a sharp slap, the partner's head snapping to the side, and the subject lowers the hand",
    term: "slaps the partner across the face", twoPerson: true },
  { id: "arm-wrestle-partner", label: "Arm Wrestle", category: "two-person", description: "Elbows planted, hands locked, straining to win",
    promptHint: "the subject plants an elbow on the table, locks hands with the partner and strains to force the partner's arm down, both arms trembling as the clasped hands tip toward the subject's side",
    term: "arm wrestles the partner", twoPerson: true },
  { id: "restrain-partner", label: "Restrain", category: "two-person", description: "Hauls the straining partner back from behind",
    promptHint: "the subject wraps both arms around the partner from behind and hauls the partner back as the partner strains forward, the partner's feet scrabbling, the subject planting the feet and pulling the partner away",
    term: "holds the partner back from behind", twoPerson: true },
]
