import type { CharacterMotion } from "./types.js"

/** unnatural-horror — authored motion fragments. Stable ids survive copy revisions. */
export const UNNATURAL_HORROR_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { "id": "twitch-head-sideways", "label": "Head twitch", "category": "unnatural-horror", "description": "Sharp head jerk to one side, then back",
    "promptHint": "the subject holds the head still, jerks it a few inches to one side in a sharp twitch, holds a beat, then snaps it back to center while the shoulders stay motionless", "term": "twitches the head sideways" },
  { "id": "snap-head-sideways", "label": "Snap head sideways", "category": "unnatural-horror", "description": "Head whips to one side and stops dead",
    "promptHint": "the subject whips the head to one side in a single fast movement and stops it dead, chin over the shoulder, the body unmoved, then holds that position without blinking", "term": "snaps the head to one side" },
  { "id": "backbend-into-crawl", "label": "Backbend crawl", "category": "unnatural-horror", "description": "Arches backward to the floor, crawls belly-up",
    "promptHint": "the subject arches backward from standing until both palms reach the floor behind them, then advances belly-up on hands and feet, pelvis pushed high, head hanging back between the arms", "term": "backbends into a spider crawl" },
  { "id": "rise-stiff-from-lying", "label": "Stiff board rise", "category": "unnatural-horror", "description": "Rises from flat to standing without bending",
    "promptHint": "the subject lies flat on their back, then rises to standing as one rigid plank, the whole body pivoting at the heels with no bend at the waist or knees", "term": "rises stiff from lying flat" },
  { "id": "contort-the-limbs", "label": "Contort limbs", "category": "unnatural-horror", "description": "Joints rotate past their natural range",
    "promptHint": "the subject rotates the elbows and knees past their natural range, the arms folding backward and the wrists turning inward, holding each wrong angle before shifting into the next one", "term": "contorts the limbs unnaturally" },
  { "id": "jerk-like-marionette", "label": "Marionette jerk", "category": "unnatural-horror", "description": "Limbs snap upward as if pulled on strings",
    "promptHint": "the subject lets the limbs hang loose, then snaps each wrist and knee upward as if yanked from above, the body following in stiff disconnected jerks between slack pauses", "term": "jerks like a marionette" },
  { "id": "drag-self-forward", "label": "Drag self forward", "category": "unnatural-horror", "description": "Pulls forward on the forearms, legs trailing",
    "promptHint": "the subject lies face down, plants both forearms ahead, and hauls the torso forward across the floor in deliberate pulls, the legs stretched straight behind and sliding along without pushing, repeating the pull forearm over forearm", "term": "drags forward on the forearms" },
  { "id": "claw-at-the-air", "label": "Claw at air", "category": "unnatural-horror", "description": "Hands rake at empty air near the face",
    "promptHint": "the subject raises both hands to face height and rakes the fingers through empty air in repeated grabbing sweeps, the elbows jerking and the hands closing on nothing each time", "term": "claws at the air" },
  { "id": "scratch-at-door", "label": "Scratch at door", "category": "unnatural-horror", "description": "Fingernails drag down a door in strokes",
    "promptHint": "the subject presses the fingertips of both hands against the door in front of them and drags the fingernails down the surface in repeated strokes, the fingers curling tighter with each pass as the forehead leans against it", "term": "scratches at a door",
    "requires": ["door"] },
  { "id": "roll-eyes-back", "label": "Roll eyes back", "category": "unnatural-horror", "description": "Eyes roll up until only the whites show",
    "promptHint": "the subject rolls both eyes upward until only the whites show, the lids staying open and the head drifting back a few degrees, then the pupils drop into place again", "term": "rolls the eyes back" },
  { "id": "stand-still-then-lunge", "label": "Still then lunge", "category": "unnatural-horror", "description": "Motionless, then one explosive step forward",
    "promptHint": "the subject stands perfectly still with the arms at the sides, then without warning drives one foot forward and lunges the whole body toward the camera, stopping abruptly at full extension", "term": "lunges forward from a dead stop" },
  { "id": "stutter-step-forward", "label": "Stutter step", "category": "unnatural-horror", "description": "Advances in half steps with hard stops",
    "promptHint": "the subject advances in short abrupt bursts, the body snapping forward a half step at a time with a hard stop between each, the legs barely appearing to carry the motion", "term": "stutter-steps forward in jerks" },
  { "id": "walk-backward-head-turned", "label": "Walk backward head turned", "category": "unnatural-horror", "description": "Walks backward with the head turned fully",
    "promptHint": "the subject twists the head around over one shoulder until the face points behind them, then walks backward toward where the face is pointing, the feet feeling for the ground while the torso stays squared to the front", "term": "walks backward with the head turned" },
  { "id": "hang-head-arms-dangle", "label": "Hang head limp", "category": "unnatural-horror", "description": "Head drops forward, arms hang slack",
    "promptHint": "the subject lets the head drop forward until the chin rests on the chest, both arms hanging dead at the sides, the body swaying a little where it stands", "term": "hangs the head, arms dangling" },
  { "id": "twitch-the-fingers", "label": "Twitch fingers", "category": "unnatural-horror", "description": "Fingers flutter and spasm at the sides",
    "promptHint": "the subject holds both arms straight at the sides while the fingers flutter and spasm in rapid irregular bursts, each hand curling half closed and springing open again, the arms never moving", "term": "twitches the fingers rapidly" },
  { "id": "sway-head-lolling", "label": "Loll and sway", "category": "unnatural-horror", "description": "Body sways while the head rolls loose",
    "promptHint": "the subject shifts the weight from one foot to the other in a continuous sway while the head rolls loose on the neck, tipping shoulder to shoulder with the jaw slack and the eyes half open", "term": "sways with the head lolling" },
  { "id": "breathe-ragged-heaves", "label": "Ragged heaves", "category": "unnatural-horror", "description": "Chest and shoulders pump in uneven breaths",
    "promptHint": "the subject draws breath in deep uneven heaves, the chest and shoulders rising sharply and dropping, the ribs pulling in between breaths, the rhythm breaking and restarting without ever settling", "term": "breathes in ragged heaves" },
  { "id": "smile-too-wide", "label": "Smile too wide", "category": "unnatural-horror", "description": "Mouth stretches wider than natural, holds",
    "promptHint": "the subject draws the corners of the mouth back until the smile stretches wider than the face allows, teeth fully bared, then locks it there while the eyes stay flat and unmoving", "term": "smiles too wide and holds it" },
  { "id": "stare-then-blink-slowly", "label": "Slow blink stare", "category": "unnatural-horror", "description": "Unblinking stare, then one deliberate blink",
    "promptHint": "the subject holds a fixed unblinking stare straight ahead, then closes both lids in one slow deliberate blink and opens them again onto the same unmoved stare", "term": "holds an unblinking stare and blinks slowly",
    "fixedPace": true },
  { "id": "tilt-body-from-ankles", "label": "Tilt from ankles", "category": "unnatural-horror", "description": "Whole body leans sideways past balance",
    "promptHint": "the subject stays rigid from head to heel and tips sideways as one piece, pivoting only at the ankles, leaning well past the point of balance and holding there without falling", "term": "tilts sideways from the ankles" },
  { "id": "scuttle-away-on-fours", "label": "Scuttle away", "category": "unnatural-horror", "description": "Drops to all fours and scurries off fast",
    "promptHint": "the subject drops from standing onto all fours in one motion and scurries away from the camera, the limbs moving in an uneven scramble with the back staying low", "term": "scuttles away on all fours" },
  { "id": "shudder-head-to-toe", "label": "Full body shudder", "category": "unnatural-horror", "description": "One shudder passes from head to feet",
    "promptHint": "the subject stands still, then shudders in one continuous wave that travels down from the head through the shoulders, torso and legs, the knees buckling slightly before the body settles", "term": "shudders from head to toe" },
  { "id": "turn-head-first", "label": "Turn head first", "category": "unnatural-horror", "description": "Head rotates first, the body follows late",
    "promptHint": "the subject turns the head toward the camera first and holds it there, the shoulders and pelvis following a beat later in a separate stiff rotation until the whole body faces forward", "term": "turns the head before the body" },
  { "id": "shake-head-into-blur", "label": "Head shake blur", "category": "unnatural-horror", "description": "Head vibrates side to side, face blurring",
    "promptHint": "the subject shakes the head side to side so fast the features blur, the neck loose and the shoulders locked in place, then stops dead on a forward-facing stare", "term": "shakes the head into a blur" },
  { "id": "let-the-jaw-drop", "label": "Jaw drops open", "category": "unnatural-horror", "description": "Mouth falls open and stays slack",
    "promptHint": "the subject lets the jaw fall open under its own weight until the mouth hangs wide and slack, the lips loose and the tongue still, holding it open while the rest of the face stays blank", "term": "lets the jaw hang open" },
]
