import type { CharacterMotion } from "./types.js"

/** Vehicles & Mounts — 32 entries. Category id `vehicles-mounts`. */
export const VEHICLES_MOUNTS_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "get-into-car", label: "Get Into Car", category: "vehicles-mounts", description: "Pulls the driver door open and drops into the seat",
    promptHint: "the subject pulls the driver door open, plants one foot inside, ducks the head under the frame and drops onto the seat, hauling the door shut behind them",
    term: "gets into the driver seat" },
  { id: "get-out-of-car", label: "Get Out of Car", category: "vehicles-mounts", description: "Swings both legs out and stands up from the seat",
    promptHint: "the subject shoves the car door open, swings both legs out onto the ground, pushes up off the seat to stand and knocks the door closed with a hip",
    term: "gets out of the car" },
  { id: "slide-across-hood", label: "Slide Across Hood", category: "vehicles-mounts", description: "Hip-slides over the hood and lands on the far side",
    promptHint: "the subject runs at the car, drops one hip onto the hood and slides across the metal with both legs swinging through, landing on both feet on the far side",
    term: "slides across the car hood" },
  { id: "drive-off", label: "Drive Off", category: "vehicles-mounts", description: "Takes the wheel and pulls the car away",
    promptHint: "the subject settles both hands onto the steering wheel, checks forward through the windshield, turns the wheel and leans slightly back as the car pulls away",
    term: "grips the wheel and drives off" },
  { id: "shift-gears", label: "Shift Gears", category: "vehicles-mounts", description: "Drops a hand to the shifter and changes gear",
    promptHint: "the subject drops the right hand from the wheel to the shifter, presses the left foot down on the clutch pedal, slots the lever into the next gear and returns the hand to the wheel",
    term: "shifts gears" },
  { id: "check-mirror-and-turn", label: "Check Mirror & Turn", category: "vehicles-mounts", description: "Mirror glance, blind-spot look, then steers around",
    promptHint: "the subject flicks a glance up to the rearview mirror, turns the head over one shoulder to check the blind spot and feeds the wheel around hand over hand",
    term: "checks the mirror and turns" },
  { id: "lean-out-car-window", label: "Lean Out Window", category: "vehicles-mounts", description: "Head and shoulders out into the moving air",
    promptHint: "the subject rolls the window down, props one forearm on the door frame and leans the head and shoulders out into the rushing air, wind pressing against the face",
    term: "leans out the car window" },
  { id: "sit-on-car-hood", label: "Sit on Hood", category: "vehicles-mounts", description: "Pushes up off both palms to perch on the hood",
    promptHint: "the subject backs up to the front of the car, plants both palms on the hood and pushes up to perch on the metal with both feet resting on the bumper",
    term: "hops up to sit on the car hood" },
  { id: "unload-trunk", label: "Unload the Trunk", category: "vehicles-mounts", description: "Lifts the trunk lid and hauls out a heavy bag",
    promptHint: "the subject lifts the trunk lid up on its struts, bends at the knees to take a heavy bag in both hands, hauls it clear and swings the lid down",
    term: "lifts a bag from the trunk" },
  { id: "put-on-helmet", label: "Put On Helmet", category: "vehicles-mounts", description: "Pulls a helmet down and cinches the chin strap",
    promptHint: "the subject raises a helmet in both hands, spreads the sides over the ears, pulls it down onto the head and cinches the chin strap tight under the jaw",
    term: "pulls on a helmet" },
  { id: "mount-motorcycle", label: "Mount Motorcycle", category: "vehicles-mounts", description: "Swings a leg over the saddle and settles down",
    promptHint: "the subject grips both handlebars, tips the motorcycle upright off its kickstand, swings one leg over the saddle and settles down with both feet planted on the ground",
    term: "swings a leg over the motorcycle" },
  { id: "kick-start-engine", label: "Kick-Start Engine", category: "vehicles-mounts", description: "Stamps down on the kick lever and twists the throttle",
    promptHint: "the subject rises off the saddle, stamps one foot down hard on the kick lever, drops back onto the seat and twists the throttle grip toward the hip",
    term: "kick-starts the engine" },
  { id: "lean-into-turn", label: "Lean Into Turn", category: "vehicles-mounts", description: "Drops the inside shoulder and knee into a curve",
    promptHint: "the subject drops the inside shoulder toward the road, tips the torso and knee down into the curve with the arms angled across the bars, and rises upright again",
    term: "leans into the turn" },
  { id: "dismount-motorcycle", label: "Dismount Motorcycle", category: "vehicles-mounts", description: "Swings the trailing leg back over and steps off",
    promptHint: "the subject kicks the stand down, rises on the footpegs, swings the trailing leg back over the saddle and steps off to stand beside the motorcycle",
    term: "steps off the motorcycle" },
  { id: "hop-on-bike", label: "Hop on Bike", category: "vehicles-mounts", description: "Swings onto the saddle and drives the pedals down",
    promptHint: "the subject pushes the bicycle forward a step, swings one leg over the saddle, drops onto it and drives both pedals down to pull away",
    term: "pedals off on a bike" },
  { id: "brake-and-hop-off", label: "Brake & Hop Off", category: "vehicles-mounts", description: "Squeezes the brakes and steps clear of the bike",
    promptHint: "the subject squeezes both brake levers, lifts off the saddle as the bicycle slows, drops one foot to the ground and steps clear while still holding the handlebars",
    term: "brakes and hops off the bike" },
  { id: "push-scooter", label: "Push a Scooter", category: "vehicles-mounts", description: "Kicks off the ground and rolls on one foot",
    promptHint: "the subject sets one foot on the scooter deck, grips the bars, pushes off the ground with the trailing foot in repeated kicks and tucks that foot up behind as the scooter rolls",
    term: "kicks a scooter along" },
  { id: "mount-horse", label: "Mount Horse", category: "vehicles-mounts", description: "Springs off the stirrup up into the saddle",
    promptHint: "the subject sets the left foot into the stirrup, grips the saddle horn, springs up off the standing leg and swings the right leg over to settle into the saddle",
    term: "swings up into the saddle" },
  { id: "ride-at-walk", label: "Ride at a Walk", category: "vehicles-mounts", description: "Sits tall, pelvis rocking with a four-beat gait",
    promptHint: "the subject sits tall in the saddle with the reins loose in both hands, pelvis rocking forward and back in time with the four-beat footfall of the walking horse",
    term: "rides at a walk" },
  { id: "gallop-on-horseback", label: "Gallop", category: "vehicles-mounts", description: "Rises into a half-seat low over the horse's neck",
    promptHint: "the subject rises out of the saddle into a half-seat, leans low over the horse's neck with both hands pushed forward and the knees absorbing each stride as the horse gallops beneath them",
    term: "gallops in a half-seat" },
  { id: "rein-in-horse", label: "Rein In", category: "vehicles-mounts", description: "Sits deep and draws the reins back to a halt",
    promptHint: "the subject sits deep into the saddle, draws both reins back toward the pelvis and leans the shoulders back past upright as the horse gathers its hindquarters and slows to a halt",
    term: "reins the horse to a halt" },
  { id: "dismount-horse", label: "Dismount Horse", category: "vehicles-mounts", description: "Swings a leg over the rump and steps to the ground",
    promptHint: "the subject frees the right foot from the stirrup, swings that leg back over the horse's rump, lowers down the side with both hands on the saddle and lands on both feet",
    term: "swings down out of the saddle" },
  { id: "board-train", label: "Board the Train", category: "vehicles-mounts", description: "Steps across the gap as the doors slide shut",
    promptHint: "the subject steps up across the gap onto the train, grips the door edge for balance and turns to face down the aisle as the doors slide shut behind them",
    term: "steps aboard the train" },
  { id: "hold-train-strap", label: "Hold the Strap", category: "vehicles-mounts", description: "Grips an overhead strap and sways with the car",
    promptHint: "the subject reaches overhead for a hanging strap, closes a fist around it, sets the feet apart and sways from the shoulders as the train car rocks",
    term: "holds an overhead strap" },
  { id: "step-off-bus", label: "Step Off Bus", category: "vehicles-mounts", description: "Takes the handrail down the steps onto the curb",
    promptHint: "the subject takes the handrail, steps down the bus stairs one tread at a time and drops off the last step onto the curb, releasing the rail to walk on",
    term: "steps down off the bus" },
  { id: "row-boat", label: "Row a Boat", category: "vehicles-mounts", description: "Drives the legs back and lifts the blades clear",
    promptHint: "the subject leans forward with straight arms, drops both oar blades into the water, drives back with the legs and torso and lifts the blades clear at the end of the stroke",
    term: "rows with both oars" },
  { id: "paddle-kayak", label: "Paddle a Kayak", category: "vehicles-mounts", description: "Alternates blade strokes with a rotating torso",
    promptHint: "the subject plants the paddle blade forward on one side, pulls it back along the hull with a rotating torso, lifts it out and drops the opposite blade in",
    term: "paddles a kayak" },
  { id: "hail-taxi", label: "Hail a Taxi", category: "vehicles-mounts", description: "Arm straight up at traffic, then for the door handle",
    promptHint: "the subject steps off the curb, shoots one arm straight up toward the oncoming traffic and, as a cab pulls in, lowers the arm to grab the rear door handle",
    term: "hails a taxi and gets in" },
  { id: "climb-into-cab", label: "Climb Into Cab", category: "vehicles-mounts", description: "Hauls up on the grab handle into a high truck seat",
    promptHint: "the subject reaches for the handle inside the door frame, sets one foot on the running board, hauls up and swings across into the high cab seat",
    term: "climbs up into the truck cab" },
  { id: "jump-onto-moving-vehicle", label: "Jump on Moving Vehicle", category: "vehicles-mounts", description: "Sprints alongside and swings onto the running board",
    promptHint: "the subject sprints alongside the moving vehicle, catches a handhold with one arm, swings both feet off the ground and pulls up onto the running board",
    term: "jumps onto a moving vehicle" },
  { id: "grip-armrests", label: "Grip the Armrests", category: "vehicles-mounts", description: "Hands clamp the armrests as the seat pushes back",
    promptHint: "the subject settles the spine back into the seat, curls both hands over the ends of the armrests, tightens the grip until the knuckles whiten and the head presses back against the headrest",
    term: "grips the armrests" },
  { id: "stretch-in-aisle", label: "Stretch in Aisle", category: "vehicles-mounts", description: "Stands up out of the seat and reaches overhead",
    promptHint: "the subject pushes up out of the seat into the narrow aisle, reaches both arms overhead until the spine lengthens, rolls the shoulders back and lowers the arms",
    term: "stands and stretches in the aisle" },
]
