import type { CharacterMotion } from "./types.js"

/** vehicles-mounts — authored motion fragments. Stable ids survive copy revisions. */
export const VEHICLES_MOUNTS_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { "id": "get-into-car", "label": "Get into driver seat", "category": "vehicles-mounts", "description": "Opens the driver door and gets into the driver seat.",
    "promptHint": "the subject pulls the driver door open, plants one foot inside, ducks the head under the frame and drops onto the seat, hauling the door shut behind them", "term": "gets into the driver seat",
    "requires": ["car with accessible driver seat"], "aliases": ["Get Into Car"] },
  { "id": "get-out-of-car", "label": "Get out of car", "category": "vehicles-mounts", "description": "Swings both legs out and stands up from the seat",
    "promptHint": "the subject shoves the car door open, swings both legs out onto the ground, pushes up off the seat to stand and knocks the door closed with a hip", "term": "gets out of the car" },
  { "id": "slide-across-hood", "label": "Slide across hood", "category": "vehicles-mounts", "description": "Hip-slides over the hood and lands on the far side",
    "promptHint": "the subject runs at the car, drops one hip onto the hood and slides across the metal with both legs swinging through, landing on both feet on the far side", "term": "slides across the car hood" },
  { "id": "drive-off", "label": "Drive off", "category": "vehicles-mounts", "description": "Takes the wheel and pulls the car away",
    "promptHint": "the subject settles both hands onto the steering wheel, checks forward through the windshield, turns the wheel and leans slightly back as the car pulls away", "term": "grips the wheel and drives off" },
  { "id": "shift-gears", "label": "Shift manual gears", "category": "vehicles-mounts", "description": "Moves a manual gear lever using the nearer hand.",
    "promptHint": "the subject remains seated in the driver seat, grips the manual gear lever with the nearer hand and moves it into the next gear while preserving the established vehicle layout", "term": "shifts manual gears using the nearer hand",
    "startPose": "seated", "endPose": "seated", "requires": ["manual-transmission vehicle"], "aliases": ["Shift Gears", "stick shift"] },
  { "id": "check-mirror-and-turn", "label": "Check mirror & turn", "category": "vehicles-mounts", "description": "Mirror glance, blind-spot look, then steers around",
    "promptHint": "the subject flicks a glance up to the rearview mirror, turns the head over one shoulder to check the blind spot and feeds the wheel around hand over hand", "term": "checks the mirror and turns" },
  { "id": "lean-out-car-window", "label": "Lean out window", "category": "vehicles-mounts", "description": "Head and shoulders out into the moving air",
    "promptHint": "the subject rolls the window down, props one forearm on the door frame and leans the head and shoulders out into the rushing air, wind pressing against the face", "term": "leans out the car window" },
  { "id": "sit-on-car-hood", "label": "Sit on hood", "category": "vehicles-mounts", "description": "Pushes up off both palms to perch on the hood",
    "promptHint": "the subject backs up to the front of the car, plants both palms on the hood and pushes up to perch on the metal with both feet resting on the bumper", "term": "hops up to sit on the car hood" },
  { "id": "unload-trunk", "label": "Unload the trunk", "category": "vehicles-mounts", "description": "Lifts the trunk lid and hauls out a heavy bag",
    "promptHint": "the subject lifts the trunk lid up on its struts, bends at the knees to take a heavy bag in both hands, hauls it clear and swings the lid down", "term": "lifts a bag from the trunk" },
  { "id": "put-on-helmet", "label": "Put on helmet", "category": "vehicles-mounts", "description": "Pulls a helmet down and cinches the chin strap",
    "promptHint": "the subject raises a helmet in both hands, spreads the sides over the ears, pulls it down onto the head and cinches the chin strap tight under the jaw", "term": "pulls on a helmet" },
  { "id": "mount-motorcycle", "label": "Mount motorcycle", "category": "vehicles-mounts", "description": "Swings a leg over the saddle and settles down",
    "promptHint": "the subject grips both handlebars, tips the motorcycle upright off its kickstand, swings one leg over the saddle and settles down with both feet planted on the ground", "term": "swings a leg over the motorcycle" },
  { "id": "kick-start-engine", "label": "Kick-start engine", "category": "vehicles-mounts", "description": "Stamps down on the kick lever and twists the throttle",
    "promptHint": "the subject rises off the saddle, stamps one foot down hard on the kick lever, drops back onto the seat and twists the throttle grip toward the hip", "term": "kick-starts the engine" },
  { "id": "lean-into-turn", "label": "Lean motorcycle into turn", "category": "vehicles-mounts", "description": "Drops the inside shoulder and knee into a curve",
    "promptHint": "the subject drops the inside shoulder toward the road, tips the torso and knee down into the curve with the arms angled across the bars, and rises upright again", "term": "leans into the turn",
    "requires": ["motorcycle"], "aliases": ["Lean Into Turn"] },
  { "id": "dismount-motorcycle", "label": "Dismount motorcycle", "category": "vehicles-mounts", "description": "Swings the trailing leg back over and steps off",
    "promptHint": "the subject kicks the stand down, rises on the footpegs, swings the trailing leg back over the saddle and steps off to stand beside the motorcycle", "term": "steps off the motorcycle" },
  { "id": "hop-on-bike", "label": "Mount bicycle and ride off", "category": "vehicles-mounts", "description": "Swings onto the bicycle and pedals away.",
    "promptHint": "the subject holds the handlebars, swings one leg over the bicycle, settles onto the saddle and pedals forward with alternating leg strokes", "term": "mounts a bicycle and pedals away",
    "aliases": ["Hop on Bike"], "requires": ["bicycle"], "startPose": "standing", "endPose": "seated", "kind": "compound" },
  { "id": "brake-and-hop-off", "label": "Brake & hop off", "category": "vehicles-mounts", "description": "Squeezes the brakes and steps clear of the bike",
    "promptHint": "the subject squeezes both brake levers, lifts off the saddle as the bicycle slows, drops one foot to the ground and steps clear while still holding the handlebars", "term": "brakes and hops off the bike" },
  { "id": "push-scooter", "label": "Push a scooter", "category": "vehicles-mounts", "description": "Kicks off the ground and rolls on one foot",
    "promptHint": "the subject sets one foot on the scooter deck, grips the bars, pushes off the ground with the trailing foot in repeated kicks and tucks that foot up behind as the scooter rolls", "term": "kicks a scooter along" },
  { "id": "mount-horse", "label": "Mount horse from left", "category": "vehicles-mounts", "description": "Steps into the left stirrup and swings the right leg over the saddle.",
    "promptHint": "the subject stands on the horse’s left, places the left foot in the stirrup, steadies against the saddle, rises and swings the right leg over, then settles into the saddle and finds the right stirrup", "term": "mounts a saddled horse from the left",
    "requires": ["saddled horse"], "startPose": "standing", "endPose": "seated", "kind": "compound", "aliases": ["Mount Horse"] },
  { "id": "ride-at-walk", "label": "Ride at a walk", "category": "vehicles-mounts", "description": "Sits tall, pelvis rocking with a four-beat gait",
    "promptHint": "the subject sits tall in the saddle with the reins loose in both hands, pelvis rocking forward and back in time with the four-beat footfall of the walking horse", "term": "rides at a walk" },
  { "id": "gallop-on-horseback", "label": "Gallop", "category": "vehicles-mounts", "description": "Rises into a half-seat low over the horse's neck",
    "promptHint": "the subject rises out of the saddle into a half-seat, leans low over the horse's neck with both hands pushed forward and the knees absorbing each stride as the horse gallops beneath them", "term": "gallops in a half-seat" },
  { "id": "rein-in-horse", "label": "Rein in", "category": "vehicles-mounts", "description": "Sits deep and draws the reins back to a halt",
    "promptHint": "the subject sits deep into the saddle, draws both reins back toward the pelvis and leans the shoulders back past upright as the horse gathers its hindquarters and slows to a halt", "term": "reins the horse to a halt" },
  { "id": "dismount-horse", "label": "Dismount horse to left", "category": "vehicles-mounts", "description": "Frees both feet from the stirrups and lowers to the ground on the left.",
    "promptHint": "the subject sits in the saddle, frees both feet from the stirrups, steadies against the saddle, swings the right leg over the horse’s back and lowers to the ground on the left, landing on both feet", "term": "frees both stirrups, dismounting the horse leftward",
    "startPose": "seated", "endPose": "standing", "requires": ["saddled horse"], "kind": "compound", "aliases": ["Dismount Horse"] },
  { "id": "board-train", "label": "Board the train", "category": "vehicles-mounts", "description": "Steps across the gap as the doors slide shut",
    "promptHint": "the subject steps up across the gap onto the train, grips the door edge for balance and turns to face down the aisle as the doors slide shut behind them", "term": "steps aboard the train" },
  { "id": "hold-train-strap", "label": "Hold the strap", "category": "vehicles-mounts", "description": "Grips an overhead strap and sways with the car",
    "promptHint": "the subject reaches overhead for a hanging strap, closes a fist around it, sets the feet apart and sways from the shoulders as the train car rocks", "term": "holds an overhead strap" },
  { "id": "step-off-bus", "label": "Step off bus", "category": "vehicles-mounts", "description": "Takes the handrail down the steps onto the curb",
    "promptHint": "the subject takes the handrail, steps down the bus stairs one tread at a time and drops off the last step onto the curb, releasing the rail to walk on", "term": "steps down off the bus" },
  { "id": "row-boat", "label": "Row fixed-seat boat", "category": "vehicles-mounts", "description": "Pulls the oars with arms and torso from a fixed seat.",
    "promptHint": "the subject sits on a fixed rowing seat, reaches forward with both oars, draws the handles toward the torso and lifts the blades clear before returning for another stroke, keeping the feet braced", "term": "rows a fixed-seat boat with paired oars",
    "startPose": "seated", "endPose": "seated", "requires": ["fixed-seat rowboat", "paired oars"], "aliases": ["Row a Boat"] },
  { "id": "paddle-kayak", "label": "Paddle a kayak", "category": "vehicles-mounts", "description": "Alternates blade strokes with a rotating torso",
    "promptHint": "the subject plants the paddle blade forward on one side, pulls it back along the hull with a rotating torso, lifts it out and drops the opposite blade in", "term": "paddles a kayak" },
  { "id": "hail-taxi", "label": "Hail a taxi", "category": "vehicles-mounts", "description": "Raises one arm toward approaching taxis, then lowers it.",
    "promptHint": "the subject stands beside the curb, raises one arm toward an approaching taxi and lowers the arm as it approaches", "term": "raises an arm to hail a taxi",
    "startPose": "standing", "needsFreeHands": true },
  { "id": "climb-into-cab", "label": "Climb into truck cab", "category": "vehicles-mounts", "description": "Hauls up on the grab handle into a high truck seat",
    "promptHint": "the subject reaches for the handle inside the door frame, sets one foot on the running board, hauls up and swings across into the high cab seat", "term": "climbs up into the truck cab",
    "requires": ["truck cab"], "aliases": ["Climb Into Cab"] },
  { "id": "jump-onto-moving-vehicle", "label": "Jump on moving vehicle", "category": "vehicles-mounts", "description": "Sprints alongside and swings onto the running board",
    "promptHint": "the subject sprints alongside the moving vehicle, catches a handhold with one arm, swings both feet off the ground and pulls up onto the running board", "term": "jumps onto a moving vehicle" },
  { "id": "grip-armrests", "label": "Grip the armrests", "category": "vehicles-mounts", "description": "Hands clamp the armrests as the seat pushes back",
    "promptHint": "the subject settles the spine back into the seat, curls both hands over the ends of the armrests, tightens the grip until the knuckles whiten and the head presses back against the headrest", "term": "grips the armrests" },
  { "id": "stretch-in-aisle", "label": "Stretch in aisle", "category": "vehicles-mounts", "description": "Stands up out of the seat and reaches overhead",
    "promptHint": "the subject pushes up out of the seat into the narrow aisle, reaches both arms overhead until the spine lengthens, rolls the shoulders back and lowers the arms", "term": "stands and stretches in the aisle" },
  { "id": "turn-wheelchair-left", "label": "Turn wheelchair left", "category": "vehicles-mounts", "description": "Turn wheelchair left.",
    "term": "turns a manual wheelchair toward their own left", "promptHint": "the subject pushes the hand rims asymmetrically to turn the manual wheelchair toward the subject’s left",
    "requires": ["manual wheelchair"], "startPose": "seated", "endPose": "seated" },
  { "id": "turn-wheelchair-right", "label": "Turn wheelchair right", "category": "vehicles-mounts", "description": "Turn wheelchair right.",
    "term": "turns a manual wheelchair toward their own right", "promptHint": "the subject pushes the hand rims asymmetrically to turn the manual wheelchair toward the subject’s right",
    "requires": ["manual wheelchair"], "startPose": "seated", "endPose": "seated" },
  { "id": "drive-powered-wheelchair", "label": "Drive powered wheelchair", "category": "vehicles-mounts", "description": "Drive powered wheelchair.",
    "term": "drives a powered wheelchair forward", "promptHint": "the subject moves the joystick to drive the powered wheelchair steadily forward while remaining seated",
    "requires": ["powered wheelchair"], "startPose": "seated", "endPose": "seated", "aliases": ["electric wheelchair"] },
  { "id": "stop-powered-wheelchair", "label": "Stop powered wheelchair", "category": "vehicles-mounts", "description": "Stop powered wheelchair.",
    "term": "returns the powered-wheelchair joystick to neutral and stops", "promptHint": "the subject returns the powered-wheelchair joystick to neutral and comes to a controlled stop",
    "requires": ["powered wheelchair"], "startPose": "seated", "endPose": "seated" },
  { "id": "ride-bicycle-continuously", "label": "Ride bicycle continuously", "category": "vehicles-mounts", "description": "Ride bicycle continuously.",
    "term": "pedals a bicycle continuously", "promptHint": "the subject remains seated on the bicycle and pedals steadily with alternating leg strokes",
    "requires": ["bicycle"] },
  { "id": "brake-bicycle", "label": "Brake bicycle to stop", "category": "vehicles-mounts", "description": "Brake bicycle to stop.",
    "term": "brakes bicycle to rest and plants one foot", "promptHint": "the subject squeezes the bicycle brake levers, slows to a stop and places one foot on the ground",
    "requires": ["bicycle"] },
  { "id": "park-bicycle", "label": "Park bicycle", "category": "vehicles-mounts", "description": "Park bicycle.",
    "term": "stops and rests a bicycle on its stand", "promptHint": "the subject stops beside the bicycle, lowers its kickstand and rests the bicycle on it",
    "requires": ["bicycle with kickstand"] },
  { "id": "enter-car-passenger-seat", "label": "Enter car passenger seat", "category": "vehicles-mounts", "description": "Enter car passenger seat.",
    "term": "opens passenger door and sits in passenger seat", "promptHint": "the subject opens the passenger door, turns to sit in the seat and draws both legs inside",
    "requires": ["car passenger door"] },
  { "id": "unbuckle-seatbelt", "label": "Unbuckle seat belt", "category": "vehicles-mounts", "description": "Unbuckle seat belt.",
    "term": "unbuckles the seat belt and guides it back", "promptHint": "the subject presses the seat-belt release and guides the belt back toward its anchor",
    "requires": ["fastened seat belt"] },
]
