import type { CharacterMotion } from "./types.js"

/** Walks & Runs — 40 entries. Category id `walks-runs`. */
export const WALKS_RUNS_MOTIONS: ReadonlyArray<CharacterMotion> = [
  { id: "stroll-casually", label: "Casual Stroll", category: "walks-runs", description: "Relaxed unhurried walk, loose arms, easy steps",
    promptHint: "the subject strolls forward with short relaxed steps, weight rolling easily heel to toe, arms swinging loosely at the sides, shoulders down and head drifting to look around",
    term: "strolls casually, arms loose" },
  { id: "walk-briskly", label: "Brisk Walk", category: "walks-runs", description: "Purposeful clipped steps, arms swinging",
    promptHint: "the subject walks briskly with clipped purposeful steps, heels striking firmly, arms swinging in a tight rhythm, torso upright and eyes fixed on a point ahead",
    term: "walks briskly with purpose" },
  { id: "power-walk", label: "Power Walk", category: "walks-runs", description: "Fitness walk, elbows bent, arms pumping hard",
    promptHint: "the subject power-walks with elbows bent at ninety degrees and arms pumping hard, pelvis driving each long stride, heels planting and toes pushing off with visible effort",
    term: "power-walks, arms pumping" },
  { id: "stride-confidently", label: "Confident Stride", category: "walks-runs", description: "Long even strides, chest up, shoulders back",
    promptHint: "the subject strides forward with long even steps, chest lifted and shoulders back, arms swinging in a full relaxed arc, each foot landing squarely with the weight committed",
    term: "strides forward confidently" },
  { id: "jog-forward", label: "Jog", category: "walks-runs", description: "Light steady run, elbows bent, gentle bounce",
    promptHint: "the subject jogs forward, elbows bent and hands loose near the waist, short strides landing midfoot, a gentle bounce in each step and breathing even",
    term: "jogs forward, elbows bent" },
  { id: "sprint-flat-out", label: "Sprint", category: "walks-runs", description: "All-out run, knees driving, arms pumping",
    promptHint: "the subject sprints flat out, torso leaning forward, knees driving high, arms pumping in sharp opposition, feet striking on the balls and pushing off hard behind",
    term: "sprints flat out" },
  { id: "tiptoe-forward", label: "Tiptoe", category: "walks-runs", description: "Heels lifted, small careful steps on the toes",
    promptHint: "the subject rises onto the balls of the feet and tiptoes forward with heels lifted, small careful steps, arms held slightly out for balance and shoulders raised",
    term: "tiptoes forward, heels lifted" },
  { id: "sneak-forward", label: "Sneak", category: "walks-runs", description: "Low crouch, soft toe-first steps, eyes scanning",
    promptHint: "the subject sneaks forward in a low crouch, knees bent, placing each foot down softly toe first, arms drawn in close to the body, head turning to check both sides",
    term: "sneaks forward in a crouch" },
  { id: "stagger-unsteadily", label: "Stagger", category: "walks-runs", description: "Weaving unsteady walk, arms out for balance",
    promptHint: "the subject staggers forward unsteadily, weight lurching from one foot to the other, path weaving side to side, arms floating out to catch balance and head lolling",
    term: "staggers unsteadily, weaving" },
  { id: "limp-forward", label: "Limp", category: "walks-runs", description: "Favoring one leg, uneven dipping gait",
    promptHint: "the subject limps forward favoring one leg, the stiff leg taking a short guarded step while the other swings through, the body dipping on each weighted step",
    term: "limps, favoring one leg" },
  { id: "march-in-cadence", label: "March", category: "walks-runs", description: "Military cadence, high knees, stiff arm swing",
    promptHint: "the subject marches forward in strict military cadence, knees lifting high, legs snapping straight, arms swinging stiffly shoulder-high in opposition, spine rigid and chin level",
    term: "marches in military cadence" },
  { id: "walk-backwards", label: "Walk Backwards", category: "walks-runs", description: "Stepping backward, glancing over one shoulder",
    promptHint: "the subject walks backwards, each foot reaching behind and landing toe first before the heel settles, weight shifting carefully, glancing over one shoulder to check the path",
    term: "walks backwards" },
  { id: "skip-along", label: "Skip", category: "walks-runs", description: "Step-hop bounce on alternating feet",
    promptHint: "the subject skips forward in a step-hop rhythm, alternating feet, bouncing up off each hop with arms swinging freely and a light springy lift through the whole body",
    term: "skips along" },
  { id: "hop-on-one-foot", label: "Hop", category: "walks-runs", description: "Bounding forward on one foot",
    promptHint: "the subject hops forward on one foot, the other leg bent and lifted, arms pumping with each push-off, landing and springing again in a chain of small bounds",
    term: "hops on one foot" },
  { id: "crawl-on-all-fours", label: "Crawl", category: "walks-runs", description: "Hands and knees, opposite limbs advancing",
    promptHint: "the subject crawls forward on hands and knees, opposite hand and knee advancing together, back level, head lifted to look ahead as the weight rocks from limb to limb",
    term: "crawls on hands and knees" },
  { id: "army-crawl-forward", label: "Army Crawl", category: "walks-runs", description: "Flat on the belly, pulling forward on elbows",
    promptHint: "the subject drops flat and army-crawls forward on the belly, dragging the body along with alternating elbows and knees, head kept low and chest pressed to the ground",
    term: "army-crawls on the belly" },
  { id: "wade-through-water", label: "Wade", category: "walks-runs", description: "High deliberate steps against the water's drag",
    promptHint: "the subject wades forward through the water, lifting each knee high and pushing it through against the drag, arms raised clear of the surface, torso leaning slightly into each step as the weight commits late",
    term: "wades through water" },
  { id: "shuffle-forward", label: "Shuffle", category: "walks-runs", description: "Feet barely leaving the ground, slumped",
    promptHint: "the subject shuffles forward with feet barely leaving the ground, short scuffing steps, shoulders slumped, arms hanging still and the head bowed",
    term: "shuffles, feet scuffing the ground" },
  { id: "scurry-forward", label: "Scurry", category: "walks-runs", description: "Hurried tiny steps, hunched and leaning ahead",
    promptHint: "the subject scurries forward in hurried tiny steps, shoulders hunched, elbows tucked, upper body leaning ahead of the feet as if late, eyes darting",
    term: "scurries with tiny hunched steps" },
  { id: "stroll-hands-in-pockets", label: "Hands in Pockets Stroll", category: "walks-runs", description: "Elbows out, loose rolling steps, slight forward lean",
    promptHint: "the subject strolls forward with both hands tucked into pockets, elbows angled out, shoulders relaxed, loose rolling steps and a slight forward lean of the head",
    term: "strolls with hands in pockets" },
  { id: "walk-while-talking", label: "Walk & Talk", category: "walks-runs", description: "Steady walk with hands gesturing mid-speech",
    promptHint: "the subject walks while talking, steps steady and unbroken, mouth moving in speech, hands gesturing in time with the words, head turning aside mid-sentence and back to the path ahead",
    term: "walks and talks, gesturing" },
  { id: "trudge-wearily", label: "Trudge", category: "walks-runs", description: "Heavy weary steps, head down, feet dragging",
    promptHint: "the subject trudges forward with heavy weary steps, feet dragging and landing flat, shoulders sagging under the effort, head down and arms hanging limp at the sides",
    term: "trudges wearily" },
  { id: "prance-forward", label: "Prance", category: "walks-runs", description: "Springy high-knee steps, toes pointed",
    promptHint: "the subject prances forward with springy high-knee steps, toes pointed on each lift, chest up and arms held out lightly, bouncing playfully off the balls of the feet",
    term: "prances with high knees" },
  { id: "strut-boldly", label: "Strut", category: "walks-runs", description: "Chest out, exaggerated arm swing, bold stamps",
    promptHint: "the subject struts forward with chest pushed out, chin raised, exaggerated arm swing and long bold steps that land with a deliberate stamp, shoulders squared",
    term: "struts, chest out" },
  { id: "swagger-forward", label: "Swagger", category: "walks-runs", description: "Wide lazy stride, shoulders rolling",
    promptHint: "the subject swaggers forward with a wide lazy stride, shoulders rolling side to side with each step, arms swinging loose and low, weight sinking into every landing",
    term: "swaggers, shoulders rolling" },
  { id: "sashay-forward", label: "Sashay", category: "walks-runs", description: "Hip-swaying walk, feet crossing on one line",
    promptHint: "the subject sashays forward with hips swaying side to side, each foot crossing in front of the other along a single line, shoulders back and one hand trailing at the hip",
    term: "sashays with swaying hips", adultOnly: true },
  { id: "run-in-panic", label: "Panicked Run", category: "walks-runs", description: "Frantic escape run, glancing back",
    promptHint: "the subject runs in panic, arms flailing loosely, strides uneven and frantic, torso twisting to glance back over a shoulder before facing forward and pushing harder",
    term: "runs in panic, glancing back" },
  { id: "run-crouched", label: "Crouched Run", category: "walks-runs", description: "Low tactical run, knees bent, head ducked",
    promptHint: "the subject runs low in a crouch, knees deeply bent and torso folded forward, head ducked, arms tucked in, feet moving in short driving steps that keep the body down",
    term: "runs low in a crouch" },
  { id: "climb-stairs", label: "Climb Stairs", category: "walks-runs", description: "Knee lifts to each step, hand sliding up the rail",
    promptHint: "the subject climbs a flight of stairs, lifting each knee to plant the whole foot on the next step, weight driving up through the leading leg, one hand sliding along the rail and torso tipped slightly forward",
    term: "climbs the stairs" },
  { id: "descend-stairs", label: "Descend Stairs", category: "walks-runs", description: "Toe-first steps down, weight lowered under control",
    promptHint: "the subject descends a flight of stairs, each foot reaching down to the next step toe first before the heel settles, weight lowering under control, chin level and one hand trailing on the rail",
    term: "descends the stairs" },
  { id: "push-through-crowd", label: "Push Through Crowd", category: "walks-runs", description: "Shoulder wedged forward, forearm parting the way",
    promptHint: "the subject pushes through the crowd, turning one shoulder forward to wedge between bodies, forearm raised to part the way, pelvis twisting sideways and short driving steps forcing a path ahead",
    term: "shoulders through the crowd" },
  { id: "sidle-along-wall", label: "Sidle Along Wall", category: "walks-runs", description: "Back and palms flat to the wall, side-stepping",
    promptHint: "the subject sidles along the wall with back and palms pressed flat against it, stepping sideways one foot after the other, knees soft, head turned to watch the direction of travel",
    term: "sidles along the wall, back pressed" },
  { id: "stomp-off-angrily", label: "Stomp Off", category: "walks-runs", description: "Storms away, flat heavy stamps, fists clenched",
    promptHint: "the subject turns sharply and stomps off, each foot slamming down flat and heavy, fists clenched and arms swinging stiffly, shoulders squared and head held rigidly forward without looking back",
    term: "stomps off, fists clenched" },
  { id: "zombie-shamble", label: "Zombie Shamble", category: "walks-runs", description: "Stiff outstretched arms, pitched torso, one foot dragging",
    promptHint: "the subject shambles forward with both arms held stiffly outstretched, torso pitched forward off balance, one leg dragging behind as the other lurches ahead, head hanging to one side and jaw slack",
    term: "shambles, arms stiffly outstretched" },
  { id: "sleepwalk-forward", label: "Sleepwalk", category: "walks-runs", description: "Eyes half-closed, arms out ahead, flat-footed drift",
    promptHint: "the subject sleepwalks forward with eyes half-closed and face slack, both arms extended straight ahead, flat-footed steps drifting in a straight line, the body upright and not reacting to anything around it",
    term: "sleepwalks, arms held out ahead" },
  { id: "run-in-circles", label: "Run in Circles", category: "walks-runs", description: "Tight looping run, body leaning into the turn",
    promptHint: "the subject runs in tight circles, body leaning into the turn, inside foot pivoting on each stride while the outside leg pushes wide, arms held out and head whipping around to keep looking ahead",
    term: "runs in tight circles" },
  { id: "brace-against-wind", label: "Brace Against Wind", category: "walks-runs", description: "Torso pitched forward, forearm shielding the face",
    promptHint: "the subject leans hard into the wind, torso pitched forward with one shoulder dropped, forearm raised to shield the face, feet planting wide in short braced steps that fight for every stride",
    term: "leans into the wind, forearm up" },
  { id: "walk-with-cane", label: "Walk with Cane", category: "walks-runs", description: "Cane plants in time with the opposite foot",
    promptHint: "the subject walks forward with a cane, planting its tip ahead in time with the opposite foot, weight leaning briefly onto the cane hand as the other leg swings through, steps short and even",
    term: "walks with a cane" },
  { id: "roll-forward-in-wheelchair", label: "Wheelchair Roll", category: "walks-runs", description: "Both hands drive the push rims in matched strokes",
    promptHint: "the subject rolls forward in a wheelchair, both hands gripping the push rims and driving them forward in matched strokes, shoulders rounding on each push and releasing on the return, chin up and looking ahead",
    term: "rolls forward in a wheelchair" },
  { id: "pull-rolling-suitcase", label: "Pull Rolling Suitcase", category: "walks-runs", description: "One arm trailing back on the handle, case on its wheels",
    promptHint: "the subject walks forward pulling a rolling suitcase, one arm trailing straight back to the extended handle, the case tilted onto its wheels behind, torso angled slightly toward the free side and the other arm swinging",
    term: "walks pulling a rolling suitcase" },
]
