/**
 * "Found nothing" and "this is not a feed" are different outcomes, and only one
 * of them may be billed.
 *
 *  - A RECOGNISED feed root (`<rss>`, `<rdf:RDF>`, `<feed>`) with zero items is
 *    a valid empty feed → `[]`. The route completes and charges it: the
 *    documented "a run that finds nothing is a completed run" policy.
 *  - A document with NO recognised root and no items (an HTML error page, JSON,
 *    garbage) is not a feed → the parser THROWS, and the route's failure path
 *    marks the job failed and refunds it.
 *
 * Before this, both parsed to `[]` and both were charged.
 */
import { describe, it, expect } from "vitest"
import { parseRssXml } from "../parser.js"
import { HTML_ERROR_PAGE } from "./fixtures/atom-feeds.js"

describe("parseRssXml — a valid empty feed is [] (completed, charged)", () => {
  it.each([
    ["Atom", `<?xml version="1.0"?><feed xmlns="http://www.w3.org/2005/Atom"><title>Empty</title></feed>`],
    ["RSS 2.0", `<?xml version="1.0"?><rss version="2.0"><channel><title>Empty</title></channel></rss>`],
    ["RSS 1.0", `<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/"><channel/></rdf:RDF>`],
    ["a self-closing root", `<feed xmlns="http://www.w3.org/2005/Atom"/>`],
    ["a prefixed Atom root", `<atom:feed xmlns:atom="http://www.w3.org/2005/Atom"><atom:title>Empty</atom:title></atom:feed>`],
  ])("%s", (_name, xml) => {
    expect(parseRssXml(xml)).toEqual([])
  })

  it("skips the prolog, processing instructions, comments and a DOCTYPE before the root", () => {
    const xml = `\uFEFF  <?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/feed.xsl"?>
<!-- generated by example > 1.0 -->
<!DOCTYPE rss PUBLIC "-//Netscape Communications//DTD RSS 0.91//EN" "http://my.netscape.com/publish/formats/rss-0.91.dtd" [
  <!ENTITY copy "&#169;">
]>
<rss version="0.91"><channel><title>Empty</title></channel></rss>`
    expect(parseRssXml(xml)).toEqual([])
  })

  it("keeps a recognised root with garbage inside at [] rather than throwing", () => {
    expect(parseRssXml(`<rss version="2.0"><channel><<>broken</channel>`)).toEqual([])
  })
})

describe("parseRssXml — a document that is not a feed throws (failed, refunded)", () => {
  it("an HTML error page", () => {
    expect(() => parseRssXml(HTML_ERROR_PAGE)).toThrow(/not an RSS or Atom feed/i)
  })

  it("names the element it found, and never echoes the body", () => {
    let message = ""
    try {
      parseRssXml(HTML_ERROR_PAGE)
    } catch (err) {
      message = (err as Error).message
    }
    expect(message).toContain("<html>")
    expect(message).not.toContain("Error 404")
    expect(message).not.toContain("/feeds/videos.xml")
    expect(message.length).toBeLessThan(300)
  })

  it.each([
    ["JSON", `{"items":[{"title":"a"}]}`],
    ["plain text", "not xml at all"],
    ["an empty body", ""],
    ["whitespace only", "  \n\t "],
    ["a broken opening tag", "<rss<<>broken"],
    ["another XML vocabulary", `<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://e.com/</loc></url></urlset>`],
    ["an OPML outline", `<opml version="2.0"><body><outline text="a" xmlUrl="https://e.com/feed"/></body></opml>`],
  ])("%s", (_name, body) => {
    expect(() => parseRssXml(body)).toThrow(/not an RSS or Atom feed/i)
  })

  it("is decided by the ROOT element — a page that merely mentions <feed> or <rss> is still not a feed", () => {
    const page = `<!DOCTYPE html><html><body><pre>&lt;feed&gt;</pre><code><feed xmlns="http://www.w3.org/2005/Atom"></feed></code><p>and <rss version="2.0"></rss></p></body></html>`
    expect(() => parseRssXml(page)).toThrow(/not an RSS or Atom feed/i)
  })

  it("a prefixed <feed> root counts only when its prefix is bound to the Atom namespace", () => {
    const other = `<x:feed xmlns:x="urn:some-other-vocabulary"><x:title>Not Atom</x:title></x:feed>`
    expect(() => parseRssXml(other)).toThrow(/not an RSS or Atom feed/i)
  })

  it("caps an absurdly long element name in the message", () => {
    const name = "x".repeat(500)
    let message = ""
    try {
      parseRssXml(`<${name}></${name}>`)
    } catch (err) {
      message = (err as Error).message
    }
    expect(message).toMatch(/not an RSS or Atom feed/i)
    expect(message.length).toBeLessThan(300)
  })
})

describe("parseRssXml — items win over the root check (nothing that parsed before stops parsing)", () => {
  it("still returns the items of a feed whose server printed a warning before the prolog", () => {
    const xml = `Warning: Undefined variable $x in /var/www/feed.php on line 12
<?xml version="1.0"?>
<rss version="2.0"><channel><item><title>Still here</title><link>https://e.com/a</link></item></channel></rss>`
    expect(parseRssXml(xml).map((i) => i.title)).toEqual(["Still here"])
  })

  it("reads RSS 1.0 (<rdf:RDF>) items, which sit beside the channel", () => {
    const xml = `<?xml version="1.0"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns="http://purl.org/rss/1.0/">
  <channel rdf:about="https://e.com/"><title>RDF feed</title></channel>
  <item rdf:about="https://e.com/a">
    <title>RDF item</title>
    <link>https://e.com/a</link>
    <description>An RSS 1.0 item</description>
  </item>
</rdf:RDF>`
    expect(parseRssXml(xml)).toEqual([
      { title: "RDF item", url: "https://e.com/a", description: "An RSS 1.0 item", pubDate: "", guid: "https://e.com/a" },
    ])
  })
})
